//! File signature identification — auto-generated from file_signatures.json

pub struct FileSignature {
    pub sig_hex: &'static str,
    pub iso: Option<&'static str>,
    pub url: Option<&'static str>,
    pub extension: Option<&'static str>,
    pub desc: &'static str,
    pub popular: bool,
}

pub static FILE_SIGNATURES: &[FileSignature] = &[
    FileSignature {
        sig_hex: "2321",
        iso: Some("23 21"),
        url: None,
        extension: None,
        desc: "Script or data to be passed to the program following the Shebang (Unix)shebang (#!)",
        popular: false,
    },
    FileSignature {
        sig_hex: "a1b2c3d4d4c3b2a1",
        iso: Some("a1 b2 c3 d4 d4 c3 b2 a1"),
        url: Some("https://wiki.wireshark.org/Development/LibpcapFileFormat#Global_Header"),
        extension: Some("pcap"),
        desc: "Libpcap File Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "0a0d0d0a",
        iso: None,
        url: Some("https://www.winpcap.org/ntar/draft/PCAP-DumpFileFormat.html#sectionshb "),
        extension: Some("pcapng"),
        desc: "PCAP Next Generation Dump File Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "edabeedb",
        iso: Some("ed ab ee db"),
        url: Some("ftp://ftp.tuwien.ac.at/.vhost/www.openpkg.org/doc/book/maximum-rpm.html/node26.html "),
        extension: Some("rpm"),
        desc: "RedHat Package Manager (RPM) package",
        popular: false,
    },
    FileSignature {
        sig_hex: "53514c69746520666f726d6174203300",
        iso: Some("SQLite format 3."),
        url: Some("https://www.sqlite.org/fileformat.html "),
        extension: Some("sqlitedbsqlitedb"),
        desc: "SQLite Database",
        popular: false,
    },
    FileSignature {
        sig_hex: "53503031",
        iso: Some("SP01"),
        url: Some("https://github.com/NiLuJe/KindleTool "),
        extension: Some("bin"),
        desc: "Amazon Kindle Update Package",
        popular: false,
    },
    FileSignature {
        sig_hex: "00",
        iso: None,
        url: None,
        extension: Some("PICPIFSEAYTR"),
        desc: "IBM Storyboard bitmap file Windows Program information fileProgram Information File Mac StuffItStuffit Self-Extracting Archive IRIS Optical character recognitionOCR data file",
        popular: false,
    },
    FileSignature {
        sig_hex: "000000000000000000000000000000000000000000000000",
        iso: None,
        url: None,
        extension: Some("PDB"),
        desc: "PalmPilot Database/Document File",
        popular: false,
    },
    FileSignature {
        sig_hex: "BEBAFECA",
        iso: Some("BE BA FE CA"),
        url: None,
        extension: Some("DBA"),
        desc: "Palm (PDA)Palm Desktop Calendar Archive",
        popular: false,
    },
    FileSignature {
        sig_hex: "00014244",
        iso: Some("..BD"),
        url: None,
        extension: Some("DBA"),
        desc: "Palm Desktop To Do Archive",
        popular: false,
    },
    FileSignature {
        sig_hex: "00014454",
        iso: Some("..DT"),
        url: None,
        extension: Some("TDA"),
        desc: "Palm Desktop Calendar Archive",
        popular: false,
    },
    FileSignature {
        sig_hex: "54444624",
        iso: Some("TDF$"),
        url: None,
        extension: Some("TDF$"),
        desc: "Telegram Desktop File",
        popular: false,
    },
    FileSignature {
        sig_hex: "54444546",
        iso: Some("TDEF"),
        url: None,
        extension: Some("TDEF"),
        desc: "Telegram Desktop Encrypted File",
        popular: false,
    },
    FileSignature {
        sig_hex: "00010000",
        iso: Some("00 01 00 00"),
        url: None,
        extension: None,
        desc: "Palm Desktop Data File (Microsoft AccessAccess format)",
        popular: false,
    },
    FileSignature {
        sig_hex: "00000100",
        iso: None,
        url: None,
        extension: Some("ico"),
        desc: "Computer icon encoded in ICO (file format)ICO file format[http://msdn.microsoft.com/en-us/library/ms997538.aspx Icons] (at MSDN)",
        popular: false,
    },
    FileSignature {
        sig_hex: "667479703367",
        iso: Some("ftyp3g"),
        url: None,
        extension: Some("3gp3g2"),
        desc: "3rd Generation Partnership Project 3GPP and 3GPP2 multimedia files",
        popular: false,
    },
    FileSignature {
        sig_hex: "1F9D",
        iso: None,
        url: None,
        extension: Some("ztar.z"),
        desc: "compressed file (often Tar (file format)tar zip) using Lempel-Ziv-Welch algorithm",
        popular: false,
    },
    FileSignature {
        sig_hex: "1FA0",
        iso: Some("1F A0"),
        url: None,
        extension: Some("ztar.z"),
        desc: "Compressed file (often tar zip) using LHA (file format)LZH algorithm",
        popular: false,
    },
    FileSignature {
        sig_hex: "4241434B4D494B454449534B",
        iso: Some("BACKMIKE DISK"),
        url: None,
        extension: Some("bac"),
        desc: "File or Magnetic tape data storagetape containing a backup done with AmiBack on an Amiga. It typically is paired with an index file (idx) with the table of contents.",
        popular: false,
    },
    FileSignature {
        sig_hex: "425A68",
        iso: Some("BZh"),
        url: None,
        extension: Some("bz2"),
        desc: "Compressed file using Bzip2 algorithm",
        popular: false,
    },
    FileSignature {
        sig_hex: "474946383761474946383961",
        iso: Some("GIF87a GIF89a"),
        url: None,
        extension: Some("gif"),
        desc: "Image file encoded in the Graphics Interchange Format (GIF)[http://www.w3.org/Graphics/GIF/spec-gif89a.txt GRAPHICS INTERCHANGE FORMAT(sm) Version 89a]",
        popular: false,
    },
    FileSignature {
        sig_hex: "49492A00(Endianness#Little-endianlittle-endianformat)4D4D002A(Endianness#Big-endianbig-endianformat)",
        iso: Some("II*. MM.*"),
        url: None,
        extension: Some("tiftiff"),
        desc: "Tagged Image File Format (TIFF)",
        popular: false,
    },
    FileSignature {
        sig_hex: "49492A00100000004352",
        iso: Some("II*..... CR"),
        url: Some("http://filext.com/file-extension/CR2"),
        extension: Some("cr2"),
        desc: "Canon RAW Format Version 2 weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "802A5FD7",
        iso: Some(".*_."),
        url: None,
        extension: Some("cin"),
        desc: "Eastman KodakKodak Cineon#Cineon file formatCineon image",
        popular: false,
    },
    FileSignature {
        sig_hex: "524E4301524E4302",
        iso: Some("RNC."),
        url: None,
        extension: None,
        desc: "Compressed file using [http://segaretro.org/Rob_Northen_compression Rob Northen Compression] (version 1 and 2) algorithm",
        popular: false,
    },
    FileSignature {
        sig_hex: "53445058(Endianness#Big-endianbig-endianformat)58504453(Endianness#Little-endianlittle-endianformat)",
        iso: Some("SDPX XPDS"),
        url: None,
        extension: Some("dpx"),
        desc: "SMPTE Digital Picture ExchangeDPX image",
        popular: false,
    },
    FileSignature {
        sig_hex: "762F3101",
        iso: Some("v/1."),
        url: None,
        extension: Some("exr"),
        desc: "OpenEXROpenEXR image",
        popular: false,
    },
    FileSignature {
        sig_hex: "425047FB",
        iso: Some("BPGû"),
        url: Some("http://bellard.org/bpg/ "),
        extension: Some("bpg"),
        desc: "Better Portable Graphics format",
        popular: false,
    },
    FileSignature {
        sig_hex: "FFD8FFDBFFD8FFE000104A4649460001FFD8FFEEFFD8FFE1????457869660000",
        iso: Some("ÿØÿÛ ÿØÿà..JFIF.. ÿØÿî ÿØÿá..Exif.."),
        url: None,
        extension: Some("jpgjpeg"),
        desc: "JPEG raw or in the JFIF or Exif file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????494C424D",
        iso: Some("FORM.... ILBM"),
        url: None,
        extension: Some("ilbmlbmibmiff"),
        desc: "Interchange File FormatIFF ILBMInterleaved Bitmap Image",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????38535658",
        iso: Some("FORM.... 8SVX"),
        url: None,
        extension: Some("8svx8svsvxsndiff"),
        desc: "Interchange File FormatIFF 8SVX8-Bit Sampled Voice",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????4143424D",
        iso: Some("FORM.... ACBM"),
        url: None,
        extension: Some("acbmiff"),
        desc: "Amiga Contiguous Bitmap",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????414E424D",
        iso: Some("FORM.... ANBM"),
        url: None,
        extension: Some("anbmiff"),
        desc: "Interchange File FormatIFF IFF Animated BitmapAnimated Bitmap",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????414E494D",
        iso: Some("FORM.... ANIM"),
        url: None,
        extension: Some("animiff"),
        desc: "Interchange File FormatIFF IFF CEL AnimationCEL Animation",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????46415858",
        iso: Some("FORM.... FAXX"),
        url: None,
        extension: Some("faxxfaxiff"),
        desc: "Interchange File FormatIFF FaxFacsimile Image",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????46545854",
        iso: Some("FORM.... FTXT"),
        url: None,
        extension: Some("ftxtiff"),
        desc: "Interchange File FormatIFF Formatted textFormatted Text",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????534D5553",
        iso: Some("FORM.... SMUS"),
        url: None,
        extension: Some("smussmumusiff"),
        desc: "Interchange File FormatIFF IFF Simple Musical ScoreSimple Musical Score",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????434D5553",
        iso: Some("FORM.... CMUS"),
        url: None,
        extension: Some("cmusmusiff"),
        desc: "Interchange File FormatIFF IFF Musical ScoreMusical Score",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????5955564E",
        iso: Some("FORM.... YUVN"),
        url: None,
        extension: Some("yuvnyuviff"),
        desc: "Interchange File FormatIFF YUVYUV Image",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????46414E54",
        iso: Some("FORM.... FANT"),
        url: None,
        extension: Some("iff"),
        desc: "Amiga FantavisionFantavision Movie",
        popular: false,
    },
    FileSignature {
        sig_hex: "464F524D????????41494646",
        iso: Some("FORM.... AIFF"),
        url: None,
        extension: Some("aiffaifaifcsndiff"),
        desc: "Audio Interchange File Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "494E4458",
        iso: Some("INDX"),
        url: None,
        extension: Some("idx"),
        desc: "Index file to a file or Magnetic tape data storagetape containing a backup done with AmiBack on an Amiga.",
        popular: false,
    },
    FileSignature {
        sig_hex: "4C5A4950",
        iso: Some("LZIP"),
        url: None,
        extension: Some("lz"),
        desc: "lzip compressed file",
        popular: false,
    },
    FileSignature {
        sig_hex: "4D5A",
        iso: None,
        url: None,
        extension: Some("exedll"),
        desc: "DOS MZ executable file format and its descendants (including New ExecutableNE and Portable ExecutablePE)",
        popular: false,
    },
    FileSignature {
        sig_hex: "504B0304504B0506(emptyarchive)504B0708(spannedarchive)",
        iso: Some("PK.."),
        url: None,
        extension: Some("zipaarapkdocxepub.ipaipajarkmzMozilla Archive Formatmaffodpodsodtpk3pk4pptxusdzvsdxxlsxXPInstallxpi"),
        desc: "ZIP (file format)zip file format and formats based on it, such as EPUB, JAR (file format)JAR, OpenDocumentODF, Office Open XMLOOXML",
        popular: false,
    },
    FileSignature {
        sig_hex: "526172211A0700",
        iso: Some("Rar!..."),
        url: None,
        extension: Some("rar"),
        desc: "RAR (file format)RAR archive version 1.50 onwards web title=TechNote.txt: RAR version 4.00 - Technical information date=2010-12-01 quote=The marker block is actually considered as a fixed byte sequence: 0x52 0x61 0x72 0x21 0x1a 0x07 0x00",
        popular: false,
    },
    FileSignature {
        sig_hex: "526172211A070100",
        iso: Some("Rar!...."),
        url: Some("http://www.rarlab.com/technote.htm "),
        extension: Some("rar"),
        desc: "RAR (file format)RAR archive version 5.0 onwards",
        popular: false,
    },
    FileSignature {
        sig_hex: "5A4D",
        iso: None,
        url: None,
        extension: Some("exe"),
        desc: "DOS ZM executable file format and its descendants (rare)",
        popular: false,
    },
    FileSignature {
        sig_hex: "7F454C46",
        iso: Some(".ELF"),
        url: None,
        extension: None,
        desc: "Executable and Linkable Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "89504E470D0A1A0A",
        iso: Some(".PNG...."),
        url: Some("http://tools.ietf.org/html/rfc2083"),
        extension: Some("png"),
        desc: "Image encoded in the Portable Network Graphics format weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "C9",
        iso: None,
        url: None,
        extension: Some("com"),
        desc: "COM file (CP/M)CP/M 3 and higher with overlays",
        popular: false,
    },
    FileSignature {
        sig_hex: "CAFEBABE",
        iso: Some("Êþº¾"),
        url: None,
        extension: Some("class"),
        desc: "Java class file, Fat binary#AppleMach-O Fat Binary",
        popular: false,
    },
    FileSignature {
        sig_hex: "EFBBBF",
        iso: Some("ï»¿"),
        url: None,
        extension: None,
        desc: "UTF-8 encoded Unicode byte order mark, commonly seen in text files.",
        popular: false,
    },
    FileSignature {
        sig_hex: "FEEDFACE",
        iso: None,
        url: None,
        extension: None,
        desc: "Mach-O binary (32-bit)",
        popular: false,
    },
    FileSignature {
        sig_hex: "FEEDFACF",
        iso: None,
        url: None,
        extension: None,
        desc: "Mach-O binary (64-bit)",
        popular: false,
    },
    FileSignature {
        sig_hex: "FEEDFEED",
        iso: None,
        url: None,
        extension: None,
        desc: "JKS [http://hg.openjdk.java.net/jdk10/jdk10/jdk/file/777356696811/src/java.base/share/classes/sun/security/provider/JavaKeyStore.java JavakeyStore]",
        popular: false,
    },
    FileSignature {
        sig_hex: "CEFAEDFE",
        iso: None,
        url: Some("\"apple.com\">{{cite web"),
        extension: None,
        desc: "Mach-O binary (reverse byte ordering scheme, 32-bit)ref name",
        popular: false,
    },
    FileSignature {
        sig_hex: "CFFAEDFE",
        iso: None,
        url: None,
        extension: None,
        desc: "Mach-O binary (reverse byte ordering scheme, 64-bit)",
        popular: false,
    },
    FileSignature {
        sig_hex: "FFFE",
        iso: None,
        url: None,
        extension: None,
        desc: "Byte-order mark for text file encoded in Endianness#Little-endianlittle-endian UTF-1616-bit Unicode Transfer Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "FFFE0000",
        iso: None,
        url: None,
        extension: None,
        desc: "Byte-order mark for text file encoded in little-endian UTF-3232-bit Unicode Transfer Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "25215053",
        iso: Some("%!PS"),
        url: None,
        extension: Some("ps"),
        desc: "PostScriptPostScript document",
        popular: false,
    },
    FileSignature {
        sig_hex: "495453460300000060000000",
        iso: Some("ITSF....`..."),
        url: None,
        extension: Some("chm"),
        desc: "Microsoft_Compiled_HTML_HelpMS Windows HtmlHelp Data",
        popular: false,
    },
    FileSignature {
        sig_hex: "255044462d",
        iso: Some("%PDF-"),
        url: Some("https://github.com/file/file/blob/master/magic/Magdir/pdf"),
        extension: Some("pdf"),
        desc: "Portable Document FormatPDF document",
        popular: false,
    },
    FileSignature {
        sig_hex: "3026B2758E66CF11A6D900AA0062CE6C",
        iso: Some("0&²u.fÏ .¦Ù.ª.bÎl"),
        url: Some("http://www.digitalpreservation.gov/formats/fdd/fdd000067.shtml "),
        extension: Some("asfwmawmv"),
        desc: "Advanced Systems Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "2453444930303031",
        iso: Some("$SDI0001"),
        url: None,
        extension: None,
        desc: "System Deployment Image, a disk image format used by Microsoft",
        popular: false,
    },
    FileSignature {
        sig_hex: "4F676753",
        iso: Some("OggS"),
        url: None,
        extension: Some("oggogaogv"),
        desc: "Ogg, an Open-source licenseopen source media container format",
        popular: false,
    },
    FileSignature {
        sig_hex: "38425053",
        iso: Some("8BPS"),
        url: None,
        extension: Some("psd"),
        desc: "Photoshop Document file, Adobe Photoshop's native file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "52494646????????57415645",
        iso: Some("RIFF.... WAVE"),
        url: None,
        extension: Some("wav"),
        desc: "Waveform Audio File Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "52494646????????41564920",
        iso: Some("RIFF.... AVI."),
        url: None,
        extension: Some("avi"),
        desc: "Audio Video Interleave video format",
        popular: false,
    },
    FileSignature {
        sig_hex: "FFFBFFF3FFF2",
        iso: Some("ÿû ÿó ÿò"),
        url: None,
        extension: Some("mp3"),
        desc: "MPEG-1 Layer 3 file without an ID3 tag or with an ID3v1 tag (which's appended at the end of the file)",
        popular: false,
    },
    FileSignature {
        sig_hex: "494433",
        iso: Some("ID3"),
        url: None,
        extension: Some("mp3"),
        desc: "MP3 file with an ID3v2 container",
        popular: false,
    },
    FileSignature {
        sig_hex: "424D",
        iso: None,
        url: None,
        extension: Some("bmpdib"),
        desc: "BMP file formatBMP file, a bitmap format used mostly in the Windows world",
        popular: false,
    },
    FileSignature {
        sig_hex: "4344303031",
        iso: Some("CD001"),
        url: Some("http://www.garykessler.net/library/file_sigs.html"),
        extension: Some("iso"),
        desc: "ISO9660 CD/DVD image file weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "53494D504C4520203D202020202020202020202020202020202020202054",
        iso: Some("SIMPLE   =                      T"),
        url: Some("http://www.digitalpreservation.gov/formats/fdd/fdd000317.shtml#sign"),
        extension: Some("fits"),
        desc: "Flexible Image Transport System (FITS) weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "664C6143",
        iso: Some("fLaC"),
        url: Some("http://flac.sourceforge.net/format.html#stream "),
        extension: Some("flac"),
        desc: "Free Lossless Audio Codec weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "4D546864",
        iso: Some("MThd"),
        url: Some("http://filesignatures.net/index.php?search"),
        extension: Some("midmidi"),
        desc: "MIDI#Standard MIDI filesMIDI sound file weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "D0CF11E0A1B11AE1",
        iso: None,
        url: Some("http://social.msdn.microsoft.com/Forums/en-US/343d09e3-5fdf-4b4a-9fa6-8ccb37a35930/developing-a-tool-to-recognise-ms-office-file-types-doc-xls-mdb-ppt-?forum"),
        extension: Some("docxlspptmsg"),
        desc: "Compound File Binary Format, a container format used for document by older versions of Microsoft Office. weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "6465780A30333500",
        iso: Some("dex.035."),
        url: None,
        extension: Some("dex"),
        desc: "Dalvik (software)Dalvik Executable",
        popular: false,
    },
    FileSignature {
        sig_hex: "4B444D",
        iso: Some("KDM"),
        url: Some("https://www.vmware.com/support/ws55/doc/ws_learning_files_in_a_vm.html"),
        extension: Some("vmdk"),
        desc: "VMDK files weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "43723234",
        iso: Some("Cr24"),
        url: Some("http://developer.chrome.com/extensions/crx.html"),
        extension: Some("crx"),
        desc: "Google Chrome extension weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "41474433",
        iso: Some("AGD3"),
        url: Some("https://mail.python.org/pipermail/pythonmac-sig/2005-February/013028.html"),
        extension: Some("fh8"),
        desc: "Adobe FreeHandFreeHand 8 document weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "05070000424F424F0507000000000000000000000001",
        iso: Some("....BOBO ........ ...."),
        url: None,
        extension: Some("cwk"),
        desc: "AppleWorks 5 document",
        popular: false,
    },
    FileSignature {
        sig_hex: "0607E100424F424F0607E10000000000000000000001",
        iso: Some("....BOBO ........ ...."),
        url: None,
        extension: Some("cwk"),
        desc: "AppleWorks 6 document",
        popular: false,
    },
    FileSignature {
        sig_hex: "4552020000008B455202000000",
        iso: Some("ER.... ãER...."),
        url: None,
        extension: Some("toast"),
        desc: "Roxio Roxio ToastToast disc image file, also some .dmg-files begin with same bytes",
        popular: false,
    },
    FileSignature {
        sig_hex: "7801730D626260",
        iso: Some("x.s.bb`"),
        url: None,
        extension: Some("dmg"),
        desc: "Apple Disk Image file",
        popular: false,
    },
    FileSignature {
        sig_hex: "78617221",
        iso: Some("xar!"),
        url: Some("https://code.google.com/p/xar/wiki/xarformat"),
        extension: Some("xar"),
        desc: "Xar (archiver)eXtensible ARchive format weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "504D4F43434D4F43",
        iso: Some("PMOCCMOC"),
        url: Some("http://www.howtogeek.com/79820/easily-restore-your-computer-with-file-and-settings-transfer-wizard-xp-part-1/"),
        extension: Some("dat"),
        desc: "Windows Files And Settings Transfer Repository weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "4E45531A",
        iso: Some("NES"),
        url: Some("http://sadistech.com/nesromtool/romdoc.html"),
        extension: Some("nes"),
        desc: "Nintendo Entertainment System ROM file weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "75737461720030307573746172202000",
        iso: Some("ustar.00 ustar  ."),
        url: Some("https://www.gnu.org/software/tar/manual/html_node/Standard.html"),
        extension: Some("tar"),
        desc: "tar (computing)tar archive weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "4F4152??",
        iso: Some("OAR."),
        url: None,
        extension: Some("oar"),
        desc: "OAR file archive format, where ?? is the format version.",
        popular: false,
    },
    FileSignature {
        sig_hex: "746F7833",
        iso: Some("TOX"),
        url: Some("http://tox.land/uvox/man.html"),
        extension: Some("tox"),
        desc: "Open source portable voxel file weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "4D4C5649",
        iso: Some("MLVI"),
        url: Some("https://docs.google.com/spreadsheet/ccc?key"),
        extension: Some("MLV"),
        desc: "Magic Lantern (firmware)Magic Lantern Video file weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "44434D0150413330",
        iso: Some("DCM PA30"),
        url: Some("1562 Binary Delta Compression]<ref>{{Cite web"),
        extension: None,
        desc: "Windows Update [http://www.microsoft.com/en-us/download/details.aspx?id",
        popular: false,
    },
    FileSignature {
        sig_hex: "377ABCAF271C",
        iso: Some("7z¼¯'"),
        url: None,
        extension: Some("7z"),
        desc: "7-Zip File Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "1F8B",
        iso: None,
        url: Some("https://tools.ietf.org/html/rfc1952#page-6"),
        extension: Some("gztar.gz"),
        desc: "GZIP compressed fileCite weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "FD377A585A00",
        iso: Some("²7zXZ.."),
        url: None,
        extension: Some("xztar.xz"),
        desc: "XZ UtilsXZ compression utility using Lempel–Ziv–Markov chain algorithmLZMA2 compression",
        popular: false,
    },
    FileSignature {
        sig_hex: "04224D18",
        iso: Some(".\"M."),
        url: Some("https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md"),
        extension: Some("lz4"),
        desc: "LZ4 (compression algorithm)LZ4 Frame Format weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "4D534346",
        iso: Some("MSCF"),
        url: None,
        extension: Some("cab"),
        desc: "Microsoft Cabinet file",
        popular: false,
    },
    FileSignature {
        sig_hex: "535A444488F02733",
        iso: Some("SZDD...."),
        url: None,
        extension: Some("Various. (Replacing the last character of the original filename extension with an underscore, e.g. setup.exe becomes setup.ex_)"),
        desc: "Microsoft compressed file in Quantum compressionQuantum format, used prior to Windows XP.  File can be decompressed using Extract.exe or Expand.exe distributed with earlier versions of Windows.",
        popular: false,
    },
    FileSignature {
        sig_hex: "464C4946",
        iso: Some("FLIF"),
        url: None,
        extension: Some("flif"),
        desc: "Free Lossless Image Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "1A45DFA3",
        iso: Some(".Eß£"),
        url: None,
        extension: Some("mkvmkamksmk3dwebm"),
        desc: "Matroska media container, including WebM",
        popular: false,
    },
    FileSignature {
        sig_hex: "4D494C20",
        iso: Some("MIL"),
        url: None,
        extension: Some("stg"),
        desc: "\"SEAN : Session Analysis\" Training file. Also used in compatible software \"Rpw : Rowperfect for Windows\" and \"RP3W : ROWPERFECT3 for Windows\".",
        popular: false,
    },
    FileSignature {
        sig_hex: "41542654464F524D????????444A56",
        iso: Some("AT&TFORM....DJV"),
        url: None,
        extension: Some("djvudjv"),
        desc: "DjVu documentThe following byte is either 55 (U) for single-page or 4D (M) for multi-page documents.",
        popular: false,
    },
    FileSignature {
        sig_hex: "3082",
        iso: None,
        url: None,
        extension: Some("der"),
        desc: "DER encoded X.509 certificate",
        popular: false,
    },
    FileSignature {
        sig_hex: "4449434D",
        iso: Some("DICM"),
        url: None,
        extension: Some("dcm"),
        desc: "DICOMDICOM Medical File Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "774F4646",
        iso: Some("wOFF"),
        url: None,
        extension: Some("woff"),
        desc: "[https://www.w3.org/TR/2012/REC-WOFF-20121213/ WOFF File Format 1.0]",
        popular: false,
    },
    FileSignature {
        sig_hex: "774F4632",
        iso: Some("wOF2"),
        url: None,
        extension: Some("woff2"),
        desc: "[https://www.w3.org/TR/WOFF2/ WOFF File Format 2.0]",
        popular: false,
    },
    FileSignature {
        sig_hex: "3c3f786d6c20",
        iso: Some("?xml"),
        url: None,
        extension: Some("XML"),
        desc: "XMLeXtensible Markup Language when using the ASCII character encoding",
        popular: false,
    },
    FileSignature {
        sig_hex: "0061736d",
        iso: Some(".asm"),
        url: Some("https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#high-level-structure"),
        extension: Some("wasm"),
        desc: "WebAssembly binary formatCite weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "cf8401",
        iso: None,
        url: Some("https://blogs.dropbox.com/tech/2016/07/lepton-image-compression-saving-22-losslessly-from-images-at-15mbs/"),
        extension: Some("lep"),
        desc: "Lepton image compression formatLepton compressed JPEG imageCite weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "435753465753",
        iso: Some("CWS FWS"),
        url: None,
        extension: Some("swf"),
        desc: "flash .swf",
        popular: false,
    },
    FileSignature {
        sig_hex: "213C617263683E",
        iso: None,
        url: None,
        extension: Some("deb"),
        desc: "linux deb file",
        popular: false,
    },
    FileSignature {
        sig_hex: "52494646????????57454250",
        iso: Some("RIFF.... WEBP"),
        url: None,
        extension: Some("webp"),
        desc: "Google WebP image file, where ?? ?? ?? ?? is the file size. More information on [https://developers.google.com/speed/webp/docs/riff_container#webp_file_header WebP File Header]",
        popular: false,
    },
    FileSignature {
        sig_hex: "27051956",
        iso: Some("'..V"),
        url: Some("http://buffalo.nas-central.org/wiki/How_to_Extract_an_uImage"),
        extension: None,
        desc: "U-Boot / uImage. Das U-Boot Universal Boot Loader.Cite weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "7B5C72746631",
        iso: Some("\\rtf1"),
        url: None,
        extension: Some("rtf"),
        desc: "Rich Text Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "54415045",
        iso: Some("TAPE"),
        url: None,
        extension: None,
        desc: "Microsoft Tape Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "47",
        iso: None,
        url: None,
        extension: Some("ts tsv  tsa"),
        desc: "MPEG Transport Stream  (MPEG-2 Part 1)",
        popular: false,
    },
    FileSignature {
        sig_hex: "000001BA",
        iso: None,
        url: None,
        extension: Some("m2p  vob"),
        desc: "MPEG Program Stream  (MPEG-1 Part 1 (essentially identical) and MPEG-2 Part 1)",
        popular: false,
    },
    FileSignature {
        sig_hex: "000001BA47000001B3",
        iso: None,
        url: None,
        extension: Some("mpg mpeg"),
        desc: "MPEG Program Stream  MPEG Transport Stream  MPEG-1 video and MPEG-2 video  (MPEG-1 Part 2 and MPEG-2 Part 2)",
        popular: false,
    },
    FileSignature {
        sig_hex: "000000186674797069736F6D",
        iso: Some("ftypisom"),
        url: None,
        extension: Some("mp4"),
        desc: "ISO Base Media file (MPEG-4)",
        popular: false,
    },
    FileSignature {
        sig_hex: "7801785E789C78DA7820787D78BB78F9",
        iso: None,
        url: None,
        extension: Some("zlib"),
        desc: "No Compression (no preset dictionary)  Best speed (no preset dictionary)  Default Compression (no preset dictionary)  Best Compression (no preset dictionary)  No Compression (with preset dictionary)  Best speed (with preset dictionary)  Default Compression (with preset dictionary)  Best Compression (with preset dictionary)",
        popular: false,
    },
    FileSignature {
        sig_hex: "62767832",
        iso: Some("bvx2"),
        url: Some("https://github.com/lzfse/lzfse"),
        extension: Some("lzfse"),
        desc: "LZFSE - Lempel-Ziv style data compression algorithm using Finite State Entropy coding. OSS by Apple.Cite weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "4F5243",
        iso: Some("ORC"),
        url: None,
        extension: Some("orc"),
        desc: "Apache ORC (Optimized Row Columnar) file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "4F626A01",
        iso: Some("Obj."),
        url: None,
        extension: Some("avro"),
        desc: "Apache Avro binary file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "53455136",
        iso: Some("SEQ6"),
        url: None,
        extension: Some("rc"),
        desc: "RCFile columnar file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "65877856",
        iso: Some("e.xV"),
        url: None,
        extension: Some("p25  obt"),
        desc: "PhotoCap Object Templates",
        popular: false,
    },
    FileSignature {
        sig_hex: "5555aaaa",
        iso: None,
        url: None,
        extension: Some("pcv"),
        desc: "PhotoCap Vector",
        popular: false,
    },
    FileSignature {
        sig_hex: "785634",
        iso: Some("xV4"),
        url: None,
        extension: Some("pbt  pdt  pea  peb  pet  pgt  pict  pjt  pkt  pmt"),
        desc: "PhotoCap Template",
        popular: false,
    },
    FileSignature {
        sig_hex: "50415231",
        iso: Some("PAR1"),
        url: None,
        extension: None,
        desc: "Apache Parquet columnar file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "454D5832",
        iso: Some("EMX2"),
        url: None,
        extension: Some("ez2"),
        desc: "E-mu_EmaxEmulator Emaxsynth samples",
        popular: false,
    },
    FileSignature {
        sig_hex: "454D5533",
        iso: Some("EMU3"),
        url: None,
        extension: Some("ez3 iso"),
        desc: "E-mu_Emulator#The_Emulator_IIIEmulator III synth samples",
        popular: false,
    },
    FileSignature {
        sig_hex: "1B4C7561",
        iso: Some(".Lua"),
        url: Some("Lua 5.2 Bytecode and Virtual Machine "),
        extension: Some("luac"),
        desc: "Lua (programming language)Lua bytecode web title",
        popular: false,
    },
    FileSignature {
        sig_hex: "626F6F6B000000006D61726B00000000",
        iso: Some("62 6F 6F 6B 00 00 00 00 6D 61 72 6B 00 00 00 00"),
        url: Some("https://www.forensicswiki.org/wiki/Mac_OS_X#Burn_Folder"),
        extension: Some("alias"),
        desc: "macOS file AliasCite weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "5B5A6F6E655472616E736665725D",
        iso: Some("[ZoneTransfer]"),
        url: Some("vs.60) URL Security Zones]<ref>{{Cite web"),
        extension: Some("Identifier"),
        desc: "Microsoft Zone Identifier for [https://technet.microsoft.com/en-us/windows/ms537183(v",
        popular: false,
    },
    FileSignature {
        sig_hex: "5265636569766564",
        iso: Some("Received:"),
        url: Some("http://file-extension.net/seeker/program_extension_message"),
        extension: Some("eml"),
        desc: "Email Message var5Cite weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "20020162A01EAB0702000000",
        iso: Some("20 02 01 62 A0 1E AB 07 02 00 00 00"),
        url: None,
        extension: Some("tde"),
        desc: "Tableau Datasource",
        popular: false,
    },
    FileSignature {
        sig_hex: "3748030200000000583530394B4559",
        iso: Some("37 48 03 02 00 00 00 00 58 35 30 39 4B 45 59"),
        url: None,
        extension: Some("kdb"),
        desc: "KDB file",
        popular: false,
    },
    FileSignature {
        sig_hex: "85????03",
        iso: Some("85 ?? ?? 03"),
        url: Some("https://security.stackexchange.com/a/144555/12109"),
        extension: Some("pgp"),
        desc: "PGP file Cite weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "28B52FFD",
        iso: Some("28 B5 2F FD"),
        url: Some("https://tools.ietf.org/html/rfc8478#section-3.1.1"),
        extension: Some("zst"),
        desc: "Zstandard compressed fileCite weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "5253564B44415441",
        iso: Some("52 53 56 4B 44 41 54 41"),
        url: Some("https://filext.com/file-extension/RS"),
        extension: Some("rs"),
        desc: "QuickZip rs compressed archiveCite weburl",
        popular: false,
    },
    FileSignature {
        sig_hex: "3A290A",
        iso: Some("3A 29 0A"),
        url: None,
        extension: Some("sml"),
        desc: "Smile (data interchange format)Smile file",
        popular: false,
    },
    FileSignature {
        sig_hex: "4A6F7921",
        iso: Some("4A 6F 79 21"),
        url: None,
        extension: None,
        desc: "Preferred Executable Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "310A3030",
        iso: Some("31 0A 30 30"),
        url: None,
        extension: Some("srt"),
        desc: "SubRip File",
        popular: false,
    },
    FileSignature {
        sig_hex: "3412AA55",
        iso: Some("34 12 AA 55"),
        url: None,
        extension: Some("vpk"),
        desc: "VPK file, used to store game data for some Source Engine games",
        popular: false,
    },
    FileSignature {
        sig_hex: "58464952",
        iso: Some("58 46 49 52"),
        url: None,
        extension: Some("dcr"),
        desc: "Adobe Shockwave",
        popular: false,
    },
    FileSignature {
        sig_hex: "2A2A4143452A3A",
        iso: Some("2A 2A 41 43 45 2A 2A"),
        url: None,
        extension: Some("ace"),
        desc: "ACE (compressed file format)",
        popular: false,
    },
    FileSignature {
        sig_hex: "60EA",
        iso: Some("60 RA"),
        url: None,
        extension: Some("arj"),
        desc: "ARJ",
        popular: false,
    },
    FileSignature {
        sig_hex: "49536328",
        iso: Some("49 53 63 28"),
        url: None,
        extension: Some("cab"),
        desc: "InstallShield CAB Archive File",
        popular: false,
    },
    FileSignature {
        sig_hex: "4B57414A",
        iso: Some("4B 57 41 4A"),
        url: None,
        extension: Some("??_"),
        desc: "Windows 3.1x Compressed File",
        popular: false,
    },
    FileSignature {
        sig_hex: "535A4444",
        iso: Some("53 5A 44 44"),
        url: None,
        extension: Some("??_"),
        desc: "Windows 9x Compressed File",
        popular: false,
    },
    FileSignature {
        sig_hex: "5A4F4F",
        iso: Some("5A 4F 4F"),
        url: None,
        extension: Some("zoo"),
        desc: "Zoo (file format)",
        popular: false,
    },
    FileSignature {
        sig_hex: "50310A",
        iso: Some("50 31 0A"),
        url: None,
        extension: Some("pbm"),
        desc: "Portable bitmap",
        popular: false,
    },
    FileSignature {
        sig_hex: "50320A",
        iso: Some("50 32 0A"),
        url: None,
        extension: Some("pgm"),
        desc: "Portable Gray Map",
        popular: false,
    },
    FileSignature {
        sig_hex: "50330A",
        iso: Some("50 33 0A"),
        url: None,
        extension: Some("ppm"),
        desc: "Portable Pixmap",
        popular: false,
    },
    FileSignature {
        sig_hex: "D7CDC69A",
        iso: Some("D7 CD C6 9A"),
        url: None,
        extension: Some("wmf"),
        desc: "Windows Metafile",
        popular: false,
    },
    FileSignature {
        sig_hex: "67696D7020786366",
        iso: Some("67 69 6D 70 20 78 63 66"),
        url: None,
        extension: Some("xcf"),
        desc: "XCF (file format)",
        popular: false,
    },
    FileSignature {
        sig_hex: "2F2A2058504D202A2F",
        iso: Some("2F 2A 20 58 50 4D 20 2A 2F"),
        url: None,
        extension: Some("xpm"),
        desc: "X PixMap",
        popular: false,
    },
    FileSignature {
        sig_hex: "414646",
        iso: Some("41 46 46"),
        url: None,
        extension: Some("aff"),
        desc: "Advanced Forensics Format",
        popular: false,
    },
    FileSignature {
        sig_hex: "45564632",
        iso: Some("45 56 46 32"),
        url: None,
        extension: Some("Ex01"),
        desc: "EnCase EWF version 2 format",
        popular: false,
    },
    FileSignature {
        sig_hex: "455646",
        iso: Some("45 56 46"),
        url: None,
        extension: Some("e01"),
        desc: "EnCase EWF version 1 format",
        popular: false,
    },
    FileSignature {
        sig_hex: "514649",
        iso: Some("51 46 49"),
        url: None,
        extension: Some("qcow"),
        desc: "qcow file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "52494646????????41434F4E",
        iso: Some("RIFF.... ACON"),
        url: None,
        extension: Some("ani"),
        desc: "Animated cursor",
        popular: false,
    },
    FileSignature {
        sig_hex: "52494646????????43444441",
        iso: Some("RIFF.... CDDA"),
        url: None,
        extension: Some("cda"),
        desc: "Compact Disc Digital Audio",
        popular: false,
    },
    FileSignature {
        sig_hex: "52494646????????514C434D",
        iso: Some("RIFF.... QLCM"),
        url: None,
        extension: Some("qcp"),
        desc: "Qualcomm PureVoice file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "58464952????????3339564D",
        iso: Some("XFIR.... 39VM"),
        url: None,
        extension: Some("dir"),
        desc: "Macromedia Director file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "464C56",
        iso: Some("46 4C 56"),
        url: None,
        extension: Some("flv"),
        desc: "Flash Video file",
        popular: false,
    },
    FileSignature {
        sig_hex: "3C3C3C204F7261636C6520564D205669727475616C426F78204469736B20496D616765203E3E3E",
        iso: Some("3C 3C 3C 20 4F 72 61 63 6C 65 20 56 4D 20 56 69 72 74 75 61 6C 42 6F 78 20 44 69 73 6B 20 49 6D 61 67 65 20 3E 3E 3E"),
        url: None,
        extension: Some("vdi"),
        desc: "VirtualBox Virtual Hard Disk file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "636F6E6E6563746978",
        iso: Some("63 6F 6E 6E 65 63 74 69 78"),
        url: None,
        extension: Some("vhd"),
        desc: "Windows Virtual PC Virtual Hard Disk file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "7668647866696C65",
        iso: Some("76 68 64 78 66 69 6C 65"),
        url: None,
        extension: Some("vhdx"),
        desc: "Windows Virtual PC Windows 8 Virtual Hard Disk file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "49735A21",
        iso: Some("49 73 5A 21"),
        url: None,
        extension: Some("isz"),
        desc: "Compressed ISO image",
        popular: false,
    },
    FileSignature {
        sig_hex: "444141",
        iso: Some("44 41 41"),
        url: None,
        extension: Some("daa"),
        desc: "Direct Access Archive PowerISO",
        popular: false,
    },
    FileSignature {
        sig_hex: "4C664C65",
        iso: Some("4C 66 4C 65"),
        url: None,
        extension: Some("evt"),
        desc: "Windows Event Viewer file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "504D4343",
        iso: Some("50 4D 43 43"),
        url: None,
        extension: Some("grp"),
        desc: "Windows 3.x Program Manager Program Group file format",
        popular: false,
    },
    FileSignature {
        sig_hex: "4B434D53",
        iso: Some("4B 43 4D 53"),
        url: None,
        extension: Some("icm"),
        desc: "ICC profile",
        popular: false,
    },
    FileSignature {
        sig_hex: "72656766",
        iso: Some("72 65 67 66"),
        url: None,
        extension: Some("dat"),
        desc: "Windows Registry file",
        popular: false,
    },
    FileSignature {
        sig_hex: "2142444E",
        iso: Some("21 42 44 4E"),
        url: None,
        extension: Some("pst"),
        desc: "Microsoft Outlook Personal Storage Table file",
        popular: false,
    },
    FileSignature {
        sig_hex: "445241434F",
        iso: Some("44 52 41 43 4F"),
        url: Some(""),
        extension: Some("drc"),
        desc: "3D model compressed with Google DracoCite weblast",
        popular: false,
    },
    FileSignature {
        sig_hex: "47524942",
        iso: Some("47 52 49 42"),
        url: None,
        extension: Some("grib grib2"),
        desc: "Gridded data (commonly weather observations or forecasts) in the World Meteorological OrganizationWMO GRIB or GRIB2 formathttps://www.wmo.int/pages/prog/www/WDM/Guides/Guide-binary-2.html",
        popular: false,
    },
    FileSignature {
        sig_hex: "424C454E444552",
        iso: Some("BLENDER"),
        url: Some("2015-04-18"),
        extension: Some("blend"),
        desc: "Blender File FormatCite webdate",
        popular: false,
    },
];

/// Identify a file by its hex signature prefix.
pub fn identify_file(hex_bytes: &str) -> Vec<&'static FileSignature> {
    let lower = hex_bytes.to_lowercase();
    FILE_SIGNATURES
        .iter()
        .filter(|sig| lower.starts_with(&sig.sig_hex.to_lowercase()))
        .collect()
}
