//! Mastercard BIN lookup — auto-generated from mastercard_companies.json

pub struct MastercardBin {
    pub bin: &'static str,
    pub company: &'static str,
}

static MASTERCARD_BINS: &[MastercardBin] = &[
    MastercardBin { bin: "510082", company: "COMMERCIAL BANK MASTER-BANK" },
    MastercardBin { bin: "510129", company: "DEUTSCHE BANK AG" },
    MastercardBin { bin: "510171", company: "ISTITUTO CENTRALE DELLE BANCHE DI CREDITO COOPERATIVO" },
    MastercardBin { bin: "510274", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "510278", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "510282", company: "BANCORP BANK" },
    MastercardBin { bin: "510291", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "510303", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "510321", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "510355", company: "COMPUTER SERVICES, INC." },
    MastercardBin { bin: "510360", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "510394", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "510498", company: "BANQUE MISR" },
    MastercardBin { bin: "510554", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "510556", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "510568", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "510573", company: "COMPUTER SERVICES, INC." },
    MastercardBin { bin: "510578", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "510579", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "510592", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "510606", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "510608", company: "SHAZAM, INC." },
    MastercardBin { bin: "510635", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "510637", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "510653", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "510656", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "510664", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "510686", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "510701", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "510729", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "510730", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "510755", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "510801", company: "BANK OF HAWAII" },
    MastercardBin { bin: "510804", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "510812", company: "H AND R BLOCK BANK" },
    MastercardBin { bin: "510814", company: "ING DIRECT" },
    MastercardBin { bin: "510827", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "510844", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "510859", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "510860", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "510864", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "510875", company: "LAKE MICHIGAN C.U." },
    MastercardBin { bin: "510880", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "510883", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "510926", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "510932", company: "ICUL SERVICE CORPORATION" },
    MastercardBin { bin: "510971", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "510999", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "511007", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "511032", company: "BANCORP BANK" },
    MastercardBin { bin: "511044", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "511058", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "511069", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "511074", company: "DATA CENTER INCORPORATED" },
    MastercardBin { bin: "511090", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "511130", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "511132", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "511144", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "511190", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "511194", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "511201", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "511202", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "511205", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "511209", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "511217", company: "BANCORP BANK" },
    MastercardBin { bin: "511250", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "511256", company: "BANK OF NEW YORK MELLON" },
    MastercardBin { bin: "511273", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "511289", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "511438", company: "FIRST COVENANT BANK" },
    MastercardBin { bin: "511443", company: "CHASE MANHATTAN BANK USA, N.A." },
    MastercardBin { bin: "511480", company: "KEYBANK, N.A." },
    MastercardBin { bin: "511481", company: "KEYBANK, N.A." },
    MastercardBin { bin: "511485", company: "REGIONS BANK" },
    MastercardBin { bin: "511597", company: "JPMORGAN CHASE BANK, N.A." },
    MastercardBin { bin: "511683", company: "HERITAGE INTERNATIONAL BANK AND TRUST, LTD." },
    MastercardBin { bin: "511804", company: "COMPUTER SERVICES, INC." },
    MastercardBin { bin: "511817", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "511858", company: "SCOTIABANK DE PUERTO RICO" },
    MastercardBin { bin: "511863", company: "BLOM BANK S.A.L." },
    MastercardBin { bin: "511901", company: "DATA CENTER INCORPORATED" },
    MastercardBin { bin: "511910", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "511932", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "511955", company: "COMPUTER SERVICES, INC." },
    MastercardBin { bin: "511969", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "511971", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "511977", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "511982", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "511983", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "511985", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "511995", company: "SANTA BARBARA BANK AND TRUST, N.A." },
    MastercardBin { bin: "512023", company: "INTERNATIONAL CARD CO., LTD." },
    MastercardBin { bin: "512067", company: "CITIBANK COLOMBIA, S.A." },
    MastercardBin { bin: "512259", company: "BANK OF NOVA SCOTIA" },
    MastercardBin { bin: "512387", company: "TIB - THE INDEPENDENT BANKERSBANK" },
    MastercardBin { bin: "512394", company: "OJSC BANK URALSIB" },
    MastercardBin { bin: "512411", company: "BANK OF CHINA, LTD." },
    MastercardBin { bin: "512431", company: "CHINA UNIONPAY CO., LTD." },
    MastercardBin { bin: "512432", company: "BANK ISLAM MALAYSIA BERHAD" },
    MastercardBin { bin: "512457", company: "BANCO SANTANDER PUERTO RICO" },
    MastercardBin { bin: "512465", company: "HSBC BANK BRASIL S.A. - BANCO MULTIPLO" },
    MastercardBin { bin: "512466", company: "CHINA MINSHENG BANKING CORP., LTD." },
    MastercardBin { bin: "512599", company: "INTESA SANPAOLO S.P.A." },
    MastercardBin { bin: "512714", company: "STANDARD CHARTERED BANK" },
    MastercardBin { bin: "512723", company: "BANCO DE COSTA RICA" },
    MastercardBin { bin: "512734", company: "HSBC BANK NEVADA, N.A." },
    MastercardBin { bin: "512750", company: "CARTASI S.P.A." },
    MastercardBin { bin: "512786", company: "DIRECTCASH BANK" },
    MastercardBin { bin: "512987", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "513027", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513039", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513059", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513065", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513106", company: "EUROPAY FRANCE SAS" },
    MastercardBin { bin: "513111", company: "EUROPAY FRANCE SAS" },
    MastercardBin { bin: "513119", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513130", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513142", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513161", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513181", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513208", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513221", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513258", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513262", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513269", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513281", company: "BANQUE FEDERATIVE DU CREDIT MUTUEL (BFCM)" },
    MastercardBin { bin: "513298", company: "BANQUE FEDERATIVE DU CREDIT MUTUEL (BFCM)" },
    MastercardBin { bin: "513301", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513309", company: "EUROPAY FRANCE SAS" },
    MastercardBin { bin: "513326", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513332", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513342", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513345", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513349", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513361", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513365", company: "BANQUE FEDERATIVE DU CREDIT MUTUEL (BFCM)" },
    MastercardBin { bin: "513381", company: "EUROPAY FRANCE SAS" },
    MastercardBin { bin: "513382", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513389", company: "EUROPAY FRANCE SAS" },
    MastercardBin { bin: "513391", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513395", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513398", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513405", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513407", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513409", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513494", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513495", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513498", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513527", company: "EUROPAY FRANCE SAS" },
    MastercardBin { bin: "513537", company: "EUROPAY FRANCE SAS" },
    MastercardBin { bin: "513544", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513547", company: "EUROPAY FRANCE SAS" },
    MastercardBin { bin: "513548", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513567", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513603", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513630", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513632", company: "BANQUE FEDERATIVE DU CREDIT MUTUEL (BFCM)" },
    MastercardBin { bin: "513654", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513686", company: "ZAGREBACKA BANKA BH D.D." },
    MastercardBin { bin: "513695", company: "SCOTIABANK EL SALVADOR, S.A." },
    MastercardBin { bin: "513704", company: "BANQUE FEDERATIVE DU CREDIT MUTUEL (BFCM)" },
    MastercardBin { bin: "513720", company: "BANQUE FEDERATIVE DU CREDIT MUTUEL (BFCM)" },
    MastercardBin { bin: "513745", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513765", company: "WIRECARD BANK AG" },
    MastercardBin { bin: "513784", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513790", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513792", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513814", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513824", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513832", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513845", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513847", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513848", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513876", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513881", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513905", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513914", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513945", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513949", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513972", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513973", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "513992", company: "MASTERCARD FRANCE S.A.S." },
    MastercardBin { bin: "514021", company: "BARCLAYS BANK DELAWARE" },
    MastercardBin { bin: "514026", company: "CONSORCIO CREDICARD, C.A." },
    MastercardBin { bin: "514101", company: "BANCO POPULAR NORTH AMERICA" },
    MastercardBin { bin: "514103", company: "BANCO POPULAR NORTH AMERICA" },
    MastercardBin { bin: "514104", company: "BANCO POPULAR NORTH AMERICA" },
    MastercardBin { bin: "514131", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "514133", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "514135", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "514180", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "514185", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "514206", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "514209", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "514233", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "514241", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "514243", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "514248", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "514274", company: "PULSE NETWORK LLC" },
    MastercardBin { bin: "514277", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "514286", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "514303", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "514307", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "514318", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "514327", company: "NYCE PAYMENTS NETWORK, LLC" },
    MastercardBin { bin: "514372", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "514389", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "514418", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "514451", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "514488", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "514515", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "514523", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "514524", company: "COMPUTER SERVICES, INC." },
    MastercardBin { bin: "514526", company: "SOUTHWEST BRIDGE CORPORATE F.C.U." },
    MastercardBin { bin: "514536", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "514544", company: "INTER NATIONAL BANK" },
    MastercardBin { bin: "514546", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "514604", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "514653", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "514674", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "514675", company: "NYCE PAYMENTS NETWORK, LLC" },
    MastercardBin { bin: "514678", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "514684", company: "LAKE MICHIGAN C.U." },
    MastercardBin { bin: "514715", company: "NYCE PAYMENTS NETWORK, LLC" },
    MastercardBin { bin: "514738", company: "SHANGHAI COMMERCIAL AND SAVINGS BANK, LTD." },
    MastercardBin { bin: "514755", company: "JPMORGAN CHASE BANK, N.A." },
    MastercardBin { bin: "514757", company: "ABSA BANK, LTD." },
    MastercardBin { bin: "514778", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "514781", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "514792", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "514793", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "514797", company: "JPMORGAN CHASE BANK, N.A." },
    MastercardBin { bin: "514811", company: "CARD SERVICES FOR CREDIT UNIONS, INC." },
    MastercardBin { bin: "514845", company: "US AIRWAYS DIVIDEND MILES" },
    MastercardBin { bin: "514849", company: "US AIRWAYS DIVIDEND MILES" },
    MastercardBin { bin: "514875", company: "YUANTA COMMERCIAL BANK CO., LTD." },
    MastercardBin { bin: "514896", company: "HONG LEONG BANK BERHAD" },
    MastercardBin { bin: "514897", company: "ITAU UNIBANCO, S.A." },
    MastercardBin { bin: "514900", company: "RANDOLPH BROOKS F.C.U." },
    MastercardBin { bin: "514954", company: "NUEVO BANCO DE ENTRE RIOS, S.A." },
    MastercardBin { bin: "514965", company: "LIBERTY BANK OF ARKANSAS" },
    MastercardBin { bin: "514967", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "514983", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "514984", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "514990", company: "COMPUTER SERVICES, INC." },
    MastercardBin { bin: "515013", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "515029", company: "COMPUTER SERVICES, INC." },
    MastercardBin { bin: "515043", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "515054", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "515090", company: "COMERICA BANK" },
    MastercardBin { bin: "515092", company: "METABANK" },
    MastercardBin { bin: "515101", company: "COMERICA BANK" },
    MastercardBin { bin: "515128", company: "FIRST PREMIER BANK - OBOPAY" },
    MastercardBin { bin: "515155", company: "FIRST PREMIER BANK - OBOPAY" },
    MastercardBin { bin: "515194", company: "ICBA BANCARD, INC." },
    MastercardBin { bin: "515206", company: "CU COOPERATIVE SYSTEMS, INC." },
    MastercardBin { bin: "515208", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "515234", company: "SHAZAM, INC." },
    MastercardBin { bin: "515248", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "515249", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "515262", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "515275", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "515287", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "515340", company: "SHAZAM, INC." },
    MastercardBin { bin: "515354", company: "ACHIEVA C.U." },
    MastercardBin { bin: "515365", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "515386", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "515607", company: "NORDEA BANK FINLAND PLC EESTI FILIAAL" },
    MastercardBin { bin: "515608", company: "PUBLIC JSC ''VSEUKRAINSKYI AKSIONERNYI BANK" },
    MastercardBin { bin: "515625", company: "HSBC BANK NEVADA, N.A." },
    MastercardBin { bin: "515628", company: "EASTERN FINANCIAL FLORIDA C.U." },
    MastercardBin { bin: "515649", company: "DEUTSCHER SPARKASSEN UND GIROVERBAND" },
    MastercardBin { bin: "515665", company: "BARCLAYS BANK DELAWARE" },
    MastercardBin { bin: "515667", company: "WING LUNG BANK, LTD." },
    MastercardBin { bin: "515703", company: "ALLIANCE BANK MALAYSIA BERHAD" },
    MastercardBin { bin: "515704", company: "HONG LEONG BANK BERHAD" },
    MastercardBin { bin: "515849", company: "ASYA KATILIM BANKASI, A.S." },
    MastercardBin { bin: "515884", company: "CITIBANK EUROPE PUBLIC LIMITED COMPANY" },
    MastercardBin { bin: "515918", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "515928", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "516001", company: "NORDEA BANK FINLAND PLC" },
    MastercardBin { bin: "516003", company: "SCOTIABANK PERU S.A.A." },
    MastercardBin { bin: "516007", company: "WIRECARD BANK AG" },
    MastercardBin { bin: "516022", company: "CITIBANK EUROPE PUBLIC LIMITED COMPANY" },
    MastercardBin { bin: "516023", company: "CITIBANK EUROPE PUBLIC LIMITED COMPANY" },
    MastercardBin { bin: "516328", company: "WESTPAC BANKING CORPORATION" },
    MastercardBin { bin: "516399", company: "PUBLIC JSC DELTA BANK" },
    MastercardBin { bin: "516401", company: "FIRST NATIONAL BANK TEXAS" },
    MastercardBin { bin: "516408", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "516449", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "516699", company: "BANCO INTERACCIONES, S.A." },
    MastercardBin { bin: "516701", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "516730", company: "SB HSBC BANK KAZAKHSTAN JSC" },
    MastercardBin { bin: "517025", company: "TELLER, A.S." },
    MastercardBin { bin: "517187", company: "EASTERN CARIBBEAN CO-OPERATIVE" },
    MastercardBin { bin: "517542", company: "TEACHERS C.U." },
    MastercardBin { bin: "517544", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "517653", company: "ICICI BANK, LTD." },
    MastercardBin { bin: "517667", company: "BANK ZENIT" },
    MastercardBin { bin: "517707", company: "VENEZOLANO DE CREDITO S.A. BANCO UNIVERS.A.L." },
    MastercardBin { bin: "517873", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "517879", company: "COMMERCIAL INTERNATIONAL BANK (EGYPT) S.A.E." },
    MastercardBin { bin: "517882", company: "NYCE PAYMENTS NETWORK, LLC" },
    MastercardBin { bin: "517894", company: "STANDARD BANK OF SOUTH AFRICA, LTD." },
    MastercardBin { bin: "517947", company: "TELLER, A.S." },
    MastercardBin { bin: "518120", company: "ICBA BANCARD, INC." },
    MastercardBin { bin: "518127", company: "PRESIDENTS CHOICE BANK" },
    MastercardBin { bin: "518300", company: "HOUSING AND DEVELOPMENT BANK" },
    MastercardBin { bin: "518305", company: "HONGKONG AND SHANGHAI BANKING CORP., LTD." },
    MastercardBin { bin: "518309", company: "ITAU UNIBANCO, S.A." },
    MastercardBin { bin: "518370", company: "BANCO DE CHILE" },
    MastercardBin { bin: "518395", company: "SCOTIABANK TRINIDAD AND TOBAGO, LTD." },
    MastercardBin { bin: "518400", company: "BANCO CITIBANK DE HONDURAS, S.A." },
    MastercardBin { bin: "518674", company: "SERVIRED, SOCIEDAD ESPANOLA DE MEDIOS DE PAGO, S.A." },
    MastercardBin { bin: "518675", company: "MBNA EUROPE BANK, LTD." },
    MastercardBin { bin: "518706", company: "NORDEA BANK FINLAND PLC" },
    MastercardBin { bin: "518729", company: "FIRST COMMERCIAL BANK" },
    MastercardBin { bin: "518788", company: "MDM BANK OJSC" },
    MastercardBin { bin: "518808", company: "PUBLIC JSC RAIFFEISEN BANK AVAL" },
    MastercardBin { bin: "518857", company: "FIRST GULF BANK PJSC" },
    MastercardBin { bin: "518864", company: "JSCB ROSBANK" },
    MastercardBin { bin: "518883", company: "CSCBANK S.A.L." },
    MastercardBin { bin: "518896", company: "KUVEYT TURK KATILIM BANKASI, A.S." },
    MastercardBin { bin: "518942", company: "HALLMARK TRUST, LTD." },
    MastercardBin { bin: "519091", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "519097", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "519229", company: "BANCO POPULAR DOMINICANO, C. POR A." },
    MastercardBin { bin: "519313", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "519342", company: "BANK OF MONTREAL" },
    MastercardBin { bin: "519409", company: "BANK OF MONTREAL" },
    MastercardBin { bin: "519433", company: "BANK OF MONTREAL" },
    MastercardBin { bin: "519434", company: "HSBC BANK CANADA" },
    MastercardBin { bin: "519467", company: "POWSZECHNA KASA OSZCZEDNOSCI BANK POLSKI SA (PKO BANK POLSKI" },
    MastercardBin { bin: "519471", company: "ALLIANCE BANK MALAYSIA BERHAD" },
    MastercardBin { bin: "519481", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "519509", company: "METABANK" },
    MastercardBin { bin: "519516", company: "SYNOVUS BANK" },
    MastercardBin { bin: "519518", company: "PUNJAB NATIONAL BANK" },
    MastercardBin { bin: "519525", company: "NEWCASTLE BUILDING SOCIETY" },
    MastercardBin { bin: "519538", company: "CITIBANK CANADA" },
    MastercardBin { bin: "519621", company: "EQUATORIAL COMMERCIAL BANK, LTD." },
    MastercardBin { bin: "519648", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "519656", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "519677", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "519684", company: "SILICON VALLEY BANK" },
    MastercardBin { bin: "519688", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "520058", company: "REDEBAN MULTICOLOR, S.A." },
    MastercardBin { bin: "520088", company: "OJSC PROMSVYAZBANK" },
    MastercardBin { bin: "520097", company: "TURKIYE GARANTI BANKASI A. S." },
    MastercardBin { bin: "520113", company: "JSCB MOSCOW INDUSTRIAL BANK" },
    MastercardBin { bin: "520122", company: "BANCO CITIBANK DE GUATEMALA, S.A." },
    MastercardBin { bin: "520176", company: "BANK OF NOVA SCOTIA JAMAICA, LTD." },
    MastercardBin { bin: "520186", company: "BANCO SANTANDER COLOMBIA, S.A." },
    MastercardBin { bin: "520309", company: "DEUTSCHER SPARKASSEN UND GIROVERBAND" },
    MastercardBin { bin: "520339", company: "SVYAZNOY BANK (JSC)" },
    MastercardBin { bin: "520342", company: "BANCO SANTANDER TOTTA, S.A." },
    MastercardBin { bin: "520389", company: "MONEY CARD ASSOCIATION PR LEAGUE, INC." },
    MastercardBin { bin: "520560", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "520575", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "520582", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "520930", company: "PROCREDIT BANK A.D." },
    MastercardBin { bin: "520942", company: "BANCA DI SASSARI S.P.A." },
    MastercardBin { bin: "520997", company: "STANDARD BANK OF SOUTH AFRICA, LTD." },
    MastercardBin { bin: "521082", company: "CSCBANK S.A.L." },
    MastercardBin { bin: "521165", company: "EURO KARTENSYSTEME GMBH" },
    MastercardBin { bin: "521181", company: "FINECOBANK S.P.A." },
    MastercardBin { bin: "521189", company: "FBME CARD SERVICES, LTD." },
    MastercardBin { bin: "521312", company: "CORP BANCA" },
    MastercardBin { bin: "521328", company: "CARD SERVICES FOR CREDIT UNIONS, INC." },
    MastercardBin { bin: "521334", company: "TCM BANK, N.A." },
    MastercardBin { bin: "521349", company: "TELLER, A.S." },
    MastercardBin { bin: "521396", company: "TMG FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "521699", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "521701", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "521718", company: "ICBA BANCARD, INC." },
    MastercardBin { bin: "521722", company: "COMPUTER SERVICES, INC." },
    MastercardBin { bin: "521726", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "521731", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "521750", company: "ICBA BANCARD, INC." },
    MastercardBin { bin: "521789", company: "MANUFACTURERS AND TRADERS TRUST COMPANY" },
    MastercardBin { bin: "521805", company: "BANCA SELLA S.P.A." },
    MastercardBin { bin: "521843", company: "CHASE BANK USA, N.A." },
    MastercardBin { bin: "521849", company: "FIRST INTERSTATE BANK" },
    MastercardBin { bin: "521884", company: "GE CAPITAL RETAIL BANK" },
    MastercardBin { bin: "521885", company: "FIRST COMMERCIAL BANK" },
    MastercardBin { bin: "521899", company: "BANK OF COMMUNICATIONS" },
    MastercardBin { bin: "522072", company: "T.BANK, S.A." },
    MastercardBin { bin: "522198", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "522231", company: "JSCB ROSBANK" },
    MastercardBin { bin: "522232", company: "SHANGHAI COMMERCIAL AND SAVINGS BANK, LTD." },
    MastercardBin { bin: "522238", company: "DEUTSCHE BANK S.P.A." },
    MastercardBin { bin: "522274", company: "CITIBANK SINGAPORE, LTD." },
    MastercardBin { bin: "522849", company: "SCOTIABANK EL SALVADOR, S.A." },
    MastercardBin { bin: "522858", company: "BANK SAINT-PETERSBURG OJSC" },
    MastercardBin { bin: "522867", company: "BOC CREDIT CARD (INTERNATIONAL), LTD." },
    MastercardBin { bin: "522883", company: "RIETUMU BANKA" },
    MastercardBin { bin: "522944", company: "HSBC BANK NEVADA, N.A." },
    MastercardBin { bin: "522978", company: "BANCO DO BRASIL, S.A." },
    MastercardBin { bin: "523028", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "523036", company: "INDUSTRIAL BANK CO., LTD." },
    MastercardBin { bin: "523798", company: "AMERICAN STATE BANK" },
    MastercardBin { bin: "523805", company: "SILVERTON BANK, N.A." },
    MastercardBin { bin: "523829", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "523833", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "523862", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "523874", company: "DATA CENTER INCORPORATED" },
    MastercardBin { bin: "523895", company: "ICBA BANCARD, INC." },
    MastercardBin { bin: "523899", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "523904", company: "RBS BANK (ROMANIA), S.A." },
    MastercardBin { bin: "523932", company: "DEUTSCHER SPARKASSEN UND GIROVERBAND" },
    MastercardBin { bin: "523969", company: "BANK ALFALAH, LTD." },
    MastercardBin { bin: "524000", company: "CARD SERVICES FOR CREDIT UNIONS, INC." },
    MastercardBin { bin: "524010", company: "FIRST COMMUNITY CREDIT UNION OF HOUSTON" },
    MastercardBin { bin: "524040", company: "OVERSEA-CHINESE BANKING CORP., LTD." },
    MastercardBin { bin: "524050", company: "RBS CITIZENS, N.A." },
    MastercardBin { bin: "524060", company: "FIRST PREMIER BANK" },
    MastercardBin { bin: "524071", company: "BANCO DE GUAYAQUIL, S.A." },
    MastercardBin { bin: "524092", company: "COMMERCIAL BANK OF DUBAI" },
    MastercardBin { bin: "524098", company: "JAMMU AND KASHMIR BANK, LTD." },
    MastercardBin { bin: "524114", company: "ALAHLI BANK OF KUWAIT (K.S.C.)" },
    MastercardBin { bin: "524174", company: "ARAB FINANCIAL SERVICES COMPANY B.S.C. (C)" },
    MastercardBin { bin: "524189", company: "BANK SINOPAC" },
    MastercardBin { bin: "524196", company: "BANK SINOPAC" },
    MastercardBin { bin: "524215", company: "CSCBANK S.A.L." },
    MastercardBin { bin: "524242", company: "HANASK CARD CO., LTD." },
    MastercardBin { bin: "524314", company: "COMMERCIAL BANK TRANSPORTNY INVESTITIONAL BANK, LTD." },
    MastercardBin { bin: "524319", company: "PT. BANK CIMB NIAGA TBK." },
    MastercardBin { bin: "524329", company: "STANDARD CHARTERED BANK" },
    MastercardBin { bin: "524334", company: "BLOM BANK S.A.L." },
    MastercardBin { bin: "524351", company: "CREDOMATIC LATINO AMERICANA" },
    MastercardBin { bin: "524355", company: "STANDARD CHARTERED BANK" },
    MastercardBin { bin: "524385", company: "CREDOMATIC DE MEXICO S.A. DE C.V." },
    MastercardBin { bin: "524729", company: "PUBLIC JSC FIRST UKRAINIAN INTERNATIONAL BANK" },
    MastercardBin { bin: "524836", company: "RAIFFEISEN BANK, LTD." },
    MastercardBin { bin: "525105", company: "ICBA BANCARD, INC." },
    MastercardBin { bin: "525258", company: "RESONA BANK, LTD." },
    MastercardBin { bin: "525409", company: "NORDNET BANK AB" },
    MastercardBin { bin: "525473", company: "NUEVO BANCO COMERCIAL, S.A." },
    MastercardBin { bin: "525476", company: "CREDISCOTIA FINANCIERA, S.A." },
    MastercardBin { bin: "525478", company: "HSBC BANK NEVADA, N.A." },
    MastercardBin { bin: "525499", company: "UNICREDIT S.P.A." },
    MastercardBin { bin: "525626", company: "PUBLIC JSC FIRST UKRAINIAN INTERNATIONAL BANK" },
    MastercardBin { bin: "525694", company: "ITAU UNIBANCO, S.A." },
    MastercardBin { bin: "525712", company: "100% BANCO, BANCO COMERCIAL, C.A." },
    MastercardBin { bin: "525739", company: "BANCO DE VENEZUELA, S.A.C.A." },
    MastercardBin { bin: "525754", company: "CREDICORP BANK, S.A." },
    MastercardBin { bin: "525780", company: "HSBC BANK MIDDLE EAST" },
    MastercardBin { bin: "525787", company: "VTB BANK (OPEN JOINT STOCK COM PANY)" },
    MastercardBin { bin: "525789", company: "EFG EUROBANK ERGASIAS, S.A." },
    MastercardBin { bin: "526201", company: "CITIBANK USA, N.A." },
    MastercardBin { bin: "526226", company: "CITIBANK, N.A." },
    MastercardBin { bin: "526227", company: "CITIBANK, N.A." },
    MastercardBin { bin: "526231", company: "CITIBANK USA, N.A." },
    MastercardBin { bin: "526270", company: "CITIBANK USA, N.A." },
    MastercardBin { bin: "526288", company: "CITIBANK USA, N.A." },
    MastercardBin { bin: "526396", company: "FBME BANK, LTD." },
    MastercardBin { bin: "526429", company: "BANCO G AND T CONTINENTAL, S.A." },
    MastercardBin { bin: "526452", company: "BANK POLSKA KASA OPIEKI S.A. (BANK PEKAO SA)" },
    MastercardBin { bin: "526631", company: "PAYLIFE BANK GMBH" },
    MastercardBin { bin: "526710", company: "BANKMUSCAT LTD. (S.A.O.G.)" },
    MastercardBin { bin: "526716", company: "COMMERCIAL INTERNATIONAL BANK (EGYPT) S.A.E." },
    MastercardBin { bin: "526736", company: "BANCA DI SASSARI S.P.A." },
    MastercardBin { bin: "526760", company: "BANK AUDI- AUDI SARADAR GROUP" },
    MastercardBin { bin: "526770", company: "BANK POLSKA KASA OPIEKI S.A. (BANK PEKAO SA)" },
    MastercardBin { bin: "526826", company: "REDEBAN MULTICOLOR, S.A." },
    MastercardBin { bin: "526839", company: "OJSC OTP BANK" },
    MastercardBin { bin: "526847", company: "OHRIDSKA BANKA A.D. - OHRID" },
    MastercardBin { bin: "526853", company: "PT. BANK BUKOPIN" },
    MastercardBin { bin: "526884", company: "EGYPTIAN BANKS CO. FOR TECHNOLOGICAL ADVANCEMENT, S.A" },
    MastercardBin { bin: "527409", company: "SYGMA BANQUE SOCIETE ANONYME ODDZIAL W POLSCE" },
    MastercardBin { bin: "527414", company: "INDUSTRIAL BANK CO., LTD." },
    MastercardBin { bin: "527421", company: "ATTIJARIWAFA BANK" },
    MastercardBin { bin: "527425", company: "ITAU UNIBANCO, S.A." },
    MastercardBin { bin: "527443", company: "COMMERCIAL BANK BNP PARIBAS VOSTOK LIMITED LIABILITY COMP" },
    MastercardBin { bin: "527460", company: "PT. BANK DANAMON INDONESIA" },
    MastercardBin { bin: "527470", company: "RBS CITIZENS, N.A." },
    MastercardBin { bin: "527829", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "527831", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "527849", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "527855", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "527881", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "528004", company: "BANCO NACIONAL DE CREDITO, C.A." },
    MastercardBin { bin: "528031", company: "BANK OF MONTREAL" },
    MastercardBin { bin: "528102", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "528103", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "528222", company: "FIRST CALIFORNIA BANK" },
    MastercardBin { bin: "528228", company: "BANCORP BANK" },
    MastercardBin { bin: "528443", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "528481", company: "GHANA COMMERCIAL BANK, LTD." },
    MastercardBin { bin: "528618", company: "HUNGARIAN VOLKSBANK, LTD." },
    MastercardBin { bin: "528706", company: "UNICREDIT BANK CZECH REPUBLIC, A.S." },
    MastercardBin { bin: "528718", company: "ABSA BANK, LTD." },
    MastercardBin { bin: "528725", company: "CITADEL F.C.U." },
    MastercardBin { bin: "528727", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "528755", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "528761", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "528843", company: "TARJETAS BANAMEX, SA DE CV, SOFOM E.R." },
    MastercardBin { bin: "528847", company: "REGIONS BANK" },
    MastercardBin { bin: "528937", company: "LOTTE CARD CO., LTD." },
    MastercardBin { bin: "528943", company: "AMBANK (M) BERHAD" },
    MastercardBin { bin: "528995", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "529025", company: "VTB24" },
    MastercardBin { bin: "529113", company: "PIRAEUS BANK EGYPT" },
    MastercardBin { bin: "529156", company: "CAPITAL ONE BANK (USA), N.A." },
    MastercardBin { bin: "529353", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "529387", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "529444", company: "WIRECARD BANK AG" },
    MastercardBin { bin: "529598", company: "EUROPAY FRANCE, S.A." },
    MastercardBin { bin: "529914", company: "COMMERCIAL BANK KHRESCHATYK" },
    MastercardBin { bin: "529931", company: "BANCO COOPERATIVO ESPANOL" },
    MastercardBin { bin: "529960", company: "BANQUE INVIK, S.A." },
    MastercardBin { bin: "529972", company: "ICICI BANK, LTD." },
    MastercardBin { bin: "529973", company: "ICICI BANK, LTD." },
    MastercardBin { bin: "529980", company: "BANK ISLAM MALAYSIA BERHAD" },
    MastercardBin { bin: "530021", company: "CHASE BANK USA, N.A." },
    MastercardBin { bin: "530040", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530044", company: "METABANK" },
    MastercardBin { bin: "530071", company: "UNITED BANK S.E.A." },
    MastercardBin { bin: "530084", company: "METABANK" },
    MastercardBin { bin: "530138", company: "METABANK/PAYONEER" },
    MastercardBin { bin: "530152", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530190", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530225", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530227", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530279", company: "OJSC BANK URALSIB" },
    MastercardBin { bin: "530415", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530437", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530444", company: "MASTERCAJAS, S.A." },
    MastercardBin { bin: "530461", company: "BALBOA BANK AND TRUST, CORP." },
    MastercardBin { bin: "530484", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530505", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530506", company: "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (MACAU), LTD." },
    MastercardBin { bin: "530519", company: "ZENITH BANK" },
    MastercardBin { bin: "530531", company: "WELLS FARGO BANK, N.A." },
    MastercardBin { bin: "530552", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530589", company: "MISSION F.C.U." },
    MastercardBin { bin: "530604", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530621", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530625", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530627", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530663", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530669", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530698", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "530701", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530736", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "530738", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "530744", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "530826", company: "DIE SCHWEIZERISCHE POST" },
    MastercardBin { bin: "530900", company: "BANK SAINT-PETERSBURG OJSC" },
    MastercardBin { bin: "530918", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530920", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530947", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "530990", company: "INDUSTRIAL AND COMMERCIAL BANK OF CHINA, LTD." },
    MastercardBin { bin: "530991", company: "KOMERCIJALNA BANKA A.D. BEOGRAD" },
    MastercardBin { bin: "531153", company: "JSCB PROBUSINESSBANK OJSC" },
    MastercardBin { bin: "531158", company: "CHEBANCA! S.P.A." },
    MastercardBin { bin: "531214", company: "BARCLAYS BANK PLC" },
    MastercardBin { bin: "531221", company: "UNIVERSAL FINANCING SERVICES" },
    MastercardBin { bin: "531222", company: "JSCB ROSBANK" },
    MastercardBin { bin: "531264", company: "BANK OF AMERICA, N.A." },
    MastercardBin { bin: "531302", company: "COMMERCIAL BANK MOSKOMMERTSBANK OJSC" },
    MastercardBin { bin: "531353", company: "WARKA BANK FOR INVESTMENT AND FINANCE" },
    MastercardBin { bin: "531628", company: "KINECTA F.C.U." },
    MastercardBin { bin: "531682", company: "BANK BPH SPOLKA AKCYJNA" },
    MastercardBin { bin: "531709", company: "CUETS FINANCIAL" },
    MastercardBin { bin: "531813", company: "BANQUE TUNISO KOWEITIENNE" },
    MastercardBin { bin: "531820", company: "ROYAL BANK OF SCOTLAND, N.V." },
    MastercardBin { bin: "531835", company: "NETWORK INTERNATIONAL LLC" },
    MastercardBin { bin: "531858", company: "OJSC BANK URALSIB" },
    MastercardBin { bin: "531879", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "531882", company: "BANCO HSBC (COSTA RICA), S.A." },
    MastercardBin { bin: "531898", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "531905", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "531916", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "531917", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "532211", company: "WASHINGTON MUTUAL" },
    MastercardBin { bin: "532227", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "532244", company: "PEOPLE'S UNITED BANK" },
    MastercardBin { bin: "532275", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "532276", company: "COMPUTER SERVICES, INC." },
    MastercardBin { bin: "532309", company: "FIRST DATA CONO SUR, S.R.L." },
    MastercardBin { bin: "532350", company: "CHASE BANK USA, N.A." },
    MastercardBin { bin: "532526", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "532538", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "532550", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "532601", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "532610", company: "EUROPAY (EUROCARD) ISRAEL, LTD." },
    MastercardBin { bin: "532672", company: "COMMERCIAL BANK OF KUWAIT, S.A.K." },
    MastercardBin { bin: "532688", company: "ABU DHABI COMMERCIAL BANK" },
    MastercardBin { bin: "532709", company: "UNITED BANK LIMITED (UBL)" },
    MastercardBin { bin: "532905", company: "FIA CARD SERVICES, N.A." },
    MastercardBin { bin: "532938", company: "MBNA AMERICA BANK, N.A." },
    MastercardBin { bin: "532984", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "533000", company: "VALITOR HF." },
    MastercardBin { bin: "533018", company: "INTESA SANPAOLO S.P.A." },
    MastercardBin { bin: "533047", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "533048", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "533060", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "533194", company: "OTP BANK JSC" },
    MastercardBin { bin: "533201", company: "CJSC COMMERCIAL BANK CITIBANK" },
    MastercardBin { bin: "533223", company: "PPF BANKA, A.S." },
    MastercardBin { bin: "533285", company: "UNIVERSITY NATIONAL BANK" },
    MastercardBin { bin: "533469", company: "JSC RUSSIAN STANDARD BANK" },
    MastercardBin { bin: "533599", company: "BANK RESPUBLIKA OJSC" },
    MastercardBin { bin: "533603", company: "R RAPHAEL AND SONS PLC" },
    MastercardBin { bin: "533617", company: "TELLER, A.S." },
    MastercardBin { bin: "533635", company: "UNIBANCA, S.A" },
    MastercardBin { bin: "533668", company: "COMMERCIAL BANK MASTER-BANK" },
    MastercardBin { bin: "533903", company: "BANCA POPOLARE DI MILANO" },
    MastercardBin { bin: "534056", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "534067", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "534080", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "534082", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "534136", company: "OJSC BANK URALSIB" },
    MastercardBin { bin: "534722", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "534751", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "534786", company: "BANCORP BANK" },
    MastercardBin { bin: "534890", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "534892", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "534908", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "536228", company: "CITIBANK, N.A." },
    MastercardBin { bin: "536444", company: "PUBLIC JSC COMMERCIAL BANK PRAVEX BANK" },
    MastercardBin { bin: "536468", company: "UNICRE - INSTITUICAO FINANCEIRA DE CREDITO, S.A." },
    MastercardBin { bin: "536479", company: "FIRST NATIONAL BANK OF OMAHA" },
    MastercardBin { bin: "536529", company: "BANCO IBI S.A. BANCO MULTIPLO" },
    MastercardBin { bin: "537020", company: "CSCBANK S.A.L." },
    MastercardBin { bin: "537156", company: "CITIBANK, N.A." },
    MastercardBin { bin: "537166", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "537169", company: "JPMORGAN CHASE BANK, N.A." },
    MastercardBin { bin: "537172", company: "JPMORGAN CHASE BANK, N.A." },
    MastercardBin { bin: "537728", company: "JSCB PROBUSINESSBANK OJSC" },
    MastercardBin { bin: "538635", company: "HERITAGE BUILDING SOCIETY, LTD." },
    MastercardBin { bin: "539625", company: "CENTRAL COOPERATIVE BANK PLC" },
    MastercardBin { bin: "539645", company: "BONNEVILLE BANK" },
    MastercardBin { bin: "539671", company: "HSBC - SAKS FIFTH AVENUE" },
    MastercardBin { bin: "539694", company: "METABANK" },
    MastercardBin { bin: "539709", company: "BANKIA, S.A." },
    MastercardBin { bin: "539738", company: "FNB BANK" },
    MastercardBin { bin: "539756", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "539763", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "539765", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "539807", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "539817", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "539819", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "539927", company: "STANDARD CHARTERED BANK" },
    MastercardBin { bin: "539978", company: "BANSI S.A. INSTITUCION DE BANCA MULTIPLE" },
    MastercardBin { bin: "540026", company: "RAIFFEISENBANK (BULGARIA) A.D." },
    MastercardBin { bin: "540069", company: "RHB BANK BERHAD" },
    MastercardBin { bin: "540080", company: "BANCO DE BOGOTA, S.A." },
    MastercardBin { bin: "540127", company: "CITIBANK, N.A., PHILIPPINES" },
    MastercardBin { bin: "540156", company: "HOUSING AND DEVELOPMENT BANK" },
    MastercardBin { bin: "540204", company: "CITIBANK (HONG KONG), LTD." },
    MastercardBin { bin: "540246", company: "BANKIA, S.A." },
    MastercardBin { bin: "540318", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "540319", company: "ZIONS FIRST NATIONAL BANK" },
    MastercardBin { bin: "540350", company: "CITIBANK, N.A." },
    MastercardBin { bin: "540365", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "540368", company: "SILVERTON BANK, N.A." },
    MastercardBin { bin: "540374", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "540386", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "540399", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "540418", company: "BAYPORT C.U." },
    MastercardBin { bin: "540432", company: "CITIBANK" },
    MastercardBin { bin: "540476", company: "BANCO DE CHILE" },
    MastercardBin { bin: "540478", company: "STANDARD CHARTERED BANK MALAYSIA BERHAD" },
    MastercardBin { bin: "540505", company: "CITIBANK TAIWAN, LTD." },
    MastercardBin { bin: "540520", company: "TAIWAN COOPERATIVE BANK" },
    MastercardBin { bin: "540522", company: "BANK OF NOVA SCOTIA JAMAICA, LTD." },
    MastercardBin { bin: "540554", company: "KOREA EXCHANGE BANK" },
    MastercardBin { bin: "540580", company: "HSBC BANK USA, N.A." },
    MastercardBin { bin: "540628", company: "BANCO PROVINCIAL S.A.C.A." },
    MastercardBin { bin: "540662", company: "BANK OF STANLY" },
    MastercardBin { bin: "540664", company: "GAZPROMBANK OJSC" },
    MastercardBin { bin: "540678", company: "FIRST CITIZENS BANK AND TRUST CO" },
    MastercardBin { bin: "540701", company: "BOC CREDIT CARD (INTERNATIONAL), LTD." },
    MastercardBin { bin: "540720", company: "MKB BANK ZRT." },
    MastercardBin { bin: "540805", company: "CITIBANK TAIWAN, LTD." },
    MastercardBin { bin: "540820", company: "BANK OF EAST ASIA, LTD." },
    MastercardBin { bin: "540823", company: "BANK FOR DEVELOPMENT AND FOREIGN ECONOMIC AFFAIRS (VNES" },
    MastercardBin { bin: "540839", company: "UMB BANK, N.A." },
    MastercardBin { bin: "540866", company: "MASTERCAJAS, S.A." },
    MastercardBin { bin: "540884", company: "ZENITH BANK" },
    MastercardBin { bin: "540901", company: "UNION NATIONAL BANK" },
    MastercardBin { bin: "540926", company: "KB KOOKMIN CARD CO., LTD." },
    MastercardBin { bin: "540935", company: "KB KOOKMIN CARD CO., LTD." },
    MastercardBin { bin: "540961", company: "UNION BANK OF CALIFORNIA, N.A." },
    MastercardBin { bin: "540986", company: "UNION BANK OF CALIFORNIA, N.A." },
    MastercardBin { bin: "540998", company: "CSCBANK S.A.L." },
    MastercardBin { bin: "541021", company: "WESTBURY BANK" },
    MastercardBin { bin: "541050", company: "VOLKSBANK SLOVENSKO, A.S." },
    MastercardBin { bin: "541102", company: "CHASE BANK USA, N.A." },
    MastercardBin { bin: "541138", company: "PULSE NETWORK LLC" },
    MastercardBin { bin: "541140", company: "BANCO SANTANDER COLOMBIA, S.A." },
    MastercardBin { bin: "541203", company: "BANCO DE OCCIDENTE, S.A." },
    MastercardBin { bin: "541233", company: "UNITED BULGARIAN BANK PLC" },
    MastercardBin { bin: "541248", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "541254", company: "BANCO NACIONAL DE COSTA RICA" },
    MastercardBin { bin: "541256", company: "EUROCARD AB" },
    MastercardBin { bin: "541281", company: "NEDBANK, LTD." },
    MastercardBin { bin: "541310", company: "DEUTSCHE BANK SOCIEDAD ANONIMA ESPANOLA" },
    MastercardBin { bin: "541376", company: "BAC FINANCIAL CORPORATION" },
    MastercardBin { bin: "541422", company: "LUSO INTERNATIONAL BANKING, LTD." },
    MastercardBin { bin: "541490", company: "APPLIED BANK" },
    MastercardBin { bin: "541502", company: "TELLER, A.S." },
    MastercardBin { bin: "541509", company: "INTERNATIONAL BANK OF QATAR (Q.S.C.)" },
    MastercardBin { bin: "541551", company: "BANCO DE RESERVAS DE LA REPUBLICA DOMINICANA" },
    MastercardBin { bin: "541556", company: "EURO KARTENSYSTEME GMBH" },
    MastercardBin { bin: "541592", company: "CONISTER BANK, LTD." },
    MastercardBin { bin: "541599", company: "BANCO POPULAR DOMINICANO, C. POR A." },
    MastercardBin { bin: "541632", company: "OJSC BANK URALSIB" },
    MastercardBin { bin: "541650", company: "RBS CITIZENS, N.A." },
    MastercardBin { bin: "541673", company: "OJSC DEMIRBANK" },
    MastercardBin { bin: "541675", company: "WASHINGTON MUTUAL" },
    MastercardBin { bin: "541677", company: "WASHINGTON MUTUAL" },
    MastercardBin { bin: "541763", company: "BANKIA, S.A." },
    MastercardBin { bin: "541801", company: "INDUSTRIAL AND COMMERCIAL BANK OF CHINA ASIA), LTD." },
    MastercardBin { bin: "541826", company: "BANAMEX USA" },
    MastercardBin { bin: "541931", company: "CITIBANK, N.A." },
    MastercardBin { bin: "541997", company: "ABSOLUT BANK" },
    MastercardBin { bin: "542047", company: "ARMENIAN CARD CJSC" },
    MastercardBin { bin: "542128", company: "DUTCH-BANGLA BANK, LTD." },
    MastercardBin { bin: "542164", company: "CSCBANK S.A.L." },
    MastercardBin { bin: "542194", company: "PODGORICKA BANKA SOCIETE GENERALE GROUP" },
    MastercardBin { bin: "542226", company: "MERCANTIL COMMERCEBANK, N.A." },
    MastercardBin { bin: "542347", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "542396", company: "FIRST NATIONAL BANK OF OMAHA" },
    MastercardBin { bin: "542462", company: "E. SUN COMMERCIAL BANK CO., LTD." },
    MastercardBin { bin: "542498", company: "RAIFFEISEN BANK, LTD." },
    MastercardBin { bin: "542539", company: "MERRICK BANK CORPORATION" },
    MastercardBin { bin: "542560", company: "AS UNICREDIT BANK" },
    MastercardBin { bin: "542606", company: "EURO KARTENSYSTEME GMBH" },
    MastercardBin { bin: "542621", company: "BANCARD, S.A." },
    MastercardBin { bin: "542640", company: "PT. BANK NEGARA INDONESIA (PERSERO) TBK." },
    MastercardBin { bin: "542747", company: "BANQUE SAUDI FRANSI" },
    MastercardBin { bin: "542808", company: "NEDBANK, LTD." },
    MastercardBin { bin: "542846", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "542967", company: "ING BANK, A.S." },
    MastercardBin { bin: "543013", company: "BANCA NAZIONALE DEL LAVORO S.P.A. - BNL" },
    MastercardBin { bin: "543201", company: "NOVA LJUBLJANSKA BANKA D.D., LJUBLJANA" },
    MastercardBin { bin: "543205", company: "STATE EXPORT-IMPORT BANK OF UKRAINE (UKREXIMBANK)" },
    MastercardBin { bin: "543237", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "543294", company: "FIRST COMMUNITY CREDIT UNION OF HOUSTON" },
    MastercardBin { bin: "543328", company: "HSBC BANK NEVADA, N.A." },
    MastercardBin { bin: "543339", company: "HSBC BANK NEVADA, N.A." },
    MastercardBin { bin: "543340", company: "ARAB AFRICAN INTERNATIONAL BANK" },
    MastercardBin { bin: "543354", company: "OJSC BANK URALSIB" },
    MastercardBin { bin: "543362", company: "FIRST PREMIER BANK" },
    MastercardBin { bin: "543377", company: "TAIPEI FUBON COMMERCIAL BANK CO., LTD." },
    MastercardBin { bin: "543400", company: "DENIZBANK, A.S." },
    MastercardBin { bin: "543401", company: "VSEOBECNA UVEROVA BANKA, A.S." },
    MastercardBin { bin: "543421", company: "CITIBANK COLOMBIA, S.A." },
    MastercardBin { bin: "543448", company: "CITIBANK COLOMBIA, S.A." },
    MastercardBin { bin: "543610", company: "BANCO GENERAL, S.A." },
    MastercardBin { bin: "543613", company: "TEACHERS C.U." },
    MastercardBin { bin: "543658", company: "BANCO SANTANDER (BRASIL), S.A." },
    MastercardBin { bin: "543685", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "543694", company: "MBNA CANADA BANK" },
    MastercardBin { bin: "543751", company: "JORDAN AHLI BANK" },
    MastercardBin { bin: "543885", company: "NUEVO BANCO DE ENTRE RIOS, S.A." },
    MastercardBin { bin: "543936", company: "EDUCATORS C.U." },
    MastercardBin { bin: "543944", company: "DENIZBANK, A.S." },
    MastercardBin { bin: "543957", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "544012", company: "MASTERCAJAS, S.A." },
    MastercardBin { bin: "544014", company: "FIRST DATA CONO SUR, S.R.L." },
    MastercardBin { bin: "544016", company: "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (MACAU), LTD." },
    MastercardBin { bin: "544034", company: "MARFIN POPULAR BANK PUBLIC CO., LTD." },
    MastercardBin { bin: "544036", company: "EUROPAY BELGIUM S.C.R.L." },
    MastercardBin { bin: "544050", company: "EUROPAY BELGIUM S.C.R.L." },
    MastercardBin { bin: "544084", company: "ENTERCARD NORGE, A.S." },
    MastercardBin { bin: "544116", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "544185", company: "CENTRAL TRUST BANK" },
    MastercardBin { bin: "544197", company: "BANCO CITIBANK DE COSTA RICA, S.A." },
    MastercardBin { bin: "544228", company: "TAISHIN INTERNATIONAL BANK" },
    MastercardBin { bin: "544264", company: "FIA CARD SERVICES, N.A." },
    MastercardBin { bin: "544279", company: "AL-MAWARID BANK S.A.L." },
    MastercardBin { bin: "544281", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "544356", company: "HSBC BANK USA, N.A." },
    MastercardBin { bin: "544362", company: "PUBLIC JSC FIRST UKRAINIAN INTERNATIONAL BANK" },
    MastercardBin { bin: "544410", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "544450", company: "JSC TRASTA KOMERCBANKA" },
    MastercardBin { bin: "544452", company: "BARCLAYS BANK PLC" },
    MastercardBin { bin: "544456", company: "ARMENIAN CARD CJSC" },
    MastercardBin { bin: "544565", company: "MECHANICS BANK" },
    MastercardBin { bin: "544567", company: "KEY CLIENT CARDS AND SOLUTIONS S.P.A." },
    MastercardBin { bin: "544614", company: "CANADIAN TIRE BANK" },
    MastercardBin { bin: "544632", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "544679", company: "COMERICA BANK" },
    MastercardBin { bin: "544694", company: "CORNER BANCA, S.A." },
    MastercardBin { bin: "544712", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "544727", company: "METABANK" },
    MastercardBin { bin: "544771", company: "SOCIEDAD CONJUNTA PARA LA EMISION Y GESTION DE MEDIOS DE" },
    MastercardBin { bin: "544786", company: "SOCIEDAD CONJUNTA PARA LA EMISION Y GESTION DE MEDIOS DE" },
    MastercardBin { bin: "544833", company: "BANCO CITICARD, S.A." },
    MastercardBin { bin: "544844", company: "BANCO CITICARD, S.A." },
    MastercardBin { bin: "544895", company: "CARD COMPLETE SERVICE BANK AG" },
    MastercardBin { bin: "544896", company: "PROCARD, S.A." },
    MastercardBin { bin: "544917", company: "RBS CITIZENS, N.A." },
    MastercardBin { bin: "544918", company: "RBS CITIZENS, N.A." },
    MastercardBin { bin: "544961", company: "HSBC BANK (PANAMA), S.A." },
    MastercardBin { bin: "545039", company: "TARJETAS BANAMEX, SA DE CV, SOFOM E.R." },
    MastercardBin { bin: "545094", company: "BANCO INTERACCIONES, S.A." },
    MastercardBin { bin: "545106", company: "DEUTSCHER SPARKASSEN UND GIROVERBAND" },
    MastercardBin { bin: "545129", company: "DEUTSCHER SPARKASSEN UND GIROVERBAND" },
    MastercardBin { bin: "545199", company: "PUBLIC JSC UNICREDIT BANK" },
    MastercardBin { bin: "545214", company: "OJSC OTP BANK" },
    MastercardBin { bin: "545224", company: "VTB24" },
    MastercardBin { bin: "545230", company: "INTERNATIONAL BANK OF AZERBAIJAN" },
    MastercardBin { bin: "545251", company: "ONEY S.P.A." },
    MastercardBin { bin: "545279", company: "AUSTRALIA AND NEW ZEALAND BANKING GROUP, LTD." },
    MastercardBin { bin: "545290", company: "BANCO MONEX, S.A., INSTITUCION DE BANCA MULTIPLE, MONEX GRUP" },
    MastercardBin { bin: "545316", company: "FIRST COMMUNITY C.U." },
    MastercardBin { bin: "545509", company: "FIRST ARKANSAS BANK AND TRUST" },
    MastercardBin { bin: "545563", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "545615", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "545658", company: "COMMERCIAL INTERNATIONAL BANK" },
    MastercardBin { bin: "545659", company: "BANCO SANTANDER, S.A." },
    MastercardBin { bin: "545797", company: "CREDOMATIC DEL ISTMO, S.A." },
    MastercardBin { bin: "545809", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "545845", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "545918", company: "FIRST AMERICAN BANK" },
    MastercardBin { bin: "546027", company: "CHEVRON F.C.U." },
    MastercardBin { bin: "546115", company: "CARD SERVICES FOR CREDIT UNIONS, INC." },
    MastercardBin { bin: "546123", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "546176", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "546179", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "546210", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "546220", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "546237", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "546245", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "546264", company: "SANTANDER CONSUMER FINANCE, S.A." },
    MastercardBin { bin: "546285", company: "JSCB FOR FOREIGN TRADE OF VIETNAM" },
    MastercardBin { bin: "546308", company: "EAST WEST BANKING CORPORATION" },
    MastercardBin { bin: "546318", company: "PT. BANK CIMB NIAGA TBK." },
    MastercardBin { bin: "546396", company: "U.S. BANK N.A. ND" },
    MastercardBin { bin: "546414", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "546442", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "546443", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "546453", company: "MAINSTREET C.U." },
    MastercardBin { bin: "546517", company: "JPMORGAN CHASE BANK, N.A." },
    MastercardBin { bin: "546536", company: "JPMORGAN CHASE BANK, N.A." },
    MastercardBin { bin: "546606", company: "FIRST ARKANSAS BANK AND TRUST" },
    MastercardBin { bin: "546621", company: "CHASE BANK USA, N.A." },
    MastercardBin { bin: "546630", company: "CAPITAL ONE BANK (USA), N.A." },
    MastercardBin { bin: "546638", company: "BARCLAYS BANK DELAWARE" },
    MastercardBin { bin: "546644", company: "PUBLIC JSC UNICREDIT BANK" },
    MastercardBin { bin: "546647", company: "CHASE BANK USA, N.A." },
    MastercardBin { bin: "546656", company: "CHASE BANK USA, N.A." },
    MastercardBin { bin: "546812", company: "SANTANDER CONSUMER BANK AG" },
    MastercardBin { bin: "546875", company: "JOINT STOCK HALYK SAVINGS BANK OF KAZAKHSTAN" },
    MastercardBin { bin: "546891", company: "JORDAN AHLI BANK" },
    MastercardBin { bin: "546897", company: "FIRSTCARIBBEAN INTERNATIONAL BANK (BARBADOS), LTD." },
    MastercardBin { bin: "547014", company: "NEW ENGLAND BANKCARD ASSOCIATION, INC." },
    MastercardBin { bin: "547022", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "547046", company: "SANTANDER CONSUMO, S.A. DE C.V. SOFOM, E.R." },
    MastercardBin { bin: "547075", company: "TARJETAS BANAMEX, SA DE CV, SOFOM E.R." },
    MastercardBin { bin: "547093", company: "TARJETAS BANAMEX, SA DE CV, SOFOM E.R." },
    MastercardBin { bin: "547109", company: "ITAU UNIBANCO, S.A." },
    MastercardBin { bin: "547148", company: "HSBC BANK MIDDLE EAST" },
    MastercardBin { bin: "547212", company: "BANK PRZEMYSLOWO-HANDLOWY PBK, S.A." },
    MastercardBin { bin: "547243", company: "MDM BANK OJSC" },
    MastercardBin { bin: "547248", company: "COPPERMARK BANK" },
    MastercardBin { bin: "547303", company: "KREDYT BANK, S.A." },
    MastercardBin { bin: "547305", company: "DNB NOR BANK ASA" },
    MastercardBin { bin: "547306", company: "OJSC BANK URALSIB" },
    MastercardBin { bin: "547366", company: "EFG EUROBANK ERGASIAS, S.A." },
    MastercardBin { bin: "547379", company: "BRD GROUPE SOCIETE GENERALE" },
    MastercardBin { bin: "547417", company: "BANCO SANTANDER COLOMBIA, S.A." },
    MastercardBin { bin: "547420", company: "BOC CREDIT CARD (INTERNATIONAL), LTD." },
    MastercardBin { bin: "547444", company: "BANCA INTESA AD BEOGRAD" },
    MastercardBin { bin: "547457", company: "BANCO BILBAO VIZCAYA ARGENTARIA COLOMBIA, S.A." },
    MastercardBin { bin: "547469", company: "BANCO EXTERIOR, C.A." },
    MastercardBin { bin: "547502", company: "ERSTE AND STEIERMARKISCHE BANK D.D." },
    MastercardBin { bin: "547537", company: "SCOTIABANK (BELIZE), LTD." },
    MastercardBin { bin: "547599", company: "BLOM BANK FRANCE, S.A." },
    MastercardBin { bin: "547613", company: "ZAO RAIFFEISENBANK" },
    MastercardBin { bin: "547693", company: "BANCO CITICARD, S.A." },
    MastercardBin { bin: "547737", company: "CESKOSLOVENSKA OBCHODNA BANKA, A.S." },
    MastercardBin { bin: "547767", company: "MEGA INTERNATIONAL COMMERCIAL BANK CO., LTD." },
    MastercardBin { bin: "547777", company: "JPMORGAN CHASE BANK, N.A." },
    MastercardBin { bin: "547786", company: "CITIBANK, N.A." },
    MastercardBin { bin: "547813", company: "FIRST HAWAIIAN BANK" },
    MastercardBin { bin: "547850", company: "BANKMED S.A.L." },
    MastercardBin { bin: "547867", company: "BANKVEREIN WERTHER AKTIENGESELLSCHAFT" },
    MastercardBin { bin: "547882", company: "SWEDBANK, A.S." },
    MastercardBin { bin: "547884", company: "BANK OF TRADE-UNIONS SOLIDARITY AND SOCIAL INVESTME" },
    MastercardBin { bin: "547915", company: "BANK OF STANLY" },
    MastercardBin { bin: "547925", company: "SBERBANK OF RUSSIA" },
    MastercardBin { bin: "547938", company: "SBERBANK OF RUSSIA" },
    MastercardBin { bin: "547996", company: "SPARKASSE BANK MAKEDONIJA AD SKOPJE" },
    MastercardBin { bin: "548009", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "548033", company: "ICBA BANCARD, INC." },
    MastercardBin { bin: "548115", company: "BANCO BILBAO VIZCAYA ARGENTARIA COLOMBIA, S.A." },
    MastercardBin { bin: "548125", company: "BANCO FINANCIERA COMERCIAL HONDURENA, S.A." },
    MastercardBin { bin: "548233", company: "BARCLAYS BANK LIMITED LIABILITY COMPANY" },
    MastercardBin { bin: "548267", company: "JSCB BANK OF MOSCOW" },
    MastercardBin { bin: "548347", company: "EURO KARTENSYSTEME GMBH" },
    MastercardBin { bin: "548430", company: "SBERBANK OF RUSSIA" },
    MastercardBin { bin: "548458", company: "ECOBANK NIGERIA PLC" },
    MastercardBin { bin: "548468", company: "SBERBANK OF RUSSIA" },
    MastercardBin { bin: "548496", company: "CAPITAL ONE BANK (CANADA BRANCH)" },
    MastercardBin { bin: "548545", company: "CARIBBEAN CREDIT CARD CORP., LTD." },
    MastercardBin { bin: "548572", company: "BANCO DO BRASIL, S.A." },
    MastercardBin { bin: "548655", company: "COMMERCIAL INNOVATION BANK ALFA-BANK" },
    MastercardBin { bin: "548741", company: "TELLER, A.S." },
    MastercardBin { bin: "548756", company: "UNICREDIT S.P.A." },
    MastercardBin { bin: "548783", company: "COMMERCIAL BANK MASTER-BANK" },
    MastercardBin { bin: "548790", company: "FIRST DATA CONO SUR, S.R.L." },
    MastercardBin { bin: "548793", company: "HSBC BANK (RR) (LIMITED LIABILITY COMPANY)" },
    MastercardBin { bin: "549085", company: "CHASE BANK USA, N.A." },
    MastercardBin { bin: "549099", company: "FIA CARD SERVICES, N.A." },
    MastercardBin { bin: "549138", company: "TARJETAS BANAMEX, SA DE CV, SOFOM E.R." },
    MastercardBin { bin: "549166", company: "REDEBAN MULTICOLOR, S.A." },
    MastercardBin { bin: "549182", company: "UNION BANK, N.A." },
    MastercardBin { bin: "549281", company: "CARD SERVICES FOR CREDIT UNIONS, INC." },
    MastercardBin { bin: "549407", company: "CARD SERVICES FOR CREDIT UNIONS, INC." },
    MastercardBin { bin: "549414", company: "CARD SERVICES FOR CREDIT UNIONS, INC." },
    MastercardBin { bin: "549457", company: "CARD SERVICES FOR CREDIT UNIONS, INC." },
    MastercardBin { bin: "549542", company: "MAGYAR CETELEM BANK RT." },
    MastercardBin { bin: "549619", company: "HSBC BANK (RR) (LIMITED LIABILITY COMPANY)" },
    MastercardBin { bin: "549705", company: "DEUTSCHER SPARKASSEN UND GIROVERBAND" },
    MastercardBin { bin: "549717", company: "HUNGARIAN VOLKSBANK, LTD." },
    MastercardBin { bin: "549758", company: "CSCBANK S.A.L." },
    MastercardBin { bin: "549762", company: "HOUSING AND DEVELOPMENT BANK" },
    MastercardBin { bin: "549771", company: "EQUATORIAL COMMERCIAL BANK, LTD." },
    MastercardBin { bin: "549797", company: "PUBLIC BANK BERHAD" },
    MastercardBin { bin: "549822", company: "JSCB ROSBANK" },
    MastercardBin { bin: "549870", company: "JSCB MOSCOW INDUSTRIAL BANK" },
    MastercardBin { bin: "549881", company: "OJSC BANK URALSIB" },
    MastercardBin { bin: "549895", company: "BANQUE TUNISO KOWEITIENNE" },
    MastercardBin { bin: "549957", company: "EURO KARTENSYSTEME GMBH" },
    MastercardBin { bin: "549958", company: "EURO KARTENSYSTEME GMBH" },
    MastercardBin { bin: "550467", company: "JSCB ROSBANK" },
    MastercardBin { bin: "550700", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "550714", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "550741", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "550742", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "550810", company: "NYCE PAYMENTS NETWORK, LLC" },
    MastercardBin { bin: "550816", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "550818", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "550827", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "550829", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "550843", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "550861", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "550888", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "550904", company: "HERRING BANK" },
    MastercardBin { bin: "550905", company: "NYCE PAYMENTS NETWORK, LLC" },
    MastercardBin { bin: "550908", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "550909", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "550952", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "550977", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "551024", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "551060", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "551070", company: "CITIBANK, N.A." },
    MastercardBin { bin: "551073", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "551078", company: "ICBA BANCARD, INC." },
    MastercardBin { bin: "551107", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "551126", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "551138", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "551143", company: "DATA CENTER INCORPORATED" },
    MastercardBin { bin: "551149", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "551220", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "551244", company: "BANCO NACIONAL DE MEXICO, S.A." },
    MastercardBin { bin: "551288", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "551327", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "551333", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "551340", company: "CARD SERVICES FOR CREDIT UNIONS, INC." },
    MastercardBin { bin: "551359", company: "ICBA BANCARD, INC." },
    MastercardBin { bin: "551371", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "551411", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "551432", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "551447", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "551461", company: "COMPUTER SERVICES, INC." },
    MastercardBin { bin: "551473", company: "NYCE PAYMENTS NETWORK, LLC" },
    MastercardBin { bin: "551483", company: "PULSE NETWORK LLC" },
    MastercardBin { bin: "551537", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "551551", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "551567", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "551573", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "551589", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "551665", company: "PSCU FINANCIAL SERVICES, INC." },
    MastercardBin { bin: "551684", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "551711", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "551725", company: "SHAZAM, INC." },
    MastercardBin { bin: "551766", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "551783", company: "SHAZAM, INC." },
    MastercardBin { bin: "551786", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "551792", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "551795", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "551802", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "551806", company: "ICBA BANCARD, INC." },
    MastercardBin { bin: "551811", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "551821", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "551859", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "551868", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "551871", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "551880", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "551910", company: "ICBA BANCARD, INC." },
    MastercardBin { bin: "551991", company: "AMALGAMATED BANK" },
    MastercardBin { bin: "552032", company: "CATHAY UNITED BANK" },
    MastercardBin { bin: "552045", company: "FRANSABANK S.A.L." },
    MastercardBin { bin: "552071", company: "UNICREDIT BANK HUNGARY ZRT." },
    MastercardBin { bin: "552078", company: "GULF BANK K.S.C." },
    MastercardBin { bin: "552086", company: "UNITED OVERSEAS BANK (MALAYSIA) BERHAD" },
    MastercardBin { bin: "552093", company: "CITIBANK" },
    MastercardBin { bin: "552096", company: "TURKIYE IS BANKASI, A.S." },
    MastercardBin { bin: "552107", company: "HSBC BANK MIDDLE EAST" },
    MastercardBin { bin: "552133", company: "HANASK CARD CO., LTD." },
    MastercardBin { bin: "552157", company: "LLOYDS TSB BANK PLC" },
    MastercardBin { bin: "552166", company: "FAR EASTERN INTERNATIONAL BANK" },
    MastercardBin { bin: "552183", company: "ISRAEL CREDIT CARDS, LTD." },
    MastercardBin { bin: "552193", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "552280", company: "ALLIED BANKING CORPORATION" },
    MastercardBin { bin: "552291", company: "NETWORK INTERNATIONAL LLC" },
    MastercardBin { bin: "552292", company: "BANCO DE VENEZUELA, S.A.C.A." },
    MastercardBin { bin: "552297", company: "BANCO CITIBANK, S.A." },
    MastercardBin { bin: "552302", company: "STANDARD CHARTERED BANK MALAYSIA BERHAD" },
    MastercardBin { bin: "552369", company: "CSCBANK S.A.L." },
    MastercardBin { bin: "552428", company: "FIA CARD SERVICES, N.A." },
    MastercardBin { bin: "552456", company: "SCOTIABANK (BAHAMAS), LTD." },
    MastercardBin { bin: "552519", company: "NORDEA BANK NORGE ASA" },
    MastercardBin { bin: "552525", company: "BANCO DE CHILE" },
    MastercardBin { bin: "552530", company: "BANCO BRADESCO, S.A." },
    MastercardBin { bin: "552566", company: "COMMERCIAL INTERNATIONAL BANK (EGYPT) S.A.E." },
    MastercardBin { bin: "552600", company: "GOSPODARCZY BANK WIELKOPOLSKI S.A. (GBW S.A.)" },
    MastercardBin { bin: "552606", company: "JSC CARTU BANK" },
    MastercardBin { bin: "552668", company: "CAIXA ECONOMICA FEDERAL" },
    MastercardBin { bin: "552708", company: "OJSC COMMERCIAL BANK" },
    MastercardBin { bin: "552715", company: "BRE BANK SPOLKA AKCYJNA BRE BANK, S.A." },
    MastercardBin { bin: "552733", company: "CESKA SPORITELNA A.S. (CZECH SAVINGS BANK CO.)" },
    MastercardBin { bin: "552739", company: "BOC CREDIT CARD (INTERNATIONAL), LTD." },
    MastercardBin { bin: "552751", company: "EURO KARTENSYSTEME GMBH" },
    MastercardBin { bin: "552780", company: "BANCO BRADESCO, S.A." },
    MastercardBin { bin: "552822", company: "BANK OF MONTREAL" },
    MastercardBin { bin: "552845", company: "OJSC BANK URALSIB" },
    MastercardBin { bin: "552865", company: "BANCO DE BOGOTA, S.A." },
    MastercardBin { bin: "552867", company: "JSCB SOYUZ" },
    MastercardBin { bin: "552893", company: "FIRST COMMUNITY CREDIT UNION OF HOUSTON" },
    MastercardBin { bin: "552914", company: "ITAU UNIBANCO, S.A." },
    MastercardBin { bin: "552925", company: "CITIBANK BERHAD" },
    MastercardBin { bin: "552927", company: "CITIGROUP PTY, LTD." },
    MastercardBin { bin: "552930", company: "CITIBANK" },
    MastercardBin { bin: "553036", company: "RANDOLPH BROOKS F.C.U." },
    MastercardBin { bin: "553041", company: "BANK BPH SPOLKA AKCYJNA" },
    MastercardBin { bin: "553046", company: "OHRIDSKA BANKA A.D. - OHRID" },
    MastercardBin { bin: "553063", company: "TELLER, A.S." },
    MastercardBin { bin: "553065", company: "ERSTE AND STEIERMARKISCHE BANK D.D." },
    MastercardBin { bin: "553081", company: "SHAZAM, INC." },
    MastercardBin { bin: "553091", company: "PUBLIC JSC UNICREDIT BANK" },
    MastercardBin { bin: "553168", company: "KOREA EXCHANGE BANK" },
    MastercardBin { bin: "553211", company: "BC CARD CO., LTD." },
    MastercardBin { bin: "553283", company: "RIZAL COMMERCIAL BANKING CORPORATION" },
    MastercardBin { bin: "553398", company: "STANDARD CHARTERED BANK (HONG KONG), LTD." },
    MastercardBin { bin: "553410", company: "CITIBANK" },
    MastercardBin { bin: "553419", company: "RBS CITIZENS, N.A." },
    MastercardBin { bin: "553438", company: "BANCO DEL TESORO C.A. BANCO UNIVERS.A.L." },
    MastercardBin { bin: "553452", company: "BANCO RIPLEY" },
    MastercardBin { bin: "553475", company: "BANCO ATLANTIDA, S.A." },
    MastercardBin { bin: "553581", company: "OJSC BANK URALSIB" },
    MastercardBin { bin: "553702", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "553710", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "553716", company: "PULSE NETWORK LLC" },
    MastercardBin { bin: "553752", company: "PEOPLE'S UNITED BANK" },
    MastercardBin { bin: "553805", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "553836", company: "CU COOPERATIVE SYSTEMS" },
    MastercardBin { bin: "553838", company: "DATA CENTER INCORPORATED" },
    MastercardBin { bin: "553882", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "553891", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "553919", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "553938", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "553950", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "553958", company: "NYCE PAYMENTS NETWORK, LLC" },
    MastercardBin { bin: "553977", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "554010", company: "MASTERCAJAS, S.A." },
    MastercardBin { bin: "554082", company: "MASTERCAJAS, S.A." },
    MastercardBin { bin: "554099", company: "MASTERCAJAS, S.A." },
    MastercardBin { bin: "554291", company: "FIA CARD SERVICES, N.A." },
    MastercardBin { bin: "554335", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "554341", company: "SHAZAM, INC." },
    MastercardBin { bin: "554354", company: "CESKOSLOVENSKA OBCHODNI BANKA, A.S." },
    MastercardBin { bin: "554433", company: "SUNNY BANK" },
    MastercardBin { bin: "554487", company: "BANK OF EAST ASIA, LTD." },
    MastercardBin { bin: "554489", company: "EUROCARD AB" },
    MastercardBin { bin: "554492", company: "BANCO NACIONAL DE MEXICO, S.A." },
    MastercardBin { bin: "554540", company: "BANCO BICENTENARIO BANCO UNIVERSAL, C.A." },
    MastercardBin { bin: "554646", company: "BFC BANCO FONDO COMUN, C.A. BANCO UNIVERS.A.L." },
    MastercardBin { bin: "554787", company: "WELLS FARGO BANK, N.A." },
    MastercardBin { bin: "554798", company: "BANCO PLAZA, C.A." },
    MastercardBin { bin: "554860", company: "CITIBANK DEL PERU, S.A." },
    MastercardBin { bin: "554907", company: "FIRST GULF BANK PJSC" },
    MastercardBin { bin: "554935", company: "BANCO G AND T CONTINENTAL, S.A." },
    MastercardBin { bin: "554963", company: "KB KOOKMIN CARD CO., LTD." },
    MastercardBin { bin: "554973", company: "KB KOOKMIN CARD CO., LTD." },
    MastercardBin { bin: "555013", company: "HSBC BANK MIDDLE EAST" },
    MastercardBin { bin: "555035", company: "CITIBANK" },
    MastercardBin { bin: "555081", company: "WRIGHT EXPRESS FINANCIAL SERVICES CORPORATION" },
    MastercardBin { bin: "555941", company: "NETWORK INTERNATIONAL LLC" },
    MastercardBin { bin: "555953", company: "BANK LEUMI LE-ISRAEL B.M." },
    MastercardBin { bin: "556022", company: "INTESA SANPAOLO BANK ALBANIA SHA." },
    MastercardBin { bin: "556059", company: "TRADE AND DEVELOPMENT BANK OF MONGOLIA" },
    MastercardBin { bin: "556319", company: "BANK OF THE WEST" },
    MastercardBin { bin: "556603", company: "EURO KARTENSYSTEME GMBH" },
    MastercardBin { bin: "556620", company: "HDFC BANK, LTD." },
    MastercardBin { bin: "556634", company: "DEUTSCHE BANK S.P.A." },
    MastercardBin { bin: "556661", company: "SEB KORT DANMARK" },
    MastercardBin { bin: "556670", company: "ITAU UNIBANCO, S.A." },
    MastercardBin { bin: "556777", company: "CIT BANK" },
    MastercardBin { bin: "556862", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "556924", company: "CITIBANK, N.A." },
    MastercardBin { bin: "556927", company: "FIA CARD SERVICES, N.A." },
    MastercardBin { bin: "556960", company: "BANK OF AMERICA CANADA" },
    MastercardBin { bin: "556968", company: "JPMORGAN CHASE BANK, N.A." },
    MastercardBin { bin: "556979", company: "ABN AMRO BANK, N.V." },
    MastercardBin { bin: "557141", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "557146", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "557177", company: "FIRST NIAGARA BANK" },
    MastercardBin { bin: "557193", company: "HEARTLAND BANK" },
    MastercardBin { bin: "557213", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "557232", company: "NYCE PAYMENTS NETWORK, LLC" },
    MastercardBin { bin: "557248", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "557271", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "557288", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "557293", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "557301", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "557354", company: "NEWCASTLE BUILDING SOCIETY" },
    MastercardBin { bin: "557521", company: "BANK PRZEMYSLOWO-HANDLOWY PBK, S.A." },
    MastercardBin { bin: "557533", company: "BANK DNB NORD POLSKA, S.A." },
    MastercardBin { bin: "557550", company: "FIFTH THIRD BANK" },
    MastercardBin { bin: "557553", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "557606", company: "SAUDI HOLLANDI BANK" },
    MastercardBin { bin: "557612", company: "RENASANT BANK" },
    MastercardBin { bin: "557635", company: "TEACHERS C.U." },
    MastercardBin { bin: "557636", company: "CSCBANK S.A.L." },
    MastercardBin { bin: "557676", company: "SEYLAN BANK PLC" },
    MastercardBin { bin: "557681", company: "BLOM BANK S.A.L." },
    MastercardBin { bin: "557693", company: "INTERCONTINENTAL BANK PLC" },
    MastercardBin { bin: "557920", company: "SCOTIABANK INVERLAT, S.A." },
    MastercardBin { bin: "558025", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "558042", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "558072", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "558115", company: "JPMORGAN CHASE BANK, N.A." },
    MastercardBin { bin: "558116", company: "JPMORGAN CHASE BANK, N.A." },
    MastercardBin { bin: "558145", company: "U.S. BANK NATIONAL ASSOCIATION, ND" },
    MastercardBin { bin: "558183", company: "STAR PROCESSING, INC." },
    MastercardBin { bin: "558194", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "558219", company: "FIDELITY INFORMATION SERVICES, INC." },
    MastercardBin { bin: "558249", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "558258", company: "JSCB ROSBANK" },
    MastercardBin { bin: "558259", company: "PUBLIC JSC UKRSIBBANK" },
    MastercardBin { bin: "558279", company: "ING BANK RT." },
    MastercardBin { bin: "558282", company: "SEB BANKAS AB" },
    MastercardBin { bin: "558305", company: "BANCO CITICARD, S.A." },
    MastercardBin { bin: "558371", company: "HUNGARIAN VOLKSBANK, LTD." },
    MastercardBin { bin: "558381", company: "PUBLIC JSC FIRST UKRAINIAN INTERNATIONAL BANK" },
    MastercardBin { bin: "558406", company: "DEUTSCHER SPARKASSEN UND GIROVERBAND" },
    MastercardBin { bin: "558433", company: "UNIVERSAL INVESTMENT BANK AD SKOPJE" },
    MastercardBin { bin: "558441", company: "DANSKE BANK A/S" },
    MastercardBin { bin: "558471", company: "JSCB VICTORIABANK" },
    MastercardBin { bin: "558474", company: "CARD SERVICES FOR CREDIT UNIONS, INC." },
    MastercardBin { bin: "558501", company: "COMMERCIAL BANK ASSISTANCE FOR PUBLIC INITIATIVES SOBINBANK" },
    MastercardBin { bin: "558592", company: "BANK GOSPODARKI ZYWNOSCIOWEJ SPOLKA AKCYJNA" },
    MastercardBin { bin: "558614", company: "CORNER BANCA, S.A." },
    MastercardBin { bin: "558629", company: "VTB BANK OJSC" },
    MastercardBin { bin: "558661", company: "NOVA LJUBLJANSKA BANKA D.D., LJUBLJANA" },
    MastercardBin { bin: "558753", company: "CITIBANK, N.A. SOUTH AFRICA" },
    MastercardBin { bin: "558757", company: "CHASE BANK USA, N.A." },
    MastercardBin { bin: "558814", company: "CITIBANK USA, N.A." },
    MastercardBin { bin: "558820", company: "FRANSABANK S.A.L." },
    MastercardBin { bin: "558834", company: "BANCO DE VENEZUELA, S.A.C.A." },
    MastercardBin { bin: "558843", company: "CITIBANK USA, N.A." },
    MastercardBin { bin: "558861", company: "CITIBANK, N.A." },
    MastercardBin { bin: "558866", company: "TAIWAN BUSINESS BANK" },
    MastercardBin { bin: "558882", company: "BANQUE FEDERATIVE DU CREDIT MUTUEL (BFCM)" },
    MastercardBin { bin: "559003", company: "JACK HENRY AND ASSOCIATES" },
    MastercardBin { bin: "559011", company: "FISERV SOLUTIONS, INC." },
    MastercardBin { bin: "559040", company: "JPMORGAN CHASE BANK, N.A." },
];

/// Look up a Mastercard company by BIN prefix (binary search).
pub fn lookup_mastercard(bin: &str) -> Option<&'static str> {
    let prefix = if bin.len() >= 6 { &bin[..6] } else { bin };
    MASTERCARD_BINS
        .binary_search_by_key(&prefix, |e| e.bin)
        .ok()
        .map(|i| MASTERCARD_BINS[i].company)
}
