//! Phone country code lookup — auto-generated from phone_codes.json

pub struct PhoneCode {
    pub code: &'static str,
    pub country: &'static str,
}

static PHONE_CODES: &[PhoneCode] = &[
    PhoneCode { code: "+ 345", country: "Cayman Islands" },
    PhoneCode { code: "+1", country: "United States" },
    PhoneCode { code: "+1 242", country: "Bahamas" },
    PhoneCode { code: "+1 246", country: "Barbados" },
    PhoneCode { code: "+1 264", country: "Anguilla" },
    PhoneCode { code: "+1 284", country: "Virgin Islands, British" },
    PhoneCode { code: "+1 340", country: "Virgin Islands, U.S." },
    PhoneCode { code: "+1 441", country: "Bermuda" },
    PhoneCode { code: "+1 473", country: "Grenada" },
    PhoneCode { code: "+1 649", country: "Turks and Caicos Islands" },
    PhoneCode { code: "+1 670", country: "Northern Mariana Islands" },
    PhoneCode { code: "+1 671", country: "Guam" },
    PhoneCode { code: "+1 684", country: "AmericanSamoa" },
    PhoneCode { code: "+1 758", country: "Saint Lucia" },
    PhoneCode { code: "+1 767", country: "Dominica" },
    PhoneCode { code: "+1 784", country: "Saint Vincent and the Grenadines" },
    PhoneCode { code: "+1 849", country: "Dominican Republic" },
    PhoneCode { code: "+1 868", country: "Trinidad and Tobago" },
    PhoneCode { code: "+1 869", country: "Saint Kitts and Nevis" },
    PhoneCode { code: "+1 876", country: "Jamaica" },
    PhoneCode { code: "+1 939", country: "Puerto Rico" },
    PhoneCode { code: "+1268", country: "Antigua and Barbuda" },
    PhoneCode { code: "+1664", country: "Montserrat" },
    PhoneCode { code: "+20", country: "Egypt" },
    PhoneCode { code: "+212", country: "Morocco" },
    PhoneCode { code: "+213", country: "Algeria" },
    PhoneCode { code: "+216", country: "Tunisia" },
    PhoneCode { code: "+218", country: "Libyan Arab Jamahiriya" },
    PhoneCode { code: "+220", country: "Gambia" },
    PhoneCode { code: "+221", country: "Senegal" },
    PhoneCode { code: "+222", country: "Mauritania" },
    PhoneCode { code: "+223", country: "Mali" },
    PhoneCode { code: "+224", country: "Guinea" },
    PhoneCode { code: "+225", country: "Cote d'Ivoire" },
    PhoneCode { code: "+226", country: "Burkina Faso" },
    PhoneCode { code: "+227", country: "Niger" },
    PhoneCode { code: "+228", country: "Togo" },
    PhoneCode { code: "+229", country: "Benin" },
    PhoneCode { code: "+230", country: "Mauritius" },
    PhoneCode { code: "+231", country: "Liberia" },
    PhoneCode { code: "+232", country: "Sierra Leone" },
    PhoneCode { code: "+233", country: "Ghana" },
    PhoneCode { code: "+234", country: "Nigeria" },
    PhoneCode { code: "+235", country: "Chad" },
    PhoneCode { code: "+236", country: "Central African Republic" },
    PhoneCode { code: "+237", country: "Cameroon" },
    PhoneCode { code: "+238", country: "Cape Verde" },
    PhoneCode { code: "+239", country: "Sao Tome and Principe" },
    PhoneCode { code: "+240", country: "Equatorial Guinea" },
    PhoneCode { code: "+241", country: "Gabon" },
    PhoneCode { code: "+242", country: "Congo" },
    PhoneCode { code: "+243", country: "Congo, The Democratic Republic of the Congo" },
    PhoneCode { code: "+244", country: "Angola" },
    PhoneCode { code: "+245", country: "Guinea-Bissau" },
    PhoneCode { code: "+246", country: "British Indian Ocean Territory" },
    PhoneCode { code: "+248", country: "Seychelles" },
    PhoneCode { code: "+249", country: "Sudan" },
    PhoneCode { code: "+250", country: "Rwanda" },
    PhoneCode { code: "+251", country: "Ethiopia" },
    PhoneCode { code: "+252", country: "Somalia" },
    PhoneCode { code: "+253", country: "Djibouti" },
    PhoneCode { code: "+254", country: "Kenya" },
    PhoneCode { code: "+255", country: "Tanzania, United Republic of Tanzania" },
    PhoneCode { code: "+256", country: "Uganda" },
    PhoneCode { code: "+257", country: "Burundi" },
    PhoneCode { code: "+258", country: "Mozambique" },
    PhoneCode { code: "+260", country: "Zambia" },
    PhoneCode { code: "+261", country: "Madagascar" },
    PhoneCode { code: "+262", country: "Reunion" },
    PhoneCode { code: "+263", country: "Zimbabwe" },
    PhoneCode { code: "+264", country: "Namibia" },
    PhoneCode { code: "+265", country: "Malawi" },
    PhoneCode { code: "+266", country: "Lesotho" },
    PhoneCode { code: "+267", country: "Botswana" },
    PhoneCode { code: "+268", country: "Swaziland" },
    PhoneCode { code: "+269", country: "Comoros" },
    PhoneCode { code: "+27", country: "South Africa" },
    PhoneCode { code: "+290", country: "Saint Helena, Ascension and Tristan Da Cunha" },
    PhoneCode { code: "+291", country: "Eritrea" },
    PhoneCode { code: "+297", country: "Aruba" },
    PhoneCode { code: "+298", country: "Faroe Islands" },
    PhoneCode { code: "+299", country: "Greenland" },
    PhoneCode { code: "+30", country: "Greece" },
    PhoneCode { code: "+31", country: "Netherlands" },
    PhoneCode { code: "+32", country: "Belgium" },
    PhoneCode { code: "+33", country: "France" },
    PhoneCode { code: "+34", country: "Spain" },
    PhoneCode { code: "+350", country: "Gibraltar" },
    PhoneCode { code: "+351", country: "Portugal" },
    PhoneCode { code: "+352", country: "Luxembourg" },
    PhoneCode { code: "+353", country: "Ireland" },
    PhoneCode { code: "+354", country: "Iceland" },
    PhoneCode { code: "+355", country: "Albania" },
    PhoneCode { code: "+356", country: "Malta" },
    PhoneCode { code: "+357", country: "Cyprus" },
    PhoneCode { code: "+358", country: "Finland" },
    PhoneCode { code: "+359", country: "Bulgaria" },
    PhoneCode { code: "+36", country: "Hungary" },
    PhoneCode { code: "+370", country: "Lithuania" },
    PhoneCode { code: "+371", country: "Latvia" },
    PhoneCode { code: "+372", country: "Estonia" },
    PhoneCode { code: "+373", country: "Moldova" },
    PhoneCode { code: "+374", country: "Armenia" },
    PhoneCode { code: "+375", country: "Belarus" },
    PhoneCode { code: "+376", country: "Andorra" },
    PhoneCode { code: "+377", country: "Monaco" },
    PhoneCode { code: "+378", country: "San Marino" },
    PhoneCode { code: "+379", country: "Holy See (Vatican City State)" },
    PhoneCode { code: "+380", country: "Ukraine" },
    PhoneCode { code: "+381", country: "Serbia" },
    PhoneCode { code: "+382", country: "Montenegro" },
    PhoneCode { code: "+383", country: "Kosovo" },
    PhoneCode { code: "+385", country: "Croatia" },
    PhoneCode { code: "+386", country: "Slovenia" },
    PhoneCode { code: "+387", country: "Bosnia and Herzegovina" },
    PhoneCode { code: "+389", country: "Macedonia" },
    PhoneCode { code: "+39", country: "Italy" },
    PhoneCode { code: "+40", country: "Romania" },
    PhoneCode { code: "+41", country: "Switzerland" },
    PhoneCode { code: "+420", country: "Czech Republic" },
    PhoneCode { code: "+421", country: "Slovakia" },
    PhoneCode { code: "+423", country: "Liechtenstein" },
    PhoneCode { code: "+43", country: "Austria" },
    PhoneCode { code: "+44", country: "United Kingdom" },
    PhoneCode { code: "+45", country: "Denmark" },
    PhoneCode { code: "+46", country: "Sweden" },
    PhoneCode { code: "+47", country: "Svalbard and Jan Mayen" },
    PhoneCode { code: "+48", country: "Poland" },
    PhoneCode { code: "+49", country: "Germany" },
    PhoneCode { code: "+500", country: "South Georgia and the South Sandwich Islands" },
    PhoneCode { code: "+501", country: "Belize" },
    PhoneCode { code: "+502", country: "Guatemala" },
    PhoneCode { code: "+503", country: "El Salvador" },
    PhoneCode { code: "+504", country: "Honduras" },
    PhoneCode { code: "+505", country: "Nicaragua" },
    PhoneCode { code: "+506", country: "Costa Rica" },
    PhoneCode { code: "+507", country: "Panama" },
    PhoneCode { code: "+508", country: "Saint Pierre and Miquelon" },
    PhoneCode { code: "+509", country: "Haiti" },
    PhoneCode { code: "+51", country: "Peru" },
    PhoneCode { code: "+52", country: "Mexico" },
    PhoneCode { code: "+53", country: "Cuba" },
    PhoneCode { code: "+54", country: "Argentina" },
    PhoneCode { code: "+55", country: "Brazil" },
    PhoneCode { code: "+56", country: "Chile" },
    PhoneCode { code: "+57", country: "Colombia" },
    PhoneCode { code: "+58", country: "Venezuela, Bolivarian Republic of Venezuela" },
    PhoneCode { code: "+590", country: "Saint Martin" },
    PhoneCode { code: "+591", country: "Bolivia, Plurinational State of" },
    PhoneCode { code: "+593", country: "Ecuador" },
    PhoneCode { code: "+594", country: "French Guiana" },
    PhoneCode { code: "+595", country: "Paraguay" },
    PhoneCode { code: "+596", country: "Martinique" },
    PhoneCode { code: "+597", country: "SuriName" },
    PhoneCode { code: "+598", country: "Uruguay" },
    PhoneCode { code: "+599", country: "Netherlands Antilles" },
    PhoneCode { code: "+60", country: "Malaysia" },
    PhoneCode { code: "+61", country: "Cocos (Keeling) Islands" },
    PhoneCode { code: "+62", country: "Indonesia" },
    PhoneCode { code: "+63", country: "Philippines" },
    PhoneCode { code: "+64", country: "New Zealand" },
    PhoneCode { code: "+65", country: "Singapore" },
    PhoneCode { code: "+66", country: "Thailand" },
    PhoneCode { code: "+670", country: "Timor-Leste" },
    PhoneCode { code: "+672", country: "Norfolk Island" },
    PhoneCode { code: "+673", country: "Brunei Darussalam" },
    PhoneCode { code: "+674", country: "Nauru" },
    PhoneCode { code: "+675", country: "Papua New Guinea" },
    PhoneCode { code: "+676", country: "Tonga" },
    PhoneCode { code: "+677", country: "Solomon Islands" },
    PhoneCode { code: "+678", country: "Vanuatu" },
    PhoneCode { code: "+679", country: "Fiji" },
    PhoneCode { code: "+680", country: "Palau" },
    PhoneCode { code: "+681", country: "Wallis and Futuna" },
    PhoneCode { code: "+682", country: "Cook Islands" },
    PhoneCode { code: "+683", country: "Niue" },
    PhoneCode { code: "+685", country: "Samoa" },
    PhoneCode { code: "+686", country: "Kiribati" },
    PhoneCode { code: "+687", country: "New Caledonia" },
    PhoneCode { code: "+688", country: "Tuvalu" },
    PhoneCode { code: "+689", country: "French Polynesia" },
    PhoneCode { code: "+690", country: "Tokelau" },
    PhoneCode { code: "+691", country: "Micronesia, Federated States of Micronesia" },
    PhoneCode { code: "+692", country: "Marshall Islands" },
    PhoneCode { code: "+7", country: "Russia" },
    PhoneCode { code: "+7 7", country: "Kazakhstan" },
    PhoneCode { code: "+81", country: "Japan" },
    PhoneCode { code: "+82", country: "Korea, Republic of South Korea" },
    PhoneCode { code: "+84", country: "Vietnam" },
    PhoneCode { code: "+850", country: "Korea, Democratic People's Republic of Korea" },
    PhoneCode { code: "+852", country: "Hong Kong" },
    PhoneCode { code: "+853", country: "Macao" },
    PhoneCode { code: "+855", country: "Cambodia" },
    PhoneCode { code: "+856", country: "Laos" },
    PhoneCode { code: "+86", country: "China" },
    PhoneCode { code: "+872", country: "Pitcairn" },
    PhoneCode { code: "+880", country: "Bangladesh" },
    PhoneCode { code: "+886", country: "Taiwan" },
    PhoneCode { code: "+90", country: "Turkey" },
    PhoneCode { code: "+91", country: "India" },
    PhoneCode { code: "+92", country: "Pakistan" },
    PhoneCode { code: "+93", country: "Afghanistan" },
    PhoneCode { code: "+94", country: "Sri Lanka" },
    PhoneCode { code: "+95", country: "Myanmar" },
    PhoneCode { code: "+960", country: "Maldives" },
    PhoneCode { code: "+961", country: "Lebanon" },
    PhoneCode { code: "+962", country: "Jordan" },
    PhoneCode { code: "+963", country: "Syrian Arab Republic" },
    PhoneCode { code: "+964", country: "Iraq" },
    PhoneCode { code: "+965", country: "Kuwait" },
    PhoneCode { code: "+966", country: "Saudi Arabia" },
    PhoneCode { code: "+967", country: "Yemen" },
    PhoneCode { code: "+968", country: "Oman" },
    PhoneCode { code: "+970", country: "Palestinian Territory, Occupied" },
    PhoneCode { code: "+971", country: "United Arab Emirates" },
    PhoneCode { code: "+972", country: "Israel" },
    PhoneCode { code: "+973", country: "Bahrain" },
    PhoneCode { code: "+974", country: "Qatar" },
    PhoneCode { code: "+975", country: "Bhutan" },
    PhoneCode { code: "+976", country: "Mongolia" },
    PhoneCode { code: "+977", country: "Nepal" },
    PhoneCode { code: "+98", country: "Iran, Islamic Republic of Persian Gulf" },
    PhoneCode { code: "+992", country: "Tajikistan" },
    PhoneCode { code: "+993", country: "Turkmenistan" },
    PhoneCode { code: "+994", country: "Azerbaijan" },
    PhoneCode { code: "+995", country: "Georgia" },
    PhoneCode { code: "+996", country: "Kyrgyzstan" },
    PhoneCode { code: "+998", country: "Uzbekistan" },
];

/// Look up a country by phone code (binary search).
pub fn lookup_phone_code(code: &str) -> Option<&'static str> {
    PHONE_CODES
        .binary_search_by_key(&code, |e| e.code)
        .ok()
        .map(|i| PHONE_CODES[i].country)
}
