//! Regex-based pattern identification — auto-generated from regex.json
use std::sync::LazyLock;
use regex::{Regex, RegexSet};

use crate::boundaryless::strip_anchors;
use crate::identifier::Match;

pub struct RegexPattern {
    pub name: &'static str,
    pub description: Option<&'static str>,
    pub rarity: f64,
    pub url: Option<&'static str>,
    pub tags: &'static [&'static str],
    pub regex_index: usize,
}

static PATTERNS: &[&str] = &[
    "^(?:-----BEGIN PGP PUBLIC KEY BLOCK-----\\n?(?:(?:(?:Version|Comment|MessageID|Hash|Charset):.*)\\n?)*[a-zA-Z0-9\\/\\.\\n\\:\\+\\=]+-----END PGP PUBLIC KEY BLOCK-----)$",
    "^(?:-----BEGIN PGP PRIVATE KEY BLOCK-----\\n?(?:(?:(?:Version|Comment|MessageID|Hash|Charset):.*)\\n?)*[a-zA-Z0-9\\/\\.\\n\\:\\+\\=]+-----END PGP PRIVATE KEY BLOCK-----)$",
    "^(ssh-rsa [A-Za-z0-9+\\/=]+ [^ \\n]+)$",
    "^(-----BEGIN( ANY| RSA| DSA| ENCRYPTED| EC| OPENSSH)? PRIVATE KEY-----\\n?[a-zA-Z0-9\\/\\.\\n\\:\\+\\=]+-----END( ANY| RSA| DSA| ENCRYPTED| EC| OPENSSH)? PRIVATE KEY-----)$",
    "^(ecdsa-sha2-nistp[0-9]{3} [A-Za-z0-9+\\/=]+ [^ \\n]+)$",
    "^(ssh-ed25519 [A-Za-z0-9+\\/=]+ [^ \\n]+)$",
    "(?i)^(Access-Control-Allow: [a-z0-9\\-*])$",
    "(?i)^(thm\\{.*\\}|tryhackme\\{.*\\})$",
    "(?i)^(hackthebox\\{.*\\}|htb\\{.*\\})$",
    "(?i)^(flag\\{.*\\}|ctf\\{.*\\}|ctfa\\{.*\\})$",
    "^(https?:\\/\\/(?:youtu\\.be\\/|(?:[a-z]{2,3}\\.)?youtube\\.com\\/watch(?:\\?|#\\!)v=)([\\w-]{11}))$",
    "(?i)^(((bitcoincash|bchreg|bchtest):)?(q|p)[a-z0-9]{41})$",
    "(?i)^(heroku.{0,30}[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})$",
    "(?i)^(xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})$",
    "(?i)^(https://hooks.slack.com/services/T[a-zA-Z0-9_]{8,10}/B[a-zA-Z0-9_]{8,10}/[a-zA-Z0-9_]{24})$",
    "(?i)^([https:\\/\\/]*s3\\.amazonaws.com[\\/]+.*|[a-zA-Z0-9_-]*\\.s3\\.amazonaws.com\\/.*)$",
    "(?i)^(s3:\\/\\/([^\\/]+)\\/(.*?([^\\/]+)\\/?))$",
    "^(sandbox-?sq0csp-[0-9A-Za-z-_]{43}|sq0[a-z]{3}-[0-9A-Za-z-_]{22,43})$",
    "^(sqOatp-[0-9A-Za-z-_]{22}|EAAA[a-zA-Z0-9-_]{60})$",
    "^([srp]k_live_[0-9a-zA-Z]{24})$",
    "^([a-zA-Z0-9_-]*:[a-zA-Z0-9_-]+@github.com*)$",
    "(?i)^(arn:(?P<Partition>[^:\\n]*):(?P<Service>[^:\\n]*):(?P<Region>[^:\\n]*):(?P<AccountID>[^:\\n]*):(?P<Ignore>(?P<ResourceType>[^:\\/\\n]*)[:\\/])?(?P<Resource>.*))$",
    "(?i)^((facebook|fb)(.{0,20})?['\\\"][0-9a-f]{32}['\\\"])$",
    "(?i)^((facebook|fb)(.{0,20})?['\\\"][0-9]{13,17}['\\\"])$",
    "(?i)^(twitter(.{0,20})?['\\\"][0-9a-z]{35,44}['\\\"])$",
    "(?i)^(twitter(.{0,20})?['\\\"][0-9a-z]{18,25}['\\\"])$",
    "^(npm_[0-9a-zA-Z]{36})$",
    "^(ghp_[0-9a-zA-Z]{36})$",
    "^(gho_[0-9a-zA-Z]{36})$",
    "^((ghu|ghs)_[0-9a-zA-Z]{36})$",
    "^(ghr_[0-9a-zA-Z]+)$",
    "(?i)^((linkedin(.{0,20})?[0-9a-z]{12}))$",
    "(?i)^(linkedin(.{0,20})?[0-9a-z]{16})$",
    "(?i)^(rk_live_[0-9a-zA-Z]{24})$",
    "(?i)^(sk_live_[0-9a-zA-Z]{24})$",
    "(?i)^(sq0csp-[ 0-9A-Za-z\\-_]{43})$",
    "(?i)^(access_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32})$",
    "(?i)^(amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
    "(?i)^(sk_[live|test]_[0-9a-z]{32})$",
    "(?i)^(ya29\\.[0-9A-Za-z\\-_]{64})$",
    "(?i)^([0-9]+\\-[0-9A-Z_]+\\.apps\\.googleusercontent\\.com)$",
    "(?i)^(hawk\\.[0-9A-Za-z\\-_]{20}\\.[0-9A-Za-z\\-_]{20})$",
    "(?i)^(oy2[a-z0-9]{43})$",
    "(?i)^(SG\\.[0-9A-Za-z\\-_]{22}\\.[0-9A-Za-z-_]{43})$",
    "(?i)^(https://creator\\.zoho\\.com/api/[A-Za-z0-9/\\-_\\.]+\\?authtoken=[A-Za-z0-9]+)$",
    "(?i)^(https://(?:www.)?hooks\\.zapier\\.com/hooks/catch/[A-Za-z0-9]+/[A-Za-z0-9]+/)$",
    "(?i)^(NRAA-[a-f0-9]{27})$",
    "(?i)^(NRI(?:I|Q)-[A-Za-z0-9\\-_]{32})$",
    "(?i)^(NRRA-[a-f0-9]{42})$",
    "(?i)^(NRSP-[a-z]{2}[0-9]{2}[a-f0-9]{31})$",
    "(?i)^(NRAK-[a-z0-9]{27})$",
    "(?i)^(https://outlook\\.office\\.com/webhook/[A-Za-z0-9\\-@]{64}/IncomingWebhook/[A-Za-z0-9\\-]{64}/[A-Za-z0-9\\-]{64})$",
    "(?i)^(AAAA[a-zA-Z0-9_-]{7}:[a-zA-Z0-9_-]{140})$",
    "(?i)^(https://calendar.google.com/calendar/embed\\?src=[A-Za-z0-9%@&;=\\-_\\./]+)$",
    "(?i)^(https?:\\/\\/(?:ptb\\.|canary\\.)?discord(?:app)?\\.com\\/api(?:\\/v\\d{1,2})?\\/webhooks\\/(\\d{17,19})\\/([\\w-]{68}))$",
    "(?i)^(https?:\\/\\/(?:api\\.|media\\.|(?P<web>www.))guilded\\.gg(?(web)\\/api|)\\/webhooks\\/[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89abAB][a-f0-9]{3}-[a-f0-9]{12}\\/[\\w]{86})$",
    "(?i)^(cloudinary://[0-9]+:[A-Za-z0-9-_.]+@[A-Za-z0-9-_.]+)$",
    "(?i)^(pypi-AgEIcHlwaS5vcmc[A-Za-z0-9-_]+)$",
    "(?i)^(shppa_[a-fA-F0-9]{32})$",
    "(?i)^(shpca_[a-fA-F0-9]{32})$",
    "(?i)^(shpat_[a-fA-F0-9]{32})$",
    "(?i)^(shpss_[a-fA-F0-9]{32})$",
    "(?i)^(dt0[a-zA-Z]{1}[0-9]{2}\\.[A-Z0-9]{24}\\.[A-Z0-9]{64})$",
    "(?i)^((arn:aws:sns:)[a-z0-9-]+:[0-9]+:[A-Za-z0-9-_]{1,128})$",
    "(?i)^(https://www\\.notion\\.so/[A-Za-z0-9-_]+/.*-[0-9a-f]{32})$",
    "(?i)^(https://[A-Za-z0-9-_]+\\.notion\\.site/.*-[0-9a-f]{32})$",
    "^((nano|xrb)_[13]{1}[1a-km-z3-9]{59})$",
    "^([^?\\n]+://totp/[^\\n]+secret=[A-Z2-7=]+[^\\n]+)$",
    "^(sshpass [^\\n]*-p[ ]+[^ ]+)$",
    "^(mount(.cifs)?\\s+[^\\n]*(username=[^, \\n]+[^\\n ]*password=[^, \\n]+|password=[^, \\n]+[^\\n ]*username=[^, \\n]+))$",
    "^(cifs\\s+[^\\n]*(username=[^, \\n]+[^\\n ]*password=[^, \\n]+|password=[^, \\n]+[^\\n ]*username=[^, \\n]+))$",
    "(?i)^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$",
    "(?i)^([0-9a-f]{32}-us[0-9]{1,2})$",
    "(?i)^((secret_)([a-zA-Z0-9]{43}))$",
    "^((?:https?:\\/\\/(?:(?:www\\.)?doi\\.org\\/)|doi:)?(10\\.[1-9][0-9]{3}[0-9]*\\/\\S+[^;,.\\s]))$",
    "^((?=.*[0-9])\\[?(?:(?:[0-9a-f]{1,4}:){7,7}[0-9a-f]{1,4}|([0-9a-f]{4}:){1,7}:|([0-9a-f]{1,4}:){1,6}:[0-9a-f]{1,4}|([0-9a-f]{1,4}:){1,5}(:[0-9a-f]{1,4}){1,2}|([0-9a-f]{1,4}:){1,4}(:[0-9a-f]{1,4}){1,3}|([0-9a-f]{1,4}:){1,3}(:[0-9a-f]{1,4}){1,4}|([0-9a-fA]{1,4}:){1,2}(:[0-9a-f]{1,4}){1,5}|[0-9a-f]{1,4}:((:[0-9a-f]{1,4}){1,6})|:((:[0-9a-f]{1,4}){1,7}|:)|fe80:(:[0-9a-f]{0,4}){0,4}%[0-9a-z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|(?:[0-9a-f]{1,4}:){1,4}:(?:(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9]))\\]?(?::[0-9]{1,5})?)$",
    "(?i)^((?:(?:(?:https?|ftp):\\/\\/(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))|(?:(?:https?|ftp):\\/\\/)?(?:[a-z0-9%.]+:[a-z0-9%]+@)?(?:(?:[a-z0-9\\_\\~]\\-?){0,62}[a-z0-9]\\.)*(?:(?:(?:[a-z0-9]\\-?){0,62}[a-z0-9])|(?:xn--[a-z0-9\\-]+))\\.(?:XN--VERMGENSBERATUNG-PWB|XN--VERMGENSBERATER-CTB|XN--CLCHC0EA0B2G2A9GCD|XN--W4R85EL8FHU5DNRA|NORTHWESTERNMUTUAL|TRAVELERSINSURANCE|XN--3OQ18VL8PN36A|XN--5SU34J936BGSG|XN--BCK1B9A5DRE4C|XN--MGBAH1A3HJKRD|XN--MGBAI9AZGQP6J|XN--MGBERP4A5D4AR|XN--XKC2DL3A5EE0H|XN--FZYS8D69UVGM|XN--MGBA7C0BBN0A|XN--MGBCPQ6GPA1A|XN--XKC2AL3HYE2A|AMERICANEXPRESS|KERRYPROPERTIES|SANDVIKCOROMANT|XN--I1B6B1A6A2E|XN--KCRX77D1X4A|XN--LGBBAT1AD8J|XN--MGBA3A4F16A|XN--MGBAAKC7DVF|XN--MGBC0A9AZCG|XN--NQV7FS00EMA|AFAMILYCOMPANY|AMERICANFAMILY|BANANAREPUBLIC|CANCERRESEARCH|COOKINGCHANNEL|KERRYLOGISTICS|WEATHERCHANNEL|XN--54B7FTA0CC|XN--6QQ986B3XL|XN--80AQECDR1A|XN--B4W605FERD|XN--FIQ228C5HS|XN--H2BREG3EVE|XN--JLQ480N2RG|XN--JLQ61U9W7B|XN--MGBA3A3EJT|XN--MGBAAM7A8H|XN--MGBAYH7GPA|XN--MGBBH1A71E|XN--MGBCA7DZDO|XN--MGBI4ECEXP|XN--MGBX4CD0AB|XN--RVC1E0AM3E|INTERNATIONAL|LIFEINSURANCE|TRAVELCHANNEL|WOLTERSKLUWER|XN--CCKWCXETD|XN--ECKVDTC9D|XN--FPCRJ9C3D|XN--FZC2C9E2C|XN--H2BRJ9C8C|XN--TIQ49XQYJ|XN--YFRO4I67O|XN--YGBI2AMMX|CONSTRUCTION|LPLFINANCIAL|SCHOLARSHIPS|VERSICHERUNG|XN--3E0B707E|XN--45BR5CYL|XN--4DBRK0CE|XN--80ADXHKS|XN--80ASEHDB|XN--8Y0A063A|XN--GCKR3F0F|XN--MGB9AWBF|XN--MGBAB2BD|XN--MGBGU82A|XN--MGBPL2FH|XN--MGBT3DHD|XN--MK1BU44C|XN--NGBC5AZD|XN--NGBE9E0A|XN--OGBPF8FL|XN--QCKA1PMC|ACCOUNTANTS|BARCLAYCARD|BLACKFRIDAY|BLOCKBUSTER|BRIDGESTONE|CALVINKLEIN|CONTRACTORS|CREDITUNION|ENGINEERING|ENTERPRISES|FOODNETWORK|INVESTMENTS|KERRYHOTELS|LAMBORGHINI|MOTORCYCLES|OLAYANGROUP|PHOTOGRAPHY|PLAYSTATION|PRODUCTIONS|PROGRESSIVE|REDUMBRELLA|WILLIAMHILL|XN--11B4C3D|XN--1CK2E1B|XN--1QQW23A|XN--2SCRJ9C|XN--3BST00M|XN--3DS443G|XN--3HCRJ9C|XN--42C2D9A|XN--45BRJ9C|XN--55QW42G|XN--6FRZ82G|XN--80AO21A|XN--9KRT00A|XN--CCK2B3B|XN--CZR694B|XN--D1ACJ3B|XN--EFVY88H|XN--FCT429K|XN--FJQ720A|XN--FLW351E|XN--G2XX48C|XN--GECRJ9C|XN--GK3AT1E|XN--H2BRJ9C|XN--HXT814E|XN--IMR513N|XN--J6W193G|XN--JVR189M|XN--KPRW13D|XN--KPRY57D|XN--MGBBH1A|XN--MGBTX2B|XN--MIX891F|XN--NYQY26A|XN--OTU796D|XN--PGBS0DH|XN--Q9JYB4C|XN--RHQV96G|XN--ROVU88B|XN--S9BRJ9C|XN--SES554G|XN--T60B56A|XN--VUQ861B|XN--W4RS40L|XN--XHQ521B|XN--ZFR164B|ACCOUNTANT|APARTMENTS|ASSOCIATES|BASKETBALL|BNPPARIBAS|BOEHRINGER|CAPITALONE|CONSULTING|CREDITCARD|CUISINELLA|EUROVISION|EXTRASPACE|FOUNDATION|HEALTHCARE|IMMOBILIEN|INDUSTRIES|MANAGEMENT|MITSUBISHI|NEXTDIRECT|PROPERTIES|PROTECTION|PRUDENTIAL|REALESTATE|REPUBLICAN|RESTAURANT|SCHAEFFLER|SWIFTCOVER|TATAMOTORS|TECHNOLOGY|UNIVERSITY|VLAANDEREN|VOLKSWAGEN|XN--30RR7Y|XN--3PXU8K|XN--45Q11C|XN--4GBRIM|XN--55QX5D|XN--5TZM5G|XN--80ASWG|XN--90A3AC|XN--9DBQ2A|XN--9ET52U|XN--C2BR7G|XN--CG4BKI|XN--CZRS0T|XN--CZRU2D|XN--FIQ64B|XN--FIQS8S|XN--FIQZ9S|XN--IO0A7I|XN--KPUT3I|XN--MXTQ1M|XN--O3CW4H|XN--PSSY2U|XN--Q7CE6A|XN--UNUP4Y|XN--WGBH1C|XN--WGBL6A|XN--Y9A3AQ|ACCENTURE|ALFAROMEO|ALLFINANZ|AMSTERDAM|ANALYTICS|AQUARELLE|BARCELONA|BLOOMBERG|CHRISTMAS|COMMUNITY|DIRECTORY|EDUCATION|EQUIPMENT|FAIRWINDS|FINANCIAL|FIRESTONE|FRESENIUS|FRONTDOOR|FURNITURE|GOLDPOINT|HISAMITSU|HOMEDEPOT|HOMEGOODS|HOMESENSE|INSTITUTE|INSURANCE|KUOKGROUP|LANCASTER|LANDROVER|LIFESTYLE|MARKETING|MARSHALLS|MELBOURNE|MICROSOFT|PANASONIC|PASSAGENS|PRAMERICA|RICHARDLI|SCJOHNSON|SHANGRILA|SOLUTIONS|STATEBANK|STATEFARM|STOCKHOLM|TRAVELERS|VACATIONS|XN--90AIS|XN--C1AVG|XN--D1ALF|XN--E1A4C|XN--FHBEI|XN--J1AEF|XN--J1AMH|XN--L1ACC|XN--NGBRX|XN--NQV7F|XN--P1ACF|XN--QXA6A|XN--TCKWE|XN--VHQUV|YODOBASHI|ABUDHABI|AIRFORCE|ALLSTATE|ATTORNEY|BARCLAYS|BAREFOOT|BARGAINS|BASEBALL|BOUTIQUE|BRADESCO|BROADWAY|BRUSSELS|BUDAPEST|BUILDERS|BUSINESS|CAPETOWN|CATERING|CATHOLIC|CIPRIANI|CITYEATS|CLEANING|CLINIQUE|CLOTHING|COMMBANK|COMPUTER|DELIVERY|DELOITTE|DEMOCRAT|DIAMONDS|DISCOUNT|DISCOVER|DOWNLOAD|ENGINEER|ERICSSON|ETISALAT|EXCHANGE|FEEDBACK|FIDELITY|FIRMDALE|FOOTBALL|FRONTIER|GOODYEAR|GRAINGER|GRAPHICS|GUARDIAN|HDFCBANK|HELSINKI|HOLDINGS|HOSPITAL|INFINITI|IPIRANGA|ISTANBUL|JPMORGAN|LIGHTING|LUNDBECK|MARRIOTT|MASERATI|MCKINSEY|MEMORIAL|MERCKMSD|MORTGAGE|OBSERVER|PARTNERS|PHARMACY|PICTURES|PLUMBING|PROPERTY|REDSTONE|RELIANCE|SAARLAND|SAMSCLUB|SECURITY|SERVICES|SHOPPING|SHOWTIME|SOFTBANK|SOFTWARE|STCGROUP|SUPPLIES|TRAINING|VANGUARD|VENTURES|VERISIGN|WOODSIDE|XN--90AE|XN--NODE|XN--P1AI|XN--QXAM|YOKOHAMA|ABOGADO|ACADEMY|AGAKHAN|ALIBABA|ANDROID|ATHLETA|AUCTION|AUDIBLE|AUSPOST|AVIANCA|BANAMEX|BAUHAUS|BENTLEY|BESTBUY|BOOKING|BROTHER|BUGATTI|CAPITAL|CARAVAN|CAREERS|CHANNEL|CHARITY|CHINTAI|CITADEL|CLUBMED|COLLEGE|COLOGNE|COMCAST|COMPANY|COMPARE|CONTACT|COOKING|CORSICA|COUNTRY|COUPONS|COURSES|CRICKET|CRUISES|DENTIST|DIGITAL|DOMAINS|EXPOSED|EXPRESS|FARMERS|FASHION|FERRARI|FERRERO|FINANCE|FISHING|FITNESS|FLIGHTS|FLORIST|FLOWERS|FORSALE|FROGANS|FUJITSU|GALLERY|GENTING|GODADDY|GROCERY|GUITARS|HAMBURG|HANGOUT|HITACHI|HOLIDAY|HOSTING|HOTELES|HOTMAIL|HYUNDAI|ISMAILI|JEWELRY|JUNIPER|KITCHEN|KOMATSU|LACAIXA|LANXESS|LASALLE|LATROBE|LECLERC|LIMITED|LINCOLN|MARKETS|MONSTER|NETBANK|NETFLIX|NETWORK|NEUSTAR|OKINAWA|OLDNAVY|ORGANIC|ORIGINS|PHILIPS|PIONEER|POLITIE|REALTOR|RECIPES|RENTALS|REVIEWS|REXROTH|SAMSUNG|SANDVIK|SCHMIDT|SCHWARZ|SCIENCE|SHIKSHA|SINGLES|STAPLES|STORAGE|SUPPORT|SURGERY|SYSTEMS|TEMASEK|THEATER|THEATRE|TICKETS|TIFFANY|TOSHIBA|TRADING|WALMART|WANGGOU|WATCHES|WEATHER|WEBSITE|WEDDING|WHOSWHO|WINDOWS|WINNERS|XFINITY|YAMAXUN|YOUTUBE|ZUERICH|ABARTH|ABBOTT|ABBVIE|AFRICA|AGENCY|AIRBUS|AIRTEL|ALIPAY|ALSACE|ALSTOM|AMAZON|ANQUAN|ARAMCO|AUTHOR|BAYERN|BEAUTY|BERLIN|BHARTI|BOSTIK|BOSTON|BROKER|CAMERA|CAREER|CASINO|CENTER|CHANEL|CHROME|CHURCH|CIRCLE|CLAIMS|CLINIC|COFFEE|COMSEC|CONDOS|COUPON|CREDIT|CRUISE|DATING|DATSUN|DEALER|DEGREE|DENTAL|DESIGN|DIRECT|DOCTOR|DUNLOP|DUPONT|DURBAN|EMERCK|ENERGY|ESTATE|EVENTS|EXPERT|FAMILY|FLICKR|FUTBOL|GALLUP|GARDEN|GEORGE|GIVING|GLOBAL|GOOGLE|GRATIS|HEALTH|HERMES|HIPHOP|HOCKEY|HOTELS|HUGHES|IMAMAT|INSURE|INTUIT|JAGUAR|JOBURG|JUEGOS|KAUFEN|KINDER|KINDLE|KOSHER|LANCIA|LATINO|LAWYER|LEFRAK|LIVING|LOCKER|LONDON|LUXURY|MADRID|MAISON|MAKEUP|MARKET|MATTEL|MOBILE|MONASH|MORMON|MOSCOW|MUSEUM|MUTUAL|NAGOYA|NATURA|NISSAN|NISSAY|NORTON|NOWRUZ|OFFICE|OLAYAN|ONLINE|ORACLE|ORANGE|OTSUKA|PFIZER|PHOTOS|PHYSIO|PICTET|QUEBEC|RACING|REALTY|REISEN|REPAIR|REPORT|REVIEW|ROCHER|ROGERS|RYUKYU|SAFETY|SAKURA|SANOFI|SCHOOL|SCHULE|SEARCH|SECURE|SELECT|SHOUJI|SOCCER|SOCIAL|STREAM|STUDIO|SUPPLY|SUZUKI|SWATCH|SYDNEY|TAIPEI|TAOBAO|TARGET|TATTOO|TENNIS|TIENDA|TJMAXX|TKMAXX|TOYOTA|TRAVEL|UNICOM|VIAJES|VIKING|VILLAS|VIRGIN|VISION|VOTING|VOYAGE|VUELOS|WALTER|WEBCAM|XIHUAN|YACHTS|YANDEX|ZAPPOS|ACTOR|ADULT|AETNA|AMFAM|AMICA|APPLE|ARCHI|AUDIO|AUTOS|AZURE|BAIDU|BEATS|BIBLE|BINGO|BLACK|BOATS|BOSCH|BUILD|CANON|CARDS|CHASE|CHEAP|CISCO|CITIC|CLICK|CLOUD|COACH|CODES|CROWN|CYMRU|DABUR|DANCE|DEALS|DELTA|DRIVE|DUBAI|EARTH|EDEKA|EMAIL|EPSON|FAITH|FEDEX|FINAL|FOREX|FORUM|GALLO|GAMES|GIFTS|GIVES|GLADE|GLASS|GLOBO|GMAIL|GREEN|GRIPE|GROUP|GUCCI|GUIDE|HOMES|HONDA|HORSE|HOUSE|HYATT|IKANO|IRISH|JETZT|KOELN|KYOTO|LAMER|LEASE|LEGAL|LEXUS|LILLY|LINDE|LIPSY|LIXIL|LOANS|LOCUS|LOTTE|LOTTO|MACYS|MANGO|MEDIA|MIAMI|MONEY|MOVIE|NEXUS|NIKON|NINJA|NOKIA|NOWTV|OMEGA|OSAKA|PARIS|PARTS|PARTY|PHONE|PHOTO|PIZZA|PLACE|POKER|PRAXI|PRESS|PRIME|PROMO|QUEST|RADIO|REHAB|REISE|RICOH|ROCKS|RODEO|RUGBY|SALON|SENER|SEVEN|SHARP|SHELL|SHOES|SKYPE|SLING|SMART|SMILE|SOLAR|SPACE|SPORT|STADA|STORE|STUDY|STYLE|SUCKS|SWISS|TATAR|TIRES|TIROL|TMALL|TODAY|TOKYO|TOOLS|TORAY|TOTAL|TOURS|TRADE|TRUST|TUNES|TUSHU|UBANK|VEGAS|VIDEO|VODKA|VOLVO|WALES|WATCH|WEBER|WEIBO|WORKS|WORLD|XEROX|YAHOO|AARP|ABLE|ADAC|AERO|AKDN|ALLY|AMEX|ARAB|ARMY|ARPA|ARTE|ASDA|ASIA|AUDI|AUTO|BABY|BAND|BANK|BBVA|BEER|BEST|BIKE|BING|BLOG|BLUE|BOFA|BOND|BOOK|BUZZ|CAFE|CALL|CAMP|CARE|CARS|CASA|CASE|CASH|CBRE|CERN|CHAT|CITI|CITY|CLUB|COOL|COOP|CYOU|DATA|DATE|DCLK|DEAL|DELL|DESI|DIET|DISH|DOCS|DUCK|DVAG|ERNI|FAGE|FAIL|FANS|FARM|FAST|FIAT|FIDO|FILM|FIRE|FISH|FLIR|FOOD|FORD|FREE|FUND|GAME|GBIZ|GENT|GGEE|GIFT|GMBH|GOLD|GOLF|GOOG|GUGE|GURU|HAIR|HAUS|HDFC|HELP|HERE|HGTV|HOST|HSBC|ICBC|IEEE|IMDB|IMMO|INFO|ITAU|JAVA|JEEP|JOBS|JPRS|KDDI|KIWI|KPMG|KRED|LAND|LEGO|LGBT|LIDL|LIFE|LIKE|LIMO|LINK|LIVE|LOAN|LOFT|LOVE|LTDA|LUXE|MAIF|MEET|MEME|MENU|MINI|MINT|MOBI|MODA|MOTO|NAME|NAVY|NEWS|NEXT|NICO|NIKE|OLLO|OPEN|PAGE|PARS|PCCW|PICS|PING|PINK|PLAY|PLUS|POHL|PORN|POST|PROD|PROF|QPON|RAID|READ|REIT|RENT|REST|RICH|RMIT|ROOM|RSVP|RUHR|SAFE|SALE|SARL|SAVE|SAXO|SCOT|SEAT|SEEK|SEXY|SHAW|SHIA|SHOP|SHOW|SILK|SINA|SITE|SKIN|SNCF|SOHU|SONG|SONY|SPOT|STAR|SURF|TALK|TAXI|TEAM|TECH|TEVA|TIAA|TIPS|TOWN|TOYS|TUBE|VANA|VISA|VIVA|VIVO|VOTE|VOTO|WANG|WEIR|WIEN|WIKI|WINE|WORK|XBOX|YOGA|ZARA|ZERO|ZONE|AAA|ABB|ABC|ACO|ADS|AEG|AFL|AIG|ANZ|AOL|APP|ART|AWS|AXA|BAR|BBC|BBT|BCG|BCN|BET|BID|BIO|BIZ|BMS|BMW|BOM|BOO|BOT|BOX|BUY|BZH|CAB|CAL|CAM|CAR|CAT|CBA|CBN|CBS|CEO|CFA|CFD|COM|CPA|CRS|CSC|DAD|DAY|DDS|DEV|DHL|DIY|DNP|DOG|DOT|DTV|DVR|EAT|ECO|EDU|ESQ|EUS|FAN|FIT|FLY|FOO|FOX|FRL|FTR|FUN|FYI|GAL|GAP|GAY|GDN|GEA|GLE|GMO|GMX|GOO|GOP|GOT|GOV|HBO|HIV|HKT|HOT|HOW|IBM|ICE|ICU|IFM|INC|ING|INK|INT|IST|ITV|JCB|JIO|JLL|JMP|JNJ|JOT|JOY|KFH|KIA|KIM|KPN|KRD|LAT|LAW|LDS|LLC|LLP|LOL|LPL|LTD|MAN|MAP|MBA|MED|MEN|MIL|MIT|MLB|MLS|MMA|MOE|MOI|MOM|MOV|MSD|MTN|MTR|NAB|NBA|NEC|NET|NEW|NFL|NGO|NHK|NOW|NRA|NRW|NTT|NYC|OBI|OFF|ONE|ONG|ONL|OOO|ORG|OTT|OVH|PAY|PET|PHD|PID|PIN|PNC|PRO|PRU|PUB|PWC|QVC|RED|REN|RIL|RIO|RIP|RUN|RWE|SAP|SAS|SBI|SBS|SCA|SCB|SES|SEW|SEX|SFR|SKI|SKY|SOY|SPA|SRL|STC|TAB|TAX|TCI|TDK|TEL|THD|TJX|TOP|TRV|TUI|TVS|UBS|UNO|UOL|UPS|VET|VIG|VIN|VIP|WED|WIN|WME|WOW|WTC|WTF|XIN|XXX|XYZ|YOU|YUN|ZIP|AC|AD|AE|AF|AG|AI|AL|AM|AO|AQ|AR|AS|AT|AU|AW|AX|AZ|BA|BB|BD|BE|BF|BG|BH|BI|BJ|BM|BN|BO|BR|BS|BT|BV|BW|BY|BZ|CA|CC|CD|CF|CG|CH|CI|CK|CL|CM|CN|CO|CR|CU|CV|CW|CX|CY|CZ|DE|DJ|DK|DM|DO|DZ|EC|EE|EG|ER|ES|ET|EU|FI|FJ|FK|FM|FO|FR|GA|GB|GD|GE|GF|GG|GH|GI|GL|GM|GN|GP|GQ|GR|GS|GT|GU|GW|GY|HK|HM|HN|HR|HT|HU|ID|IE|IL|IM|IN|IO|IQ|IR|IS|IT|JE|JM|JO|JP|KE|KG|KH|KI|KM|KN|KP|KR|KW|KY|KZ|LA|LB|LC|LI|LK|LR|LS|LT|LU|LV|LY|MA|MC|MD|ME|MG|MH|MK|ML|MM|MN|MO|MP|MQ|MR|MS|MT|MU|MV|MW|MX|MY|MZ|NA|NC|NE|NF|NG|NI|NL|NO|NP|NR|NU|NZ|OM|PA|PE|PF|PG|PH|PK|PL|PM|PN|PR|PS|PT|PW|PY|QA|RE|RO|RS|RU|RW|SA|SB|SC|SD|SE|SG|SH|SI|SJ|SK|SL|SM|SN|SO|SR|SS|ST|SU|SV|SX|SY|SZ|TC|TD|TF|TG|TH|TJ|TK|TL|TM|TN|TO|TR|TT|TV|TW|TZ|UA|UG|UK|US|UY|UZ|VA|VC|VE|VG|VI|VN|VU|WF|WS|YE|YT|ZA|ZM|ZW))(?::\\d{2,5})?(?:\\/[a-z0-9\\/\\-_%$@&()!?'=~*+:;,.]+)*\\/?(?:[?#]\\S*)*\\/?)$",
    "^((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(?::[0-9]{1,5})?)$",
    "^(([1][a-km-zA-HJ-NP-Z1-9]{25,35})|([3][a-km-zA-HJ-NP-Z1-9]{33})|(bc|tb)1(?!.*[1bio])[a-z0-9]{39,59})$",
    "(?i)^((?:(?:N|W|S|E)\\s?\\d+\\s?\\u00B0\\s?\\d+\\.?\\d*\\s?\\'?\\s?\\d*\\.?\\,?\\d*?\\\"?\\s?){1,2}|(?:\\d+\\s?\\u00B0\\s?\\d+\\s?\\'?\\s?\\d+\\.?\\,?\\d{0,}?\\\"?\\s?(?:N|W|S|E)\\s?){1,2}|(?:[-+]?(?:[0-8]?\\d+\\.\\d{4,}|90(?:\\.0+)?),\\s*[-+]?(?:180(?:\\.0+)?|(?:(?:1[0-7]\\d)|(?:[1-9]?\\d))(?:\\.\\d+)?))|(?:@\\d+\\.\\d{4,},\\d+.\\d{4,},\\d+z))$",
    "^(([0-9A-Fa-f]{2}[:]){5}[0-9A-Fa-f]{2}|([0-9A-Fa-f]{2}[-]){5}[0-9A-Fa-f]{2}|([0-9A-Fa-f]{4}[\\.]){2}[0-9A-Fa-f]{4})$",
    "^(D{1}[5-9A-HJ-NP-U]{1}[1-9A-HJ-NP-Za-km-z]{32})$",
    "^((?:[a-z0-9!#$%&'\"*+\\/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'\"*+\\/=?^_`{|}~-]+)*)@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:(?:2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\\.){3}(?:(?:2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:)\\]))$",
    "^([A-Za-z]{6}[0-9]{2}[ABCDEHLMPSTabcdehlmpst]{1}[0-9]{2}[A-Za-z]{1}[0-9]{3}[A-Za-z]{1})$",
    "^(\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*)$",
    "^(([0-9][0-9][0-9])(?<!666|000|9[0-9][0-9])(=|\\+|_|\\#|:|;|\\.|-|\\s){0,3}([1-9][1-9]|0[1-9]|[1-9]0)(=|\\+|_|\\#|:|;|\\.|-|\\s){0,3}([0-9][0-9][0-9][0-9])(?<!0000)(=|\\+|_|\\#|:|;|\\.|-|\\s){0,3}?)$",
    "^([0-9a-f]{40})$",
    "^([0-9a-f]{40})$",
    "^(UC[0-9A-Za-z_-]{21}[AQgw]{1})$",
    "^((?:N|M|O)[a-zA-Z0-9]{23}\\.[a-zA-Z0-9-_]{6}\\.[a-zA-Z0-9-_]{27})$",
    "^([0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[12345][0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12})$",
    "^(1Z[0-9A-Z]{6}[0-9]{10})$",
    "^(0[1-9]|[1-7][0-9]|8[01])(([A-Z])(\\d{4,5})|([A-Z]{2})(\\d{3,4})|([A-Z]{3})(\\d{2,3}))$",
    "^([1-9]|[12][0-9]|3[01])(|\\/|\\.|\\-|\\s)?(0[1-9]|1[12])\\2(19[0-9]{2}|200[0-9]|201[0-8])$",
    "(?i)^([48][0-9AB][1-9A-HJ-NP-Za-km-z]{93})$",
    "(?i)^((?:L|M)[a-z0-9]{33})$",
    "(?i)^(r[a-z0-9]{33})$",
    "^(3[47][0-9]{2}\\s?(?:[0-9]{4}\\s?){2}[0-9]{3})$",
    "^((?:6541|6556)[0-9]{12})$",
    "^(30[0-5][0-9]{11})$",
    "^(3(?:0[0-5]|[68][0-9])[0-9]\\s?(?:[0-9]{4}\\s?){2}[0-9]{2})$",
    "^((?:64[4-9][0-9]|65[0-9]{2}|6011)\\s?(?:[0-9]{4}\\s?){3}|622(?:1\\s?2[6-9][0-9]{2}|1\\s?[3-9][0-9]{3}|[2-8]\\s?[0-9]{4}|9\\s?[01][0-9]{3}|9\\s?2[0-5][0-9]{2})\\s?(?:[0-9]{4}\\s?){2})$",
    "^((?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)\\s?(?:[0-9]{4}\\s?){3})$",
    "^((?:5018|5020|5038|5612|5893|6304|6759|676[1-3]|0604|6390)\\s?(?:[0-9]{4}\\s?){3}\\s?(?:[0-9]{3,7})?)$",
    "^(4[0-9]{12}(?:[0-9]{3})?|4[0-9]{3}\\s(?:[0-9]{2,4}\\s?){3}(?:[0-9])?)$",
    "^(63[7-9][0-9]{13})$",
    "^((?:2131|1800|35\\d{3})\\d{11,14})$",
    "^(9[0-9]{15})$",
    "^((?:6304|6706|6709|6771)[0-9]{12,15})$",
    "^((?:6334|6767)[0-9]{12}|(?:6334|6767)[0-9]{14}|(?:6334|6767)[0-9]{15})$",
    "^((?:4903|4905|4911|4936|6333|6759)[0-9]{12}|(?:4903|4905|4911|4936|6333|6759)[0-9]{14}|(?:4903|4905|4911|4936|6333|6759)[0-9]{15}|564182[0-9]{10}|564182[0-9]{12}|564182[0-9]{13}|633110[0-9]{10}|633110[0-9]{12}|633110[0-9]{13})$",
    "(?i)^(0x[a-f0-9]{40})$",
    "^(xox[a-zA-Z]-[a-zA-Z0-9-]+)$",
    "^(o-[a-z0-9]{10,32})$",
    "^(AIza[0-9A-Za-z-_]{35})$",
    "^(ya29.[0-9A-Za-z-_]+)$",
    "^(key-[0-9a-zA-Z]{32})$",
    "^(SK[0-9a-fA-F]{32})$",
    "^(AC[a-zA-Z0-9_-]{32})$",
    "^(AP[a-zA-Z0-9_-]{32})$",
    "^(6L[0-9A-Za-z-_]{38}|6[0-9a-zA-Z_-]{39})$",
    "^(B[A-Z0-9]{9})$",
    "^([0-9]{6,}\\|[A-Za-z0-9\\-]{24,})$",
    "^(pub[a-f0-9]{32})$",
    "(?i)^((?=eyJ)(?:[a-z0-9_=\\-]{17,})\\.(?=e)(?:[a-z0-9_=\\-]{2,})\\.(?:[a-z0-9_=\\-]{43,}))$",
    "^((?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9]))$",
    "^((?<![A-Za-z0-9\\/+=])[A-Za-z0-9\\/+=]{40}(?![A-Za-z0-9\\/+=]))$",
    "(?i)^(i-([a-z0-9]{8}|[a-z0-9]{17}))$",
    "^([1-9]{1}[0-9]{9}[02468]{1})$",
    "^(EA[0-9A-Za-z]{190,})$",
    "^([0-9a-fA-F]{24})$",
    "^([0-9]{10})$",
    "^([0-9]{13})$",
    "^([0-9]{8,10})$",
    "^([0-9]{11,13})$",
    "^([0-9A-HJKMNP-TV-Z]{26})$",
    "^([a-f0-9]{32})$",
    "^([a-f0-9]{40})$",
    "^((?=.*[A-Z])(?=.*[a-z])[0-9A-Za-z_-]{10}[048AEIMQUYcgkosw]{1})$",
    "^([0-9]{10})$",
    "^([^:\\s]+[ ]?:[ ]?[^:\\s]+)$",
];

static REGEX_PATTERNS: &[RegexPattern] = &[
    RegexPattern {
        name: "PGP Public Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["PGP"],
        regex_index: 0,
    },
    RegexPattern {
        name: "PGP Private Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["PGP", "Bug Bounty"],
        regex_index: 1,
    },
    RegexPattern {
        name: "SSH RSA Public Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Credentials", "SSH Public Key"],
        regex_index: 2,
    },
    RegexPattern {
        name: "PEM-formatted Private Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Credentials", "Bug Bounty"],
        regex_index: 3,
    },
    RegexPattern {
        name: "SSH ECDSA Public Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Credentials", "SSH Public Key"],
        regex_index: 4,
    },
    RegexPattern {
        name: "SSH ED25519 Public Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Credentials", "SSH Public Key"],
        regex_index: 5,
    },
    RegexPattern {
        name: "Access-Control-Allow-Header",
        description: Some("Used for [#CAE4F1][link=https://en.wikipedia.org/wiki/Cross-origin_resource_sharing]Cross-Origin Resource Sharing (CORS)[/link][/#CAE4F1]"),
        rarity: 1.0_f64,
        url: None,
        tags: &["Networking", "Website"],
        regex_index: 6,
    },
    RegexPattern {
        name: "TryHackMe Flag Format",
        description: Some("Used for Capture The Flags at https://tryhackme.com"),
        rarity: 1.0_f64,
        url: None,
        tags: &["CTF Flag"],
        regex_index: 7,
    },
    RegexPattern {
        name: "HackTheBox Flag Format",
        description: Some("Used for Capture The Flags at https://hackthebox.eu"),
        rarity: 1.0_f64,
        url: None,
        tags: &["CTF Flag"],
        regex_index: 8,
    },
    RegexPattern {
        name: "Capture The Flag (CTF) Flag",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["CTF Flag"],
        regex_index: 9,
    },
    RegexPattern {
        name: "YouTube Video",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Media", "YouTube", "YouTube Video"],
        regex_index: 10,
    },
    RegexPattern {
        name: "Bitcoin Cash (BCH) Wallet Address",
        description: None,
        rarity: 1.0_f64,
        url: Some("https://www.blockchain.com/bch/address/"),
        tags: &["Finance", "Cryptocurrency Wallet", "Bitcoin Cash Wallet", "Bitcoin"],
        regex_index: 11,
    },
    RegexPattern {
        name: "Heroku API Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "API Keys", "Credentials", "Heroku"],
        regex_index: 12,
    },
    RegexPattern {
        name: "Slack API Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "API Keys", "Credentials", "Slack"],
        regex_index: 13,
    },
    RegexPattern {
        name: "Slack Webhook",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "API Keys", "Credentials", "Slack"],
        regex_index: 14,
    },
    RegexPattern {
        name: "Amazon Web Services Simple Storage (AWS S3) URL",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Networking", "AWS", "Bug Bounty"],
        regex_index: 15,
    },
    RegexPattern {
        name: "Amazon Web Services Simple Storage (AWS S3) Internal URL",
        description: Some("Internal URL, only accessible via the virtual private cloud."),
        rarity: 1.0_f64,
        url: None,
        tags: &["Networking", "AWS", "Bug Bounty"],
        regex_index: 16,
    },
    RegexPattern {
        name: "Square Application Secret",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Square", "Bug Bounty"],
        regex_index: 17,
    },
    RegexPattern {
        name: "Square Access Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Square", "Bug Bounty"],
        regex_index: 18,
    },
    RegexPattern {
        name: "Stripe API Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Bug Bounty", "Stripe"],
        regex_index: 19,
    },
    RegexPattern {
        name: "GitHub Access Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Bug Bounty", "GitHub"],
        regex_index: 20,
    },
    RegexPattern {
        name: "Amazon Resource Name (ARN)",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Identifiers", "Networking", "AWS", "Bug Bounty"],
        regex_index: 21,
    },
    RegexPattern {
        name: "Facebook Secret Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Facebook"],
        regex_index: 22,
    },
    RegexPattern {
        name: "Facebook Client ID",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "Facebook"],
        regex_index: 23,
    },
    RegexPattern {
        name: "Twitter Secret API Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Twitter"],
        regex_index: 24,
    },
    RegexPattern {
        name: "Twitter Client ID",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "Twitter"],
        regex_index: 25,
    },
    RegexPattern {
        name: "Node Package Manager (NPM) Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Token", "Bug Bounty", "NPM"],
        regex_index: 26,
    },
    RegexPattern {
        name: "GitHub Personal Access Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "GitHub"],
        regex_index: 27,
    },
    RegexPattern {
        name: "GitHub OAuth Access Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "GitHub"],
        regex_index: 28,
    },
    RegexPattern {
        name: "GitHub App Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "GitHub"],
        regex_index: 29,
    },
    RegexPattern {
        name: "GitHub Refresh Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "GitHub"],
        regex_index: 30,
    },
    RegexPattern {
        name: "LinkedIn Client ID",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "LinkedIn"],
        regex_index: 31,
    },
    RegexPattern {
        name: "LinkedIn Secret Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "LinkedIn"],
        regex_index: 32,
    },
    RegexPattern {
        name: "Stripe Restricted API Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Stripe"],
        regex_index: 33,
    },
    RegexPattern {
        name: "Stripe Standard API Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Stripe"],
        regex_index: 34,
    },
    RegexPattern {
        name: "Square OAuth Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Square"],
        regex_index: 35,
    },
    RegexPattern {
        name: "PayPal/Braintree Access Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "PayPal", "Braintree"],
        regex_index: 36,
    },
    RegexPattern {
        name: "MWS Auth Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Amazon", "MWS"],
        regex_index: 37,
    },
    RegexPattern {
        name: "Picatic API Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Picatic"],
        regex_index: 38,
    },
    RegexPattern {
        name: "Google OAuth Access Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Google"],
        regex_index: 39,
    },
    RegexPattern {
        name: "Google OAuth Client ID",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Google"],
        regex_index: 40,
    },
    RegexPattern {
        name: "StackHawk API Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "StackHawk"],
        regex_index: 41,
    },
    RegexPattern {
        name: "NuGet API Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "NuGet"],
        regex_index: 42,
    },
    RegexPattern {
        name: "SendGrid Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "SendGrid"],
        regex_index: 43,
    },
    RegexPattern {
        name: "Zoho Webhook Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "Zoho"],
        regex_index: 44,
    },
    RegexPattern {
        name: "Zapier Webhook Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Zapier"],
        regex_index: 45,
    },
    RegexPattern {
        name: "New Relic Admin API Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "New Relic"],
        regex_index: 46,
    },
    RegexPattern {
        name: "New Relic Insights API Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "New Relic"],
        regex_index: 47,
    },
    RegexPattern {
        name: "New Relic REST API Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "New Relic"],
        regex_index: 48,
    },
    RegexPattern {
        name: "New Relic Synthetics Location Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "New Relic"],
        regex_index: 49,
    },
    RegexPattern {
        name: "New Relic User API Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "New Relic"],
        regex_index: 50,
    },
    RegexPattern {
        name: "Microsoft Teams Webhook",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "URL", "Microsoft Teams", "Microsoft"],
        regex_index: 51,
    },
    RegexPattern {
        name: "Google FCM Server Key",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "Google"],
        regex_index: 52,
    },
    RegexPattern {
        name: "Google Calendar URI",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "URL", "Google Calendar", "Google"],
        regex_index: 53,
    },
    RegexPattern {
        name: "Discord Webhook",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "URL", "Discord"],
        regex_index: 54,
    },
    RegexPattern {
        name: "Guilded Webhook",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "URL", "Guilded"],
        regex_index: 55,
    },
    RegexPattern {
        name: "Cloudinary Credentials",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "Credentials", "Cloudinary"],
        regex_index: 56,
    },
    RegexPattern {
        name: "PyPI Upload Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "Credentials", "API Keys", "PyPI"],
        regex_index: 57,
    },
    RegexPattern {
        name: "Shopify Private App Access Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "Credentials", "API Keys", "Shopify"],
        regex_index: 58,
    },
    RegexPattern {
        name: "Shopify Custom App Access Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "Credentials", "API Keys", "Shopify"],
        regex_index: 59,
    },
    RegexPattern {
        name: "Shopify Access Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "Credentials", "API Keys", "Shopify"],
        regex_index: 60,
    },
    RegexPattern {
        name: "Shopify Shared Secret",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "Credentials", "API Keys", "Shopify"],
        regex_index: 61,
    },
    RegexPattern {
        name: "Dynatrace Token",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "Credentials", "API Keys", "Dynatrace"],
        regex_index: 62,
    },
    RegexPattern {
        name: "Amazon SNS Topic",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "AWS", "Amazon"],
        regex_index: 63,
    },
    RegexPattern {
        name: "Notion Note URI",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "URL"],
        regex_index: 64,
    },
    RegexPattern {
        name: "Notion Team Note URI",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Bug Bounty", "URL"],
        regex_index: 65,
    },
    RegexPattern {
        name: "Nano (NANO) Wallet Address",
        description: None,
        rarity: 1.0_f64,
        url: Some("https://nanocrawler.cc/explorer/account/"),
        tags: &["Finance", "Cryptocurrency Wallet", "Nano Wallet", "Nano"],
        regex_index: 66,
    },
    RegexPattern {
        name: "Time-Based One-Time Password (TOTP) URI",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Credentials", "TOTP", "Bug Bounty"],
        regex_index: 67,
    },
    RegexPattern {
        name: "SSHPass Clear Password Argument",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Credentials", "SSH", "Bug Bounty"],
        regex_index: 68,
    },
    RegexPattern {
        name: "Mount Command With Clear Credentials",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Credentials", "Bug Bounty"],
        regex_index: 69,
    },
    RegexPattern {
        name: "CIFS Fstab Entry With Clear Credentials",
        description: None,
        rarity: 1.0_f64,
        url: None,
        tags: &["Credentials", "Bug Bounty"],
        regex_index: 70,
    },
    RegexPattern {
        name: "Google Cloud Platform API Key",
        description: None,
        rarity: 0.8_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Google Cloud", "Google"],
        regex_index: 71,
    },
    RegexPattern {
        name: "Mailchimp API Key",
        description: None,
        rarity: 0.8_f64,
        url: None,
        tags: &["Bug Bounty", "API Keys", "Credentials", "Mailchimp"],
        regex_index: 72,
    },
    RegexPattern {
        name: "Notion Integration Token",
        description: Some("A Notion API integration's internal integration token."),
        rarity: 0.8_f64,
        url: None,
        tags: &["Credentials", "API Keys", "Bug Bounty"],
        regex_index: 73,
    },
    RegexPattern {
        name: "Digital Object Identifier (DOI)",
        description: None,
        rarity: 0.7_f64,
        url: None,
        tags: &["Identifiers", "Media"],
        regex_index: 74,
    },
    RegexPattern {
        name: "Internet Protocol (IP) Address Version 6",
        description: None,
        rarity: 0.7_f64,
        url: Some("https://www.shodan.io/host/"),
        tags: &["Identifiers", "Networking", "IP", "IPv6", "Bug Bounty"],
        regex_index: 75,
    },
    RegexPattern {
        name: "Uniform Resource Locator (URL)",
        description: None,
        rarity: 0.7_f64,
        url: None,
        tags: &["Identifiers", "URL"],
        regex_index: 76,
    },
    RegexPattern {
        name: "Internet Protocol (IP) Address Version 4",
        description: None,
        rarity: 0.7_f64,
        url: Some("https://www.shodan.io/host/"),
        tags: &["Identifiers", "Networking", "IP", "IPv4", "Bug Bounty"],
        regex_index: 77,
    },
    RegexPattern {
        name: "Bitcoin (₿) Wallet Address",
        description: None,
        rarity: 0.7_f64,
        url: Some("https://www.blockchain.com/btc/address/"),
        tags: &["Finance", "Cryptocurrency Wallet", "Bitcoin Wallet", "Bitcoin"],
        regex_index: 78,
    },
    RegexPattern {
        name: "Latitude & Longitude Coordinates",
        description: None,
        rarity: 0.7_f64,
        url: Some("https://www.google.com/maps/place/"),
        tags: &["Geo-location", "Lat & Long", "Coords"],
        regex_index: 79,
    },
    RegexPattern {
        name: "EUI-48 Identifier (Ethernet, WiFi, Bluetooth, etc)",
        description: None,
        rarity: 0.5_f64,
        url: Some("https://maclookup.app/search/macs/"),
        tags: &["Identifiers", "Networking", "EUI-48", "Bluetooth Address", "Ethernet Address", "WiFi Address", "Mac Address"],
        regex_index: 80,
    },
    RegexPattern {
        name: "Dogecoin (DOGE) Wallet Address",
        description: None,
        rarity: 0.5_f64,
        url: Some("https://dogechain.info/address/"),
        tags: &["Finance", "Cryptocurrency Wallet", "Dogecoin Wallet", "Dogecoin"],
        regex_index: 81,
    },
    RegexPattern {
        name: "Email Address",
        description: None,
        rarity: 0.5_f64,
        url: None,
        tags: &["Identifiers", "Credentials", "Email Address", "Email"],
        regex_index: 82,
    },
    RegexPattern {
        name: "Italian Fiscal Code",
        description: None,
        rarity: 0.5_f64,
        url: None,
        tags: &["Identifiers", "Credentials"],
        regex_index: 83,
    },
    RegexPattern {
        name: "Phone Number",
        description: None,
        rarity: 0.5_f64,
        url: None,
        tags: &["Identifiers", "Credentials", "Phone Number", "Phone"],
        regex_index: 84,
    },
    RegexPattern {
        name: "American Social Security Number",
        description: Some("An [#CAE4F1][link=https://en.wikipedia.org/wiki/Social_Security_number]American Identification Number[/link][/#CAE4F1]"),
        rarity: 0.5_f64,
        url: None,
        tags: &["Credentials", "SSN", "Social Security Number", "Bug Bounty"],
        regex_index: 85,
    },
    RegexPattern {
        name: "Bitly Secret Key",
        description: None,
        rarity: 0.5_f64,
        url: None,
        tags: &["Bug Bounty", "Credentials", "API Keys", "Bitly"],
        regex_index: 86,
    },
    RegexPattern {
        name: "Visual Studio App Center API Token",
        description: None,
        rarity: 0.5_f64,
        url: None,
        tags: &["Identifiers", "API Keys", "Bug Bounty", "Visual Studio", "Microsoft"],
        regex_index: 87,
    },
    RegexPattern {
        name: "YouTube Channel ID",
        description: None,
        rarity: 0.5_f64,
        url: Some("https://www.youtube.com/channel/"),
        tags: &["Media", "YouTube", "YouTube Channel"],
        regex_index: 88,
    },
    RegexPattern {
        name: "Discord Bot Token",
        description: None,
        rarity: 0.5_f64,
        url: None,
        tags: &["Credentials", "Token", "API Keys", "Bug Bounty", "Discord", "Discord Bot"],
        regex_index: 89,
    },
    RegexPattern {
        name: "UUID",
        description: None,
        rarity: 0.5_f64,
        url: Some("https://www.uuidtools.com/api/decode/"),
        tags: &["Identifiers", "UUID"],
        regex_index: 90,
    },
    RegexPattern {
        name: "United States Postal Service (UPS) Tracking Number",
        description: None,
        rarity: 0.5_f64,
        url: Some("https://www.ups.com/track?tracknum="),
        tags: &["Tracking", "Bug Bounty", "Identifiers", "Mailing"],
        regex_index: 91,
    },
    RegexPattern {
        name: "Turkish License Plate Number",
        description: Some("The [#CAE4F1][link=https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_Turkey]vehicle registration plate number of Turkey[/link][/#CAE4F1]"),
        rarity: 0.4_f64,
        url: None,
        tags: &["Identifiers", "License Plate", "Turkish"],
        regex_index: 92,
    },
    RegexPattern {
        name: "Date of Birth",
        description: None,
        rarity: 0.4_f64,
        url: None,
        tags: &["Identifiers", "Date of Birth", "DOB"],
        regex_index: 93,
    },
    RegexPattern {
        name: "Monero (XMR) Wallet Address",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Finance", "Cryptocurrency Wallet", "Monero Wallet", "Monero"],
        regex_index: 94,
    },
    RegexPattern {
        name: "Litecoin (LTC) Wallet Address",
        description: None,
        rarity: 0.3_f64,
        url: Some("https://live.blockcypher.com/ltc/address/"),
        tags: &["Finance", "Cryptocurrency Wallet", "Litecoin Wallet", "Litecoin"],
        regex_index: 95,
    },
    RegexPattern {
        name: "Ripple (XRP) Wallet Address",
        description: None,
        rarity: 0.3_f64,
        url: Some("https://xrpscan.com/account/"),
        tags: &["Finance", "Cryptocurrency Wallet", "Ripple Wallet", "Ripple", "XRP"],
        regex_index: 96,
    },
    RegexPattern {
        name: "American Express Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance", "AMEX CC", "Bug Bounty"],
        regex_index: 97,
    },
    RegexPattern {
        name: "BCGlobal Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance"],
        regex_index: 98,
    },
    RegexPattern {
        name: "Carte Blanche Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance"],
        regex_index: 99,
    },
    RegexPattern {
        name: "Diners Club Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance"],
        regex_index: 100,
    },
    RegexPattern {
        name: "Discover Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance", "Discover CC"],
        regex_index: 101,
    },
    RegexPattern {
        name: "MasterCard Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance", "MasterCard CC", "Bug Bounty"],
        regex_index: 102,
    },
    RegexPattern {
        name: "Maestro Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance"],
        regex_index: 103,
    },
    RegexPattern {
        name: "Visa Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance", "Visa CC", "Bug Bounty"],
        regex_index: 104,
    },
    RegexPattern {
        name: "Insta Payment Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance"],
        regex_index: 105,
    },
    RegexPattern {
        name: "JCB Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance"],
        regex_index: 106,
    },
    RegexPattern {
        name: "Korean Local Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance"],
        regex_index: 107,
    },
    RegexPattern {
        name: "Laser Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance"],
        regex_index: 108,
    },
    RegexPattern {
        name: "Solo Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance"],
        regex_index: 109,
    },
    RegexPattern {
        name: "Switch Card Number",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Credit Card", "Finance"],
        regex_index: 110,
    },
    RegexPattern {
        name: "Ethereum (ETH) Wallet Address",
        description: None,
        rarity: 0.3_f64,
        url: Some("https://etherscan.io/address/"),
        tags: &["Finance", "Cryptocurrency Wallet", "Ethereum Wallet", "Ethereum"],
        regex_index: 111,
    },
    RegexPattern {
        name: "Slack Token",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Bug Bounty", "Slack"],
        regex_index: 112,
    },
    RegexPattern {
        name: "Amazon Web Services Organization Identifier",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["Identifiers", "AWS", "Amazon"],
        regex_index: 113,
    },
    RegexPattern {
        name: "Google API Key",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Google", "Bug Bounty"],
        regex_index: 114,
    },
    RegexPattern {
        name: "Google OAuth Token",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Google", "Bug Bounty"],
        regex_index: 115,
    },
    RegexPattern {
        name: "Mailgun API Key",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Bug Bounty", "Mailgun"],
        regex_index: 116,
    },
    RegexPattern {
        name: "Twilio API Key",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Bug Bounty", "Twilio"],
        regex_index: 117,
    },
    RegexPattern {
        name: "Twilio Account SID",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Twilio"],
        regex_index: 118,
    },
    RegexPattern {
        name: "Twilio Application SID",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Twilio"],
        regex_index: 119,
    },
    RegexPattern {
        name: "Google ReCaptcha API Key",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["API Keys", "Credentials", "Google", "Bug Bounty"],
        regex_index: 120,
    },
    RegexPattern {
        name: "Amazon Standard Identification Number (ASIN)",
        description: None,
        rarity: 0.3_f64,
        url: Some("https://amzn.com/"),
        tags: &["Identifiers", "Amazon"],
        regex_index: 121,
    },
    RegexPattern {
        name: "Facebook App Token",
        description: None,
        rarity: 0.3_f64,
        url: Some("https://developers.facebook.com/tools/debug/accesstoken/?access_token="),
        tags: &["API Keys", "Bug Bounty", "Credentials", "Facebook"],
        regex_index: 122,
    },
    RegexPattern {
        name: "Datadog Client Token",
        description: None,
        rarity: 0.3_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Datadog"],
        regex_index: 123,
    },
    RegexPattern {
        name: "JSON Web Token (JWT)",
        description: None,
        rarity: 0.2_f64,
        url: None,
        tags: &["Token", "Website", "JWT Token", "JWT"],
        regex_index: 124,
    },
    RegexPattern {
        name: "Amazon Web Services Access Key",
        description: None,
        rarity: 0.2_f64,
        url: None,
        tags: &["Credentials", "API Keys", "AWS", "Amazon"],
        regex_index: 125,
    },
    RegexPattern {
        name: "Amazon Web Services Secret Access Key",
        description: None,
        rarity: 0.2_f64,
        url: None,
        tags: &["Credentials", "API Keys", "AWS", "Bug Bounty", "Amazon"],
        regex_index: 126,
    },
    RegexPattern {
        name: "Amazon Web Services EC2 Instance ID",
        description: None,
        rarity: 0.2_f64,
        url: None,
        tags: &["Identifiers", "AWS", "Amazon"],
        regex_index: 127,
    },
    RegexPattern {
        name: "Turkish Identification Number",
        description: None,
        rarity: 0.2_f64,
        url: None,
        tags: &["Credentials", "Identifiers", "Turkish"],
        regex_index: 128,
    },
    RegexPattern {
        name: "Facebook Access Token",
        description: None,
        rarity: 0.2_f64,
        url: Some("https://developers.facebook.com/tools/debug/accesstoken/?access_token="),
        tags: &["API Keys", "Bug Bounty", "Credentials", "Facebook"],
        regex_index: 129,
    },
    RegexPattern {
        name: "ObjectID",
        description: None,
        rarity: 0.0_f64,
        url: None,
        tags: &["Identifiers", "ObjectID"],
        regex_index: 130,
    },
    RegexPattern {
        name: "Recent Unix Timestamp",
        description: Some("Seconds elapsed since unix epoch: 1970, between year 2001 and 2286"),
        rarity: 0.0_f64,
        url: None,
        tags: &["UNIX Timestamp", "Timestamp", "UNIX"],
        regex_index: 131,
    },
    RegexPattern {
        name: "Recent Unix Millisecond Timestamp",
        description: Some("Milliseconds elapsed since unix epoch: 1970, between year 2001 and 2286"),
        rarity: 0.0_f64,
        url: None,
        tags: &["UNIX Timestamp", "Timestamp", "UNIX"],
        regex_index: 132,
    },
    RegexPattern {
        name: "Unix Timestamp",
        description: Some("Seconds elapsed since unix epoch: 1970"),
        rarity: 0.0_f64,
        url: None,
        tags: &["UNIX Timestamp", "Timestamp", "UNIX"],
        regex_index: 133,
    },
    RegexPattern {
        name: "Unix Millisecond Timestamp",
        description: Some("Milliseconds elapsed since unix epoch: 1970"),
        rarity: 0.0_f64,
        url: None,
        tags: &["UNIX Timestamp", "Timestamp", "UNIX"],
        regex_index: 134,
    },
    RegexPattern {
        name: "ULID",
        description: None,
        rarity: 0.0_f64,
        url: None,
        tags: &["Identifiers", "ULID"],
        regex_index: 135,
    },
    RegexPattern {
        name: "Datadog API Key",
        description: None,
        rarity: 0.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Datadog"],
        regex_index: 136,
    },
    RegexPattern {
        name: "Datadog Application Key",
        description: None,
        rarity: 0.0_f64,
        url: None,
        tags: &["API Keys", "Bug Bounty", "Credentials", "Datadog"],
        regex_index: 137,
    },
    RegexPattern {
        name: "YouTube Video ID",
        description: None,
        rarity: 0.0_f64,
        url: Some("https://www.youtube.com/watch?v="),
        tags: &["Media", "YouTube Video", "YouTube"],
        regex_index: 138,
    },
    RegexPattern {
        name: "Turkish Tax Number",
        description: None,
        rarity: 0.0_f64,
        url: None,
        tags: &["Credentials", "Identifiers", "Turkish"],
        regex_index: 139,
    },
    RegexPattern {
        name: "Key:Value Pair",
        description: None,
        rarity: 0.0_f64,
        url: None,
        tags: &["Credentials"],
        regex_index: 140,
    },
];

struct ValidatedRegexSet {
    set: RegexSet,
    /// Maps RegexSet match index -> original PATTERNS index.
    index_map: Vec<usize>,
}

static VALIDATED_REGEX_SET: LazyLock<ValidatedRegexSet> = LazyLock::new(|| {
    let mut valid_patterns = Vec::new();
    let mut index_map = Vec::new();
    for (i, pat) in PATTERNS.iter().enumerate() {
        if regex::Regex::new(pat).is_ok() {
            valid_patterns.push(*pat);
            index_map.push(i);
        }
    }
    let set = regex::RegexSetBuilder::new(&valid_patterns)
        .size_limit(64 * 1024 * 1024)
        .build()
        .unwrap();
    ValidatedRegexSet { set, index_map }
});

/// Identify a string using regex patterns, returning all matches.
pub fn identify_pattern(input: &str) -> Vec<&'static RegexPattern> {
    let vrs = &*VALIDATED_REGEX_SET;
    let matches = vrs.set.matches(input);
    let mut results = Vec::new();
    for set_idx in matches.iter() {
        let orig_idx = vrs.index_map[set_idx];
        for p in REGEX_PATTERNS.iter() {
            if p.regex_index == orig_idx {
                results.push(p);
            }
        }
    }
    results
}

struct BoundarylessRegexPatternSet {
    set: RegexSet,
    individual: Vec<Regex>,
    index_map: Vec<usize>,
}

static BOUNDARYLESS_REGEX_SET: LazyLock<BoundarylessRegexPatternSet> = LazyLock::new(|| {
    let mut valid_patterns = Vec::new();
    let mut index_map = Vec::new();
    for (i, pat) in PATTERNS.iter().enumerate() {
        let stripped = strip_anchors(pat);
        if regex::Regex::new(&stripped).is_ok() {
            valid_patterns.push(stripped);
            index_map.push(i);
        }
    }
    let set = regex::RegexSetBuilder::new(&valid_patterns)
        .size_limit(64 * 1024 * 1024)
        .build()
        .unwrap();
    let individual = valid_patterns
        .iter()
        .map(|p| regex::RegexBuilder::new(p).size_limit(64 * 1024 * 1024).build().unwrap())
        .collect();
    BoundarylessRegexPatternSet { set, individual, index_map }
});

pub fn identify_pattern_boundaryless(input: &str) -> Vec<Match> {
    let brs = &*BOUNDARYLESS_REGEX_SET;
    let set_matches = brs.set.matches(input);
    let mut results = Vec::new();

    for set_idx in set_matches.iter() {
        let orig_idx = brs.index_map[set_idx];
        let re = &brs.individual[set_idx];
        for m in re.find_iter(input) {
            for p in REGEX_PATTERNS.iter() {
                if p.regex_index == orig_idx {
                    results.push(Match {
                        matched_text: m.as_str().to_string(),
                        start: m.start(),
                        end: m.end(),
                        name: p.name.to_string(),
                        rarity: p.rarity,
                        desc: p.description.map(|s| s.to_string()),
                        url: p.url.map(|s| s.to_string()),
                        tags: p.tags.iter().map(|t| t.to_string()).collect(),
                        hashcat: None,
                        john: None,
                    });
                }
            }
        }
    }
    results
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_identify_pattern_boundaryless_finds_embedded() {
        let results = identify_pattern_boundaryless("check ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQ user@host here");
        assert!(!results.is_empty());
    }

    #[test]
    fn test_identify_pattern_boundaryless_no_match() {
        let results = identify_pattern_boundaryless("nothing here");
        assert!(results.is_empty());
    }
}
